### ISSUE TITLE
100gb+ payload

### ISSUE THREAD

**Issue by cdennis12280** [jilleb/mib2-toolbox#100]
See if you can do anything with this, if you need help testing let me know.

[CENSORED]

**Comment by tmchnko** [comment]
Do you, by any means, have a link like that for Audi related payloads? I think this could vastly boost development speeds.

**Comment by cdennis12280** [comment]
This is all I have, I recommend storing the data u need as these links will not be available forever. 

When I come across more information I will share

**Comment by tmchnko** [comment]
Alright but the Harman Link is not working. If you could fix this, would be nice.

**Comment by cdennis12280** [comment]
Fully fledged android can be installed on mib2 units and mapped to a button on the unit!!

https://youtu.be/4eWT1HPhmGg

**Comment by cdennis12280** [comment]
Updated Harman link

https://mega.nz/folder/3Y5T2Z5A#L2endnMmtyOdbjr_K1oDyw/folder/GEhkjKaQ

**Comment by jilleb** [comment]
Thanks, but let's not share this kind of content here. I don't want my repository taken down by VW lawyers

**Comment by cdennis12280** [comment]
Apologies was just sharing some stuff shared with me

**Comment by jilleb** [comment]
No problem :-) 
There's some pretty interesting things in there, maybe useful for MIB2 standard toolbox!
