### ISSUE TITLE
[REQUEST] Disable Carplay autostart

### ISSUE THREAD

**Issue by andy0172** [jilleb/mib2-toolbox#102]
As I'm using the wireless carplay modul it always connects automatically and Carplay is always in front. Is there a possibility to disable this autostart and leave the normal window in front? Thanks

**Comment by olli991** [comment]
I also thought about this. I'm also using carplay2air.
But i think if we somehow patch this out it also wont come up if you get some new notification while on another screen.

**Comment by jilleb** [comment]
I would think it's better to have this fixed on the Carplay side, just like it's done with Android Auto (it has a setting: auto start upon connecting).

**Comment by olli991** [comment]
> 
> 
> I would think it's better to have this fixed on the Carplay side, just like it's done with Android Auto (it has a setting: auto start upon connecting).

If it's this "easy" woe should actually do it. We can add a toggle into the toolbox menu to switch it on or of.

Reminder to myself: Restructure menu to cluster things better :D

**Comment by Kondax** [comment]
> I would think it's better to have this fixed on the Carplay side, just like it's done with Android Auto (it has a setting: auto start upon connecting).

I believe he means he has a wireless module, so carplay is always activated through the module even when the phone isn't connected, hence wanting to disable auto start.

**Comment by jilleb** [comment]
I found some entries in config files related to AndroidAuto getting the focus automatically.. I'll see if I can find the same for Carplay

**Comment by jilleb** [comment]
![image](https://user-images.githubusercontent.com/8352494/107130554-e46f8e80-68ce-11eb-864b-77fb05e74cd6.png)


ipod.cfg holds these settings.. pushUI sounds like a setting that autostarts carplay 🤔

**Comment by olli991** [comment]
i could try this i also have wireless adapter in my car :)

**Comment by olli991** [comment]
Tested it. Changed nothing. Didn't work.

**Comment by olli991** [comment]
@andrewleech did you maybe also found something for this case while you where editing the jars for navigation activ flag?

**Comment by andrewleech** [comment]
Wasn't looking for anything like that at the time... however some of the sections in this function look relevant: https://gitlab.com/alelec/mib2-lsd-patching/-/blob/2acc2c11b1664ad91cfbdea0ec61aabb391b57c8/patched/de/vw/mib/asl/internal/carplay/common/CarPlayModeHandling.java#L136

**Comment by olli991** [comment]
I just noticed that the navigation patch is also resolving this. Carplay isn't in the focus after the patch. It connects in the background. Sadly it also do not pop up when getting messages.

**Comment by andy0172** [comment]
I noticed the same, that sometimes its now connected in the background, but most of the time its in focus.
Even more annoying thin, the sound it all fewm inutes taking back to carplay, even if I hear normal radio, it switches to carplay for no reason and sound is of. So I have to manually go back to radio each time.. This happens sometime, but also not all the time. Might be coming from other apps on the iphone like Spotify or so.

**Comment by enaforcc2227** [comment]
hi
i activated testmode with obdeleven but toolbox not shown in GEM 4.11
MST2_EU_SK_ZR_P0480T.
please need your help.
![158680592-9e2765ec-89e1-4418-9b0e-b669b4680bdb](https://github.com/jilleb/mib2-toolbox/assets/62881714/6eaf9efc-7c7c-442b-8b23-cd043cc2e6ef)

**Comment by jilleb** [comment]
> hi i activated testmode with obdeleven but toolbox not shown in GEM 4.11 MST2_EU_SK_ZR_P0480T. no NAV please need your help. ![158680592-9e2765ec-89e1-4418-9b0e-b669b4680bdb](https://user-images.githubusercontent.com/62881714/251502999-6eaf9efc-7c7c-442b-8b23-cd043cc2e6ef.png)

This is for a different toolbox

**Comment by jilleb** [comment]
This is for mib2 HIGH, not Standard.

**Comment by enaforcc2227** [comment]
is it possible to display toolbox in MIB2 HIGH?

**Comment by jilleb** [comment]
This entire toolbox is meant for MIB2HIGH, so the answer would be yes.
