### ISSUE TITLE
[REQUEST] Skoda

### ISSUE THREAD

**Issue by voidxtz** [jilleb/mib2-toolbox#103]
hey skoda is have similar info system do it work on it if not can you make it to work ?

**Comment by jilleb** [comment]
Yes it works.

**Comment by voidxtz** [comment]
on what head unit does it work ? i have balero 2.5

**Comment by peterbensch** [comment]
Come on just read [README.md](https://github.com/jilleb/mib2-toolbox/blob/master/README.md)
