### ISSUE TITLE
[REQUEST] Script to add more usb-ethernet devices

### ISSUE THREAD

**Issue by Hphipps** [jilleb/mib2-toolbox#105]
**Is your feature request related to a problem? Please describe.**
There is only a small amount of compatible usb-ethernet devices and they're getting harder to find and very expensive.

**Describe the solution you'd like**
A script to run in the green menu that adds newer usb-ethernet devices into the device list on the MIB.

**Comment by andrewleech** [comment]
On firmware 1367 at least there are more easily findable usb ethernet adapters available: https://github.com/jilleb/mib2-toolbox/issues/119
