### ISSUE TITLE
Clear service menu logging

### ISSUE THREAD

**Issue by kentherzz** [jilleb/mib2-toolbox#11]
Is this something that could be added? You know when you hold MENU for 5 seconds then choose software/updates. You will basically see a list of all updates made to the Discover Pro unit, including firmware, patches and map upgrades. Can this list be cleared?

**Comment by jilleb** [comment]
Yes, I'm currently working on a privacy menu that has the ability to clear this.

**Comment by kentherzz** [comment]
Superb, keep up the good work!

**Comment by jilleb** [comment]
thanks! :-)


Added this with ebea36f32e60489c643c0812468ba4683aaabfeb
