### ISSUE TITLE
[BUG] Cant install Android Auto Patch - Backup problem

### ISSUE THREAD

**Issue by gpg18p8** [jilleb/mib2-toolbox#110]
Dear jilleb, 
first of all I have to thank you for this great tool and 
that you provide it for free.

I have read all your readme's and also all bug reports, but unfotunately
I havent found something similar.

First I had the metainfo2.txt error and was unable to install.
Here some infos to my device:

Teilenummer Gerät: 5NA035020D
Hardware: H55
Software: 1367
Golf MK 7.5 2019

I received now the D-link Adapter and I'm able to connect to the device and to install it manually.

Now if I try to apply the Android Auto patch, I receive following errors. Of course there is a writeable SD card in Slot1.

![20201124_142606](https://user-images.githubusercontent.com/74683114/100103872-c06ee600-2e65-11eb-8340-6cd7d825fb4f.jpg)
![20201124_142636](https://user-images.githubusercontent.com/74683114/100103897-c82e8a80-2e65-11eb-88f0-11af15ceba38.jpg)
![20201124_142749](https://user-images.githubusercontent.com/74683114/100103904-c95fb780-2e65-11eb-9972-f1a416ccbd6d.jpg)

The last screenshot is from /customization/varios/Activate 3D terrain/buildings in Carnet Google Earth (I just saw there is an open bug by yourself)

![gemib](https://user-images.githubusercontent.com/74683114/100103908-ca90e480-2e65-11eb-8a68-854a6924cfbf.jpg)

It would be great, if you could support me!

Thank you very much!
Best regards

**Comment by gpg18p8** [comment]
Hi, tried some things:
if I add this 3 variables on the top of the script patch_gal.sh the script is running without any error.

VOLUME=/net/mmx/fs/sda0
FILENAME=gal.json
ORIGINAL=/etc/eso/production/

If I check the file /etc/eso/production/gal.json I can see that all parameters are set,
but unfortunately AA is not working as expected, no difference to the unpatched Android Auto.
Unpluged phone, rebooted unit, same result.

FYi, I found an older version of Mib2-Toolbox here the script patch_gal.sh is working without problems.

But AA is unfortunately still not working as expected.
Developer mode in AA is activated, and also unknown sources, is there to be set something more on the phone in AA?

Please help! 
Thank you!
Best regards

**Comment by jilleb** [comment]
Thanks, I'll dive into it!

**Comment by jilleb** [comment]
Allright, found the mistake I've made...

```. /eso/bin/PhoneCustomer/default/util_mountsd.sh``` was missing, so $VOLUME was never set correctly.

**Comment by gpg18p8** [comment]
Ok, I'm also missing the button to restore the original settings in the AA
menu, why?

Thank you!

Chillout <notifications@github.com> schrieb am Mi., 25. Nov. 2020, 18:36:

**Comment by jilleb** [comment]
Because I removed it 😄

**Comment by gpg18p8** [comment]
With the volume variable I started.
Then the next errors appeared and I set this variables:
FILENAME=gal.json
ORIGINAL=/etc/eso/production/
The the script was running.
Thank you.

**Comment by gpg18p8** [comment]
> Because I removed it 😄

🤣 ok

**Comment by jilleb** [comment]
I think I fixed it 😉

**Comment by gpg18p8** [comment]
New Version is working without problems, tested it today.
Thank you!
