### ISSUE TITLE
[BUG] how to recovery ? 

### ISSUE THREAD

**Issue by tugais27** [jilleb/mib2-toolbox#114]
Hello, i have successful installed the toolbox in my audi q7 mib2 high. 
I patched vim, working good
Android auto work nice too
But google earth dont work after patching it. I want to recovery whit the backup file but dont find where i can do it. I don't see te recovery option.. 
Please help me

**Comment by tugais27** [comment]
After making installation again i have now the option recovery google displayed, but dont work. It always say file not found
![IMG_20201208_154252](https://user-images.githubusercontent.com/75607811/101590447-b8c54a80-39ea-11eb-92f2-f67d346b402e.jpg)

**Comment by jilleb** [comment]
Audi has different paths, so the script cannot find the fazit and correct backup directory name for your unit.
You can check if the google earth files were backed up to your unit, but they probably weren't patched to begin with 😁


However.... This feature will never enable google earth, as stated in the readme. It's only to enable 3d view in Google earth, but you would need to have Google Earth in the first place.

**Comment by tugais27** [comment]
I have google earth licence active. It was working perfect before installation. When i install the patch it says install done. I have the backup file copy in sd
