### ISSUE TITLE
The tool can’t installed language pack?

### ISSUE THREAD

**Issue by ebass23** [jilleb/mib2-toolbox#115]

**Comment by ebass23** [comment]
![Uploading 4C5B80D5-47AD-4696-995C-75388D834F16.jpeg…]()

**Comment by jilleb** [comment]
No, but of course you can write your own script to do so.

**Comment by ebass23** [comment]
![IMG_0507](https://user-images.githubusercontent.com/49875109/103170272-7b840800-4886-11eb-971c-6f231151fe92.jpeg)
![IMG_0508](https://user-images.githubusercontent.com/49875109/103170275-7d4dcb80-4886-11eb-909d-4884361154a7.jpeg)
Thank you for your answer. but i don't know programing

**Comment by jilleb** [comment]
It's possible to replace language files, but they are firmware-specific. I can add a feature to dump languages files, so you can edit them offline, and import them again.

**Comment by ebass23** [comment]
> It's possible to replace language files, but they are firmware-specific. I can add a feature to dump languages files, so you can edit them offline, and import them again.

thank you,
[WordPrediction.zip](https://github.com/jilleb/mib2-toolbox/files/5882712/WordPrediction.zip)

**Comment by jilleb** [comment]
The translation you will need to do by yourself, of course. 😁

**Comment by ebass23** [comment]
> 当然，您将需要自己进行翻译。 😁

i know  thank u 

ღ'ᴗ'ღ

**Comment by jilleb** [comment]
😁😁👍🏼👍🏼

**Comment by olli991** [comment]
We've now added a simple copy and replace language file method into the latest release. It can replace existing files. It can't install unknown languages. You also have to make sure the langugage file is compatible with your firmware, otherwise the text could be mixed up. Manual language changes or modifications are possible this way.

**Comment by 94350001** [comment]
> We've now added a simple copy and replace language file method into the latest release. It can replace existing files. It can't install unknown languages. You also have to make sure the langugage file is compatible with your firmware, otherwise the text could be mixed up. Manual language changes or modifications are possible this way.

I have a 5L0 035 200 D Škoda MIB head unit, and the fw is MST2_EU_SK_PQ_P0359T
Whenever I play MP3 files from an SD card, it displays garbled text.
It's possible to add language files?
I don't need the UI become Chinese, I only need when play mp3 files it can display corrently Chinese characters.
btw I can do emmc method.
thank you.
