### ISSUE TITLE
[REQUEST] Unlock SWAP code available in mib2

### ISSUE THREAD

**Issue by sebk95** [jilleb/mib2-toolbox#117]
Unlock all code available in my mib2

**Comment by jilleb** [comment]
Like I said in #116 and in other places (like the readme), I will not support this.
But you're more than welcome to code it yourself 😄

**Comment by sebk95** [comment]
Your project is full illegal because you modified vw SO (read mib copyright on the manual)  but if you use for personal use it isn't illegal. The people need to unlock this code because they have paid for this features yet and vw required another moneys(not have sense). Please consider that and help me to unlock. If you want i talk in private for this project
