### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HANNIBALLECTER911** [jilleb/mib2-toolbox#118]
hi, im trying to use python but only get this error code.. sure im so silly but.. need some help.. never used python before. thanks

**Comment by andrewleech** [comment]
Currently the scripts need python2 I believe, not the python3 that now comes as default. Perhaps try again with https://www.python.org/downloads/release/python-2718/

**Comment by jilleb** [comment]
All the extraction scripts do work with python 3. But using python 2 is a good idea. Haven't yet found the time to make it all work with 3.
