### ISSUE TITLE
Audi drive selection?

### ISSUE THREAD

**Issue by Hphipps** [jilleb/mib2-toolbox#120]
Is it possible to enable audi drive selection with mib toolbox?

**Comment by andrewleech** [comment]
I don't think there's anything in the toolbox for this currently. I've looked for ways to do this a couple of times in the past and generally came to the conclusion it's quite complicated and imperfect.

This is the most comprehensive guide I've found so far: http://www.audienthusiasts.com/Project_ADS.html

**Comment by vwjap** [comment]
Isn’t driving mode SWaP, I’m pretty sure I’ve played with charisma and apart form the obvious (colour change of ambient in drive modes) they didn’t seem do do much

**Comment by jilleb** [comment]
Yes, driving modes are SWaP, and the FECs need to be there on the Gateway, otherwise there won't be any profiles to select from.
The Toolbox cannot change anything about it, unfortunately.

**Comment by Hphipps** [comment]
My car originally came with audi drive select. Something happened to my 5F module and it lost all FEC codes. I was able to restore all of the codes other than ADS. Do you know the FEC code for ADS?

**Comment by vwjap** [comment]
What happened to your 5F? Did you do coding? Obd11 or vcds or VCP?

**Comment by Hphipps** [comment]
I'm not sure. Everything was working fine and then it randomly lost all FEC codes and the dealer could not fix it. I had not messed with any software before this happened either. I managed to add back most of the FEC codes but I am still missing the code for drive select.

**Comment by vwjap** [comment]
Pretty sure on the golf there’s not much in the 5F that has to do with charisma, on display on screen and maybe what can bus line it’s on, its normally in the central electronics/gateway that’s all accounted from, did you look at the link posted above about enabling it?

**Comment by Hphipps** [comment]
Yeah, non of the coding on my car was changed and its still the same as it was when it was working. I don't think VW uses charisma but Audi does. I'm pretty sure its just a FEC code. I can add it back easily but I don't know what the code is.
