### ISSUE TITLE
Fix mqbcoding.esd script paths

### ISSUE THREAD

**Issue by olli991** [jilleb/mib2-toolbox#123]
**Major flaw in current Toolbox version found!**
Current mqbcoding.esd refers to scripts in the path:
`/net/mmx/mnt/app/eso/bin/PhoneCustomer/default`
Build in script `copy_phone_customer.sh`, which is used from toolbox to import additional scripts and CHMODs them, copies everything from:
`/fs/sda0/Phone/Apps/0/default` to `/net/mmx/mnt/app/eso/bin/PhoneCustomer`
So all scripts are in the wrong directory to be used with current mqbconding.esd!
The copy script is available on the unit from stock, we shouldn't / can't change it. mqbcoding.esd needs to be changed so that all scripts will be called from the right folder and will also work again.
==> This fixed my `Execution failes: java.io.IOException: Unable to start programm` error mentioned above.

I will fix current mqbcoding.esd because for new users it is broken.

_Originally posted by @olli991 in https://github.com/jilleb/mib2-toolbox/issues/122#issuecomment-766107899_

**Comment by jilleb** [comment]
Wow that's a major flaw indeed 😅
The weird thing is.... It's working on my test units even when installing from scratch. Sometimes the phone customer script copies to the wrong folder and other times to right

**Comment by olli991** [comment]
Hmm thats interesting. Maybe this is different in firmwares? I'm working on Seat 1447 atm. I connected via telnet and viewed the content of the copy_phone_customer.sh

**Comment by jilleb** [comment]
Using 1447 as well, but originally started development on VW firmware. I think it has something to do with variables being set or so. Most of the times whenever I got the error that a script couldn't be run, I ran the script 4 times in a row...and it worked 😅😂

**Comment by olli991** [comment]
Maybe we need help here to dertime if the `copy_phone_customer.sh` scripts work different on other firmwares. I can only check Seat 1447 right now.

**Comment by jilleb** [comment]
Checked my test unit, it has all scripts in both folders, without having changed anything in the mean time 😂

**Comment by jilleb** [comment]
> Maybe we need help here to dertime if the `copy_phone_customer.sh` scripts work different on other firmwares. I can only check Seat 1447 right now.

I had a look at most common vw, Skoda and seat distributions. All had the same script.

**Comment by olli991** [comment]
> 
> 
> Checked my test unit, it has all scripts in both folders, without having changed anything in the mean time 😂

yeah mine too but I copied them with my news install method try to `/default` because I worked on the base of current mqbcoding.esd ...

**Comment by olli991** [comment]
Scripts can be anywhere if they are at least CHMOD 777. I changed this for the `/default` folder and now current esd works because it looks there. But implemented `Get new scripts` button doesn`t do anything because it CHMODs in folder above and isn't recursive.

**Comment by olli991** [comment]
Hmmm I looked back into first commit here. Toolbox was always the way that it looked to `/default` and it works back than like this....
Seems to be that it somehow copies the files sometime to default and sometimes not?! I can't explain that to me.

**Comment by jilleb** [comment]
haha, yes exactly my point. This is the one thing that I've kept the same since the beginning and could never explain why it sometimes worked and sometimes didn't.  Probably some path variable being set somewhere.

**Comment by olli991** [comment]
Okay so I tried to reproduce it but I can't.
I went into `PhoneCustomer` dir and delted all *.sh files. I also deleted all *.sh files in `PhoneCustomer/default`.
I didn't delete the `default` dir because it seems to have also special CHMOD. 

After that was clean i rebooted the unit twice, went into GreenMenu and performed `Get new scripts from SD`. I checked via Telnet and all files where written to `PhoneCustomer/default`. Rebooted several times and also deleted the files several times. They always went into `PhoneCustomer/default`. I don't know where or when the files will be moved but one thing is clear: esd don't need to be changed. Everthing seems good now. 

Will close this issue.

Sideeffect. To clear all files I made e script, we could maybe use it als general cleanup if my coding isn't completly wrong.
Next steps ins #50 

```
#!/bin/sh

#Cleanup all MQB Toolbox scripts

mount -uw /mnt/app

rm -r /mnt/app/eso/bin/PhoneCustomer/*.sh
rm -r /mnt/app/eso/bin/PhoneCustomer/default/*.sh

mount -ur /mnt/app

exit 0

```

**Comment by jilleb** [comment]
Good research 👍🏼
