### ISSUE TITLE
Enabling mib 2 app connect 

### ISSUE THREAD

**Issue by canesrefoglu25** [jilleb/mib2-toolbox#124]
Hello, I have the necessary devices. vcds, dub e 100, sd card. can you teach me how to enable app connect. my vehicle is golf 7.5. I would be grateful if you could help. thanks in advance. whatsapp number +905350656622.

**Comment by jilleb** [comment]
I will not support this kind of mods. See the readme and the template when you add a new issue.

Also removing contact info starting today. This is not a hub for potential illegal stuff.
