### ISSUE TITLE
[REQUEST] Green menu is only showing half

### ISSUE THREAD

**Issue by kec96** [jilleb/mib2-toolbox#127]
Hello

I am just install toolbox on unit but when i enter green menu and go to  mqbcoding have only two options dump and customization and in customization is only adaptations. Whay cant find other options?

**Comment by jilleb** [comment]
What version did you install?

**Comment by kec96** [comment]
I try to install version 2.2 but get metainfo.txt error and then i try with lastest version 4.0 and then i get mqdcoding menu in green menu but have only 2 options.

**Comment by kec96** [comment]
Now am i try to install experimental version 4.1 but result is same.  Only get this screen 
![Uploading 16118488669127634683879542543143.jpg…]()
![Uploading 16118488906361609348244119542779.jpg…]()

**Comment by kec96** [comment]
Now am i try to install experimental version 4.1 but result is same. Only get this screen: 
![Uploading 16118490304922888226594972040348.jpg…]()

**Comment by jilleb** [comment]
It seems like something went wrong with your upload can you try again?

**Comment by kec96** [comment]
![20210128_171611](https://user-images.githubusercontent.com/78108562/106166529-8df6a780-618c-11eb-8c65-800be4f71777.jpg)

**Comment by andrewleech** [comment]
Could you check what version of software is running on your unit?  Maybe just take a photo of the  "Software updates/versions" screen from the service menu?

**Comment by kec96** [comment]
Yes no problem here are photos

![20210128_200040](https://user-images.githubusercontent.com/78108562/106185832-ade59580-61a3-11eb-9db1-27c1e1392e14.jpg)
![20210128_200057](https://user-images.githubusercontent.com/78108562/106185846-b3db7680-61a3-11eb-8a7b-9601b857d32b.jpg)

**Comment by andrewleech** [comment]
That firmware is quite old now, perhaps that's causing the issue?

**Comment by jilleb** [comment]
Maybe installing the latest GEM.jar during install will work. It's worth a try 😁😁

**Comment by kec96** [comment]
I will try but have some instructions how to update Gem? And where can find file for update? 🙂

**Comment by kec96** [comment]
Now with this expirimental version all works well on same GEM 😃 thanks for help

**Comment by olli991** [comment]
> Now with this expirimental version all works well on same GEM 😃 thanks for help

Experimental is mostly not tested... So welcome alpha tester :D did everything work and also scripts are working for you?

**Comment by kec96** [comment]
Yes i know that is not testet yet, but because i dont want root my phone yet so i try experimental version for android auto patch and works fine. Maybe during day will try other scrips 😁

**Comment by jilleb** [comment]
😄  so I guess older firmwares can't handle the big .esd file!
Good to hear it's working. Let's close this issue.
