### ISSUE TITLE
[BUG] Toolbox does not store dump files even there is no error message / Toolbox Menue shows only two options

### ISSUE THREAD

**Issue by SnkZ68** [jilleb/mib2-toolbox#135]
Description:

Toolbox does not store dump files even there is no error message
- v.4.1 experimental not working
- v.4.0 not working

Toolbox menue shows only two options/no options
- v.4.1 experimental no options
- v.4.0 two options (dump / customization)

Firmware:
 - Brand: SEAT
 - Hardware: MIB2 High
 - Detail: 5F0035043V | H41 | MHI2_ER_SEG11_S0257 | SW MU0123

Questions:
- Specific SD Card necessary to store dump files?
- GEM requirement for Toolbox to show all menue options? (GEM v3.4 installed)
- If GEM update necessary, how should this be performed and where do I get latest GEM.jar?
- How can I delete other toolboxes? After installing 4.1 and 4.0 the green menue shows two toolboxes.

Sorry if this is not a bug and more like a user issue!

**Comment by olli991** [comment]
Did you tried with latest master commit?
There is a cleanup which is restoring all of this in it. Just perform another install via software update... if it doesn't show modules to update make a custom SWDL... if it then also isn't showing this could be a old GEM error.

Btw. your firmware is super old. What car are you driving?

**Comment by SnkZ68** [comment]
Do you mean the latest 4.0 with master commit?
Thanks for the advice I will try with SWDL. Do oyu know how to update GEM?

Im driving a March, 2015 Seat Leon Cupra 280. Do you know if there is a newer software I can update to?

**Comment by olli991** [comment]
you can go to 1447 which is latest. Only thing you will loose is you carimages because all will be replaced by facelift cars.
If toolbox works on your old version you could export those but toolbox isnt working.

Just clone the master to ZIP dont load the Release download... 4.1 is still missing there.

**Comment by SnkZ68** [comment]
Got it running!
Issue was the SD card I was using...
I tried with another one and the toolbox stored the dump files.

Could there be an issue if I jump directly from 0123 to 1447 or do I have to do some steps between?

**Comment by olli991** [comment]
Currently 1447 is missing one file in Speech and you'll get an error during install. This can be fixed if you just copy the missing file from 1409.
But for the main question if you can jump this high I don't know. One said to me you can do so but in my optinion this is a super far jump.. don't know. Do you know @jilleb ?

**Comment by jilleb** [comment]
I'd say, just go ahead and try it. I never had any issues.
