### ISSUE TITLE
[BUG] there is some chinese guy sell your code on his website

### ISSUE THREAD

**Issue by gehot** [jilleb/mib2-toolbox#137]
https://www.vwodis.com/2090.html
this guy sell your code for €38

**Comment by jilleb** [comment]
Yeah I noticed, thanks :-) . I messaged him, let's see what happens.
At least it's not like with my Performance Monitor for Android Auto that was sold for €300 somewhere 😆

**Comment by jilleb** [comment]
![image](https://user-images.githubusercontent.com/8352494/107928188-4e93cd80-6f78-11eb-894d-159f7ec36dcd.png)

Talked to the owner of the site, he removed it. Thanks for letting me know!
