### ISSUE TITLE
[Question] Screenshot on Audi Virtual Cockpit MIB2 MMI 4G

### ISSUE THREAD

**Issue by DanielVolt** [jilleb/mib2-toolbox#140]
Running it on my Audi TTS 2016, how does one take a screenshot? I tried all known key combinations but nada.

Any thoughts? 

Alvast bedankt/Thanks.

**Comment by olli991** [comment]
You can find it [here](https://procarmanuals.com/vag-ssp-648-audi-second-generation-modular-infotainment-system/) on page 16

**Comment by DanielVolt** [comment]
> You can find it [here](https://procarmanuals.com/vag-ssp-648-audi-second-generation-modular-infotainment-system/) on page 16

Olli, if i take screenshots it'll remove the speedo layer. Do you happen to know how i can enable to also take a 'full' screenshot with the speedo instead of only the background?

![ScreenShot_20210223_154947_MEDIA_PLAYER_FUL_prOn](https://user-images.githubusercontent.com/56798159/109029260-f1f48900-76c2-11eb-874e-3d86963e0c67.png)

**Comment by olli991** [comment]
I don't know if you can make dashboard screenshots.

**Comment by mattcabb** [comment]
You need to enable dev mode for VC (same procedure as in 0x5F, button 0x17 instead). Enter the VC GEM (that's a different GEM, accessible via steering wheel buttons), toggle function called something like "screenshot with joker button". Now the asterix button takes screenshots of the VC and stores them in VC internal memory.

Now, to get them, you need to dump to USB drive connected to the **VC mainboars** via flex cable.

https://youtu.be/z6uXa9qs_Ik?is=MHB3e4oKAKnsmaTU
