### ISSUE TITLE
How to install on mib2 high harman audi a3

### ISSUE THREAD

**Issue by salihkurucan** [jilleb/mib2-toolbox#142]
Is this compatible with mib2 high harman unit on audi a3? I had an attempt to install, It rebooted several times, but I cannot see [Y] This is what I see now, any suggestions ?
![1](https://user-images.githubusercontent.com/7413036/108627536-2835cc80-7467-11eb-832e-ae25bbf2b040.jpg)
![2](https://user-images.githubusercontent.com/7413036/108627538-2a982680-7467-11eb-9dab-ebf1d1b14459.jpg)
![3](https://user-images.githubusercontent.com/7413036/108627542-2c61ea00-7467-11eb-9c06-48b5ce64c4d2.jpg)
![4](https://user-images.githubusercontent.com/7413036/108627543-2d931700-7467-11eb-92a3-32423ab86279.jpg)

**Comment by olli991** [comment]
It's already installed. Clone current version it's v 4.1 with many improvements. Than you can update this way because it's newer version.

**Comment by salihkurucan** [comment]
solved!
