### ISSUE TITLE
Mapstyle copy issue

### ISSUE THREAD

**Issue by n3oka** [jilleb/mib2-toolbox#145]
Hi,

when I try to copy custom or original mapstyles, I get the following errors:

_mkdir: Function not implemented
cp: Can't create dirictory. (/net/mmx/navigation/app/resources/): Function nc (maybe: Function not implemented)

Lock picture here:
https://ibb.co/rttGYCv

Its a MIB2 HIGH crossflashed from Skoda to Seat with SW1447

**Comment by jilleb** [comment]
I'll have a look into this

**Comment by jilleb** [comment]
Updated the mapstyle feature, now it should work if you export a mapstyle to SD-card, modify it there, and run the custom mapstyle from SD (use the \customization\navigation\ screen)
