### ISSUE TITLE
cannot run patches for aa or vim

### ISSUE THREAD

**Issue by salihkurucan** [jilleb/mib2-toolbox#146]
I installed toolbox to audi a3 mib2 harman unit and first created dump files to the sd-card successfully.  But, this is what I see when I select android auto patch or vim or other scripts? It appears like scripts are not running, what am I missing?

![20210223_214126](https://user-images.githubusercontent.com/7413036/108896577-2bc38200-7626-11eb-9589-527def38c2c9.jpg)
![20210223_213214](https://user-images.githubusercontent.com/7413036/108896584-2d8d4580-7626-11eb-89c5-c6f1a1e1f7c1.jpg)

**Comment by olli991** [comment]
You installed old version of toolbox...

Von meinem iPhone gesendet

**Comment by salihkurucan** [comment]
Today, I updated from the latest repository 4.1A. It worked like a charm, this is really a good work, many thanks!
![20210225_184416](https://user-images.githubusercontent.com/7413036/109191249-07db7a00-77a7-11eb-9e72-3c76fe76c259.jpg)
