### ISSUE TITLE
[BUG] Installation Error 137 with MIB Toolbox 4.1

### ISSUE THREAD

**Issue by Sensei1978** [jilleb/mib2-toolbox#147]
On Year 2019 and 2020 i can't install the MIB2Toolbox on my MIB2HIGH. It has firmware 0687. It always comes an METAINFO error.
I tried the manual installation but i have no root password.
Now i tried the new MIB2Toolbox 4.1 with the new installation method. 
This installationpoints are successful:
If you've installed a previous version (before V4.0) of the toolbox: clean your SD-card before trying to install.
Download all files from the repository. This can be either as a git clone or "Download zip" from github then extract the zip.
Put all files and folders on an empty SD-card, preferable >1GB.
Put the SD-card in one of the slots of your MIB2-unit.
Make sure there's only 1 SD-card in your unit, otherwise the scripts don't know where to look.
Hold the MENU button on your MIB2 until the service screen appears.
Select the "Software updates/versions" menu, then hit the "Update" button in top right corner.
Select the SD-card and select MQB Coding MIB2 Toolbox.

But when my MIB2HIGH want to install the Toolbox i only get an error message: 
Error: Gerät
Error: 137
Detail: 0 
Gerät: MQB Coding MIB2 Toolbox: 0

I hoped after 2 years i can now install the MIB2Toolbox. But now i think i can never install the MIB2Toolbox on my MIB2.

**Comment by olli991** [comment]
Error 137 means there is a metainfo checksum error... maybe we've an failure in the curretn files... will check.

**Comment by olli991** [comment]
I found a checksum mismatch for the finalscript folder. Please replace metainfo2.txt and try again. You maybe need custom SWDL now to update the same module again. See commit: https://github.com/jilleb/mib2-toolbox/commit/3bb538c7f8a7334cb7a00c50f5b9cee91c0b4c2b

**Comment by Sensei1978** [comment]
I tried it again. But there is the errorcode 137 again. I think i can't install any updates, because the unit is a retrofitted unit.

**Comment by olli991** [comment]
should also work on it.
Can you please post you Train and MU version.

Do you get the 137 on Toolbox or Finalscript installation?

**Comment by Sensei1978** [comment]
I get the 137 on Toolbox.
 SW Train: MHI2_ER_VWG11_P3250
SW MU: 0687
TN: 3G0035021D
Software-Version: H28.28.62_1_HIGH2_EU

**Comment by olli991** [comment]
This is odd... could be a problem with line endings in the code... you somehow edited the files yourself?

**Comment by Sensei1978** [comment]
No i have never edited the files myself.  Because i don't have the root password. I searched many times in the Internet to find the correct password. But i never found it. Thats the reason because i can't install the toolbox manually. I think i can never install your toolbox on my mib2 unit without flashing a complete New firmware.

**Comment by olli991** [comment]
Maybe try with `Ca2MewGI` or `UaIIm8IY` maybe they work

**Comment by Sensei1978** [comment]
Thank you very much for your help. I will try it tomorrow or friday i give you a Feedback.

**Comment by andrewleech** [comment]
It seems (nor surprisingly) that branch merging can often throw out the checksums, we might want to look at changing the merge behavior for the repo.

I've just fixed the checksums and pushed directly to master so if you download a fresh copy now it'll hopefully be fixed.

**Comment by olli991** [comment]
Andrew you didn't changed much. I already edited it before. You now just made the checksum in uppercase. So I don't think this will resolve this issue.

**Comment by andrewleech** [comment]
Oh yeah, good point - I hadn't noticed that all the tool changed. Perhaps the issue is how old the firmware is.

**Comment by DukeFawks** [comment]
> I tried it again. But there is the errorcode 137 again. I think i can't install any updates, because the unit is a retrofitted unit.

This being a retrofit the unit must be patched for activations and/or component protection. There is a good chance the root password was changed and/or the public keys were altered and therefore the Metainfo signature check fails.
You can try to run the original 2021 map update to see if that gives no errors. Don't go through with the install in case you don't have the activation for them!

**Comment by olli991** [comment]
So I just released v 4.1 and also uninstalled everything from my unit before. On a stock unit, non patched, this is working all fine.
So this problem seems to be something related to your retrofitted unit which we can't account for.

**Comment by veso266** [comment]
does this still relay on POIUpdate to install, or could I finally install it on my MIB2 standard without Navigation?

**Comment by olli991** [comment]
No you can't. This isn't compatible with standard units. 

There is currently a toolbox for standard in the making but that one also is only possible an units with nav.

**Comment by umutucar39** [comment]
How did you solve the error code : 137?
