### ISSUE TITLE
need help to install the mib toolbox 

### ISSUE THREAD

**Issue by rambo165** [jilleb/mib2-toolbox#148]
so i have followed the following steps to the installation how ever when i hold the menu button and go for a update it says "unable to read the release information file. error when reading/opening the files.

what do i do here?

**Comment by olli991** [comment]
Post your current SD root stucture

**Comment by rambo165** [comment]
From the SD card it's in a folder called mib toolbox

**Comment by olli991** [comment]
Than there is your problem. Metainfo need to be in root. Your out the top folder an move everything one up.

**Comment by rambo165** [comment]
I did that the first time and I had the same problem

**Comment by olli991** [comment]
SD in FAT32? It works and woken for many people now. You structure is messed or you files. But as you don't post a Screenshot or something I can't help more. 

Also if your car was previously patched by some companies out there it could also possible they manipulated it to not allow installations. 

What train and mu version is your unit?

**Comment by rambo165** [comment]
![20210226_201046](https://user-images.githubusercontent.com/79720930/109351082-89e3a580-7870-11eb-9f42-c0c43b0182b3.jpg)
![20210226_201103](https://user-images.githubusercontent.com/79720930/109351089-8c45ff80-7870-11eb-8dc5-e7ce7abbae57.jpg)
![20210226_201648](https://user-images.githubusercontent.com/79720930/109351093-8f40f000-7870-11eb-9c4a-2f9fc30cfc0d.jpg)
![20210226_201644](https://user-images.githubusercontent.com/79720930/109351099-91a34a00-7870-11eb-8a8c-6557f3695c4e.jpg)

Its also fat32

**Comment by andrewleech** [comment]
As @olli991 said the files can't be in a folder on the SD card. Move everything out of the folder so metainfo2.txt, readme, toolbox folder etc are all directly in the SD card, not in a folder.

**Comment by rambo165** [comment]
![20210226_210812](https://user-images.githubusercontent.com/79720930/109355190-c6b29b00-7876-11eb-964d-6014e3feb122.jpg)

Done all of that and this comes up still

**Comment by rambo165** [comment]
Can you show me your folder if you don't mind

**Comment by olli991** [comment]
Your Train is MST2 so this is standard radio and not high. Toolbox only supports high version!. This isn't compatible to your radio.
