### ISSUE TITLE
[BUG] Unable to dump Skinfiles

### ISSUE THREAD

**Issue by Kondax** [jilleb/mib2-toolbox#149]
**Describe the bug**
Attempting to dump Skinfiles on Audi S4 B9 fails.

**To Reproduce**
1. Go to dump
2. Dump skin files
3. I get error `cp: Can't open source file. (/eso/hmi/lsd/Resources)`. It works fine for the startup screen dump.

**Expected behavior**
It should dump the Skinfiles.

**Firmware(please complete the following information):**
 - Brand: Audi
 - Hardware-type: MIB2High
 - Version: 1329

**Additional context**
No additional context.

**Comment by DukeFawks** [comment]
Audi has no skin files. You will also see that byte 17 (skin) of long coding is set to 00 (not supported).

**Comment by Kondax** [comment]
Ah. Bummer. That would explain it..

Is it at all possible to change the images in the VC?

**Comment by DukeFawks** [comment]
Everything is possible. But I have already bricked one VC while messing with it and that is an expensive headache. They can be unbricked but getting the ODX files for them is next to impossible and only a few are floating around. Don't mess with the VC. The very early versions (TT) from 2015 still used a Tegra30 CPU in them like MIB and you could backup the NOR/NAND before messing with it. The later ones all have shitty onboard flash in the CPU with secure enclaves and boobytraps.

**Comment by Kondax** [comment]
Just what I want to hear haha. Thanks for the advice, I guess I'll keep the RS logo.

**Comment by zergione** [comment]
Earlier Audi A4 B9 used Tegra too (2015 - ~ 2016/11). 
It can be easily be found when checking the version info 
MHI2 = Tegra
MHI2Q = Qualcomm

**Comment by Kondax** [comment]
Yes, mine is Qualcomm.
