### ISSUE TITLE
[QUESTION]  5F no respanding with VCDS and ODIS

### ISSUE THREAD

**Issue by S-Marwen** [jilleb/mib2-toolbox#151]
**Describe the bug**
After installing MIB2 Toolbox 4.1 my 5F Modul on AUDI A6 C7 FL No respanding any more with diag cable ( VCDS and ODIS) So i unstall tooobox to have back com with the modul via OBD but style nothing
If i can have help to get it back thank you

**Firmware**
 - Brand: [AUDI]
 - Hardware-type [MIB2High]
 - Version [0910]

**Comment by olli991** [comment]
I don't exactly understand what the problem is. Firmware Train would also be helpful and how you installed Toolbox etc.

**Comment by S-Marwen** [comment]
> Je ne comprends pas exactement quel est le problème. Firmware Train serait également utile et comment vous avez installé Toolbox, etc.

The probleme is after installed the toolbox when i try to scan my car with vcds or odis thay can not communicat with the modul 5F (MIB2) 
I install the toolbox with the update menu 
And my version is MHI2_ER_AU57X_k3663

**Comment by DukeFawks** [comment]
Highly unlikely that installing toolbox will cause this. More likely is that you changed something in the green menu. Another possible problem is the IOC firmware. Did you update to K3663 yourself? What year/month is the car from?

**Comment by jilleb** [comment]
When you play with the variants screen, this can be the cause.

**Comment by jilleb** [comment]
I'll take it this is fixed, as it's been silent here for over 3 months.

**Comment by Pushkaaa** [comment]
How did you fix it? Have same problem…

**Comment by Pushkaaa** [comment]
Which of the toolbox settings could couse this?

**Comment by jilleb** [comment]
The variants screen.

**Comment by Pushkaaa** [comment]
Thank you so much for the speedy reply. 
Solved my problem after more than a month :)

**Comment by Pushkaaa** [comment]
> The variants screen.

Thank you so much for the speedy reply.
Solved my problem after more than a month :)

**Comment by ANMOSIN** [comment]
How did you solve the problem?

**Comment by Pushkaaa** [comment]
Variant screen, you need to check what was changed
ZR INVALID was my diagnosis variant....

**Comment by ANMOSIN** [comment]
how do I change ZR_INVALID?
