### ISSUE TITLE
[BUG] Invalid Syntax

### ISSUE THREAD

**Issue by Sensei1978** [jilleb/mib2-toolbox#153]
Hello.
What do i make wrong?
I have the Skin0 folder with the extract-mcf.py on drive N:
But i always geht an invalid syntax error.
I used phyton 2.7 and 3.9
N:\skin0\extract_mcf.py images.mcf .\extracted\

**Comment by vwjap** [comment]
It’s not a underslash it’s a - char

**Comment by vwjap** [comment]
Also it should be ‘python extract-mcf.py n:\skin0\images.mcf .\extracted\’

**Comment by Sensei1978** [comment]
Thank you. But how did phyton know where the extract Script is? (Drive and path).

**Comment by vwjap** [comment]
It doesn’t if it’s not in a `path` directory, if extract-mcf.py isn’t in it it will come up with a error, you could just change to the n:\skin0\ directory and run `python extract-mcf.py images.mcf .\extracted\`

**Comment by Sensei1978** [comment]
I don't know what i make wrong. I installed phyton with the installer on windows 10. But what must i do now to run the script in N:\skin0.

**Comment by vwjap** [comment]
Can you take a picture for me?

**Comment by Sensei1978** [comment]
Now it's running. It was an installation error of pyhton.
But now i get a new error message:
N:\skin0>python extract-mcf.py images.mcf .\extracted\
Do you want to print the image number on each image(y/n)?: y
Traceback (most recent call last):
  File "extract-mcf.py", line 56, in <module>
    print_number = input("Do you want to print the image number on each image(y/n)?: ")
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by Sensei1978** [comment]
I deleted all sections wie y in the script. Now it works.

**Comment by Sensei1978** [comment]
I see that my car is in the skin 0 with many other cars. But how can activate my car in MIB2?

**Comment by vwjap** [comment]
What I did was change one thing (on the car that looked like mine e.g bumpers not gti) then compressed it up, loaded it into car and See if it changed, if it didn’t I went on to the next, I think it was the last batch of pictures (img900 odd) that did it
