### ISSUE TITLE
MIB2

### ISSUE THREAD

**Issue by Gismo567** [jilleb/mib2-toolbox#154]
Is het mogelijk om de gereedschapskist voor de Delphi Unit MIB2 aan te maken?

**Comment by jilleb** [comment]
https://github.com/jilleb/mib2-toolbox/blob/master/FAQ.md#when-will-you-make-a-toolbox-for-mib2-standard

Het is vast mogelijk, maar ik heb niet de hardware en tijd er voor.

**Comment by Gismo567** [comment]
Jammer dat je misschien iemand vindt waarmee je iets kunt testen.

Von meinem iPhone gesendet
