### ISSUE TITLE
 [QUESTION]  GPL source code

### ISSUE THREAD

**Issue by nrobert13** [jilleb/mib2-toolbox#156]
Hey Guys,

first of all, thanks for this great repo.
I was wondering, if these units are running linux under the hood, aren't the sellers ( VW, SEAT, SKODA, AUDI ) obliged to provide the source code of OSS running on the units?

If so, have anyone already requested them?

**Comment by andrewleech** [comment]
The MIB units aren't actually running Linux, they're built on QNX.

QNX is a proprietary OS more similar to NetBSD than Linux, it's quite popular in the automotive industry. 

Either way, it's not GPL so they're not subject to those kinds of disclosure requirements, which is over of the main reasons companies pay to use QNX.

**Comment by nrobert13** [comment]
thanks for the quick and detailed reply.

**Comment by nrobert13** [comment]
hey guys,

sorry for reopening this issue. I saw there's a way to enable ssh on the units, so I connected to my cars wlan, and tried
```
telnet 10.173.189.71 22
Trying 10.173.189.71...
Connected to 10.173.189.71.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
```

I'm a bit confused now, about 2 things:
1. I understood the ssh has to be enabled on the units, I didn't enable it, but apparently it is already enabled. 
2. The welcome string on the ssh port reveals that it's an Ubuntu system.

Am I missing something here, or is it actually strange?

**Comment by andrewleech** [comment]
Where did you get that IP address, can you confirm it from the IP addresses printout in GEM?

All of the MIB firmware images I've inspected (from VW, Skoda, Audi) are definitely QNX, not Ubuntu, and none of them include SSH by default.

**Comment by nrobert13** [comment]
Sorry, my bad. That was the IP acquired by my laptop from the unit. The units IP is actually 10.173.189.1, and no ssh port open ...
