### ISSUE TITLE
How can i recover my gal.json from Backup folder?

### ISSUE THREAD

**Issue by aleksgeko** [jilleb/mib2-toolbox#161]
Hello, how can i recovery gal.json from my backup folder?

In Customization -> Android auto -> exist just "Install Android auto custom applications patch" and nothing for recovery my original file.

Thanks!

**Comment by jilleb** [comment]
Good question. Currently there's no way to recover it. I used to have one, but removed it.

I put it back in the latest commit: 3718b3b

**Comment by stifftara** [comment]
I used it to patch AA, so at the moment i don't know what to do once i copied your new script (is the line 35 right?). Where and how i can import/use in the toolbox? Thx
