### ISSUE TITLE
[REQUEST] Modify image viewer to play videos

### ISSUE THREAD

**Issue by cdennis12280** [jilleb/mib2-toolbox#162]
Is it possible to amend the image viewer on the mib2 platform to enable playback of video codecs, mp4 etc?

**Describe the solution you'd like**
dump of image viewer program source code to enable the community to enhance its feature set.

**Describe alternatives you've considered**
This is more about continious improvement of the MIB2 /qnx platform.

**Comment by jilleb** [comment]
This is already possible, you can play videos on your unit.

**Comment by cdennis12280** [comment]
How?

**Comment by jilleb** [comment]
You can put files on your SD-card / USB, and open them in the image viewer.

**Comment by cdennis12280** [comment]
But not video files???

Charlie

**Comment by jilleb** [comment]
https://www.youtube.com/watch?v=mr-WUSQ0jNA

yes, Video files too.
