### ISSUE TITLE
AX88179 adapter not recognized.

### ISSUE THREAD

**Issue by nrobert13** [jilleb/mib2-toolbox#163]
hey Guys,

I tried an AX88179 [adapter](https://www.amazon.de/-/en/Ethernet-Adapter-Network-Compatible-Aluminium/dp/B07M91X2NW/ref=sr_1_7?dchild=1&keywords=AX88179&qid=1616915842&sr=8-7), but my unit ( SW 0897 ) doesn't recognise it. It may be related to the old firmware, as far as I can see the list in https://github.com/jilleb/mib2-toolbox/issues/119#issuecomment-761689293 , they are all newer than mine. I see these logs while plugging in the adapter.

```
Jan 01 00:09:50    5    12   100 USB-0.3:0: vid=0b95, did=1790: found control endpoint
Jan 01 00:09:50    5    12   100 USB-0.3:0: vid=0b95, did=1790: Insertion
Jan 01 00:09:50    5    12   100 USB-0.3:0: vid=0b95, did=1790: cfg 1, iface 0 alt 0: check_MS_descriptors: 19
Jan 01 00:09:50    3    29     0 pps:(1441847) Created usb-0.0.3 with .all ocb 1 -> 2

Jan 01 00:09:50    3    29     0 pps:(1441847) Created usb-0.0.3 with .all ocb 0 -> 3

Jan 01 00:09:50    5    12   100 USB-0.3:0: vid=0b95, did=1790: No match found, class=0xff
```

so the VID/PID seem to be the correct one.

I enabled ssh and logged in over wifi, was just wondering if I get the adapter working as well.
Where can I find `efs-system.img` / `usblauncher` to check if the VID/PID is present?

**Comment by andrewleech** [comment]
Sorry I've been meaning to update that list, it turns out there are a whole bunch of firmwares that include just AX88178 instead of both AX88178 and AX88179. The original grep/search I based that table on wasn't checking for both.

**Comment by nrobert13** [comment]
I see. I'll try to find the `usblauncher` script on my unit, to see what devices ID's are in there. I saw people on seatcupra.net updating their units, but not sure where they get the firmware images from, haven't found any link. Do you happen to know?

**Comment by andrewleech** [comment]
Yeah it's in /mnt/system/etc/usblauncher.lua I think. It's pretty easy to read/modify, basically lists USB vid/pid combos and the driver to use for them. On some units it uses /mnt/system/etc/usblauncher_otg.lua

**Comment by andrewleech** [comment]
The config block for AX88178 should look like 
```
-- ASIX AX88178
device(0x0b95, 0x1780) {
    driver"/etc/scripts/extnet.sh -oname=en,lan=0,busnum=$(busno),devnum=$(devno),wait=60,ign_remove,path=$(USB_PATH) /lib/dll/devnp-asix.so /dev/io-net/en0";
    removal"ifconfig en0 destroy";
};
```
You can duplicate that and change 0x1780 to 0x1790 to make it work.

**Comment by nrobert13** [comment]
thanks for the advice. I haven't got the time to test this out, returned the adapter, I guess the the wifi connection is good enough for me.  Closing this issue.
