### ISSUE TITLE
invalid image mode RGB in img_1755.png

### ISSUE THREAD

**Issue by Gal1an0** [jilleb/mib2-toolbox#164]
Hi, i'm trying to modifikate Transparent Radiostation-Background for Skoda but i'm getting an error when trying to compress.
´´invalid image mode RGB in img_1755.png
make sure to use a good image editor´´

 I copy the background img from Modifications\Graphics\Transparent Radiostation Background\Skoda change it to img_1755 and put back to the extracted folder. What i'm doing wrong ? MHI2_ER_SKG13_P1440

**Comment by c727** [comment]
I have not tested the current file but have you noticed my PR #160 to replace the Image?

**Comment by Gal1an0** [comment]
Thanks, i replace the Image and now All files are imported to images2.mcf
