### ISSUE TITLE
Restore gal.json

### ISSUE THREAD

**Issue by stifftara** [jilleb/mib2-toolbox#169]
Hi,

How can we restore the gal.json backup? Thx

**Comment by jilleb** [comment]
See here

https://github.com/jilleb/mib2-toolbox/issues/161

**Comment by stifftara** [comment]
Hi snd thanks, but i don't know how is the procedure... What i have to do? Move manualy the original gal.json or other things?
Thx

**Comment by jilleb** [comment]
No, i created a new script which is available in the latest commits.

**Comment by stifftara** [comment]
So what are the steps? Copy the script ? Download it? And how to use in the greenmenu? 
Thx

**Comment by jilleb** [comment]
Using the green menu is kind of the base for using the toolbox.. Have you used the toolbox already?

**Comment by stifftara** [comment]
I used it to patch aa, so at the moment I don't know what to do once I copy your new script (line 35 is right?).  where and how can I import / use in the toolbox?  thank you

**Comment by jilleb** [comment]
Please download the entire zip:
https://github.com/jilleb/mib2-toolbox/archive/refs/heads/master.zip

Put it on SD-card and use the update function in the toolbox. Then there will be a new function, which allows you to recover gal.json from backup.

**Comment by stifftara** [comment]
Hi, thanks for support i very appreciate. 
Unfortunally it doesn't works: i wiped my SD and copied the zip file and that's the result. 
![IMG_20210518_140820](https://user-images.githubusercontent.com/84348108/118650280-8cf19080-b7e4-11eb-8fa4-8d8263286018.jpg)
 Toolbox version is 4.12st

Thanks

**Comment by stifftara** [comment]
Of course any new function in AA section is available. So something went wrong

**Comment by jilleb** [comment]
Make sure you extracted the zipfile to the SD-card.. not just the zip

**Comment by stifftara** [comment]
I also tried but non chance, i got the same screen. I also tried to install from original mib2 menu (update in top right) but doest detect the SD (strange)

**Comment by jilleb** [comment]
Can you show me what the contens of the SD looks like?

**Comment by jilleb** [comment]
please read the readme.
https://github.com/jilleb/mib2-toolbox#how-to-install

Just place the files from the zip onto the SD
so metainfo2.txt is in the root of the SD

**Comment by stifftara** [comment]
Ok it worked, using the original menu "update". I restored the gal.json and then i unistalled the toolbox using the last command in "unistall" section. But it revoved only the "customization" menu. "Production" one remained. 
Is there a way to restore to stock the discover pro?
The point is that after the mandatory ECU update in VW, they gave me back the car and now the park assist image of the sensors doesnt appear anymore on the screen (only acoustic beep). I would to restore fully to stock the discover pro to test if parking assist issue is related. 

Thanks a lot for replies and support!

**Comment by jilleb** [comment]
The production menu is there from stock, it's delivered with the unit from factory.

You can try a full software reinstall. But it sounds like they did a mis coding of your parking assist module or MIB, which wouldn't be fixed by a software reinstall because then all adaptation and coding would be the same as it is right now. If i were you, i would go back to the dealer to have them fix it for free.

**Comment by stifftara** [comment]
I'm agree, i told her and she want me to drop back the car for a couple of days, what a inconpetence. 
I was searching for the software but but i cannot find it. 
Anyhow does the "test menu" in the service screen already exist in default?

**Comment by jilleb** [comment]
Yes, it does exist, although it's hidden from view until it's set by adaptation of the MIB to be in dev mode.

**Comment by stifftara** [comment]
Perfect thanks! Do you know if is possible to find the original software ?

**Comment by jilleb** [comment]
It depends on what version you have. But you're better off going back to the dealer to have them fix the issue they causes.

**Comment by stifftara** [comment]
I think the sw veraion is one of the last for mib2 high... I think 9130 and 1161 the MU version. 
I'm managing the situation but they are speaking about the diagnostic (they did also one yesterday of course finding nothing!) And the want me to leave the car 😤. 
Do you know if it is related to the update of ECU? or mib related?
