### ISSUE TITLE
Feature request: Keep bluetooth connection on while CarPlay/AA is in use

### ISSUE THREAD

**Issue by kentherzz** [jilleb/mib2-toolbox#17]
Is it possible to make so that bluetooth is connected to a secondary phone (for taking calls) while primary phone is connected with USB and running CarPlay/Android Auto?

**Comment by jilleb** [comment]
I highly doubt it... but it's worth researching. Currently, other things have more priority, so I'll put it on my backlog for now.

**Comment by andy0172** [comment]
I recognized that when using a wireless Carplay adapter, the Bluetooth function is still available even when Carplay is active from this adapter, but my phone is not yet connected.

Which means the bluetooth connection is only deactivated when a phone is really connected.

**Comment by jilleb** [comment]
I recently read a blog about this, and it is an issue in the Android core that will not be handled any time soon. Closing, as it's not an issue the toolbox can fix.

**Comment by andy0172** [comment]
This might be the case for Android, but with carplay its still possible to have a second phone connected to the same MIB system.

So might be you get it wrong, we want to have the MIB hacked, so that bluetooth keeps active for a second phone while carplay is connected with the first phone.
