### ISSUE TITLE
how to remove the red numbers

### ISSUE THREAD

**Issue by gehot** [jilleb/mib2-toolbox#170]
i extract the images.mcf and got the output images with res numbers

![img_884](https://user-images.githubusercontent.com/78896393/118770650-2b005c00-b8b4-11eb-9f71-f6d0f8f456cc.png)

**Comment by jilleb** [comment]
During extraction,  you get a question:

`Do you want to print the image number on each image(y/n)
`

Answer this with "n" and you will not get any numbers.

**Comment by gehot** [comment]
> During extraction, you get a question:
> 
> `Do you want to print the image number on each image(y/n) `
> 
>
