### ISSUE TITLE
[REQUEST] Fix MIB2.5 HIGH HARMAN - CarPlay GPS Issues

### ISSUE THREAD

**Issue by Bpm4Life** [jilleb/mib2-toolbox#171]
Hello there.  

I have a MIB 2.5 Harman Unit with internal memory.  My car is Seat Leon ST.  

When I connect my iPhone to the car with carplay, the iphone map shows my location incorrectly.  Is there any way to fix this?
My current software version: 1409
![IMG_3049](https://user-images.githubusercontent.com/72079606/119578615-87d4a880-bdc5-11eb-89a6-c38ac4e9c8cb.jpeg)
![IMG_3048](https://user-images.githubusercontent.com/72079606/119578636-90c57a00-bdc5-11eb-9470-be25bcbcc080.jpeg)
Please help me

**Comment by Krosta8** [comment]
Did you try to open the navigation on your phone, while it is not connected to the car? Or tried it in another car? I am not sure about that, but the position is calculated in phone, if you are using AA/CarPlay, because you are using navigation from phone, or am I mistaken?

**Comment by Bpm4Life** [comment]
Yes, before connecting the phone, I opened the map and then connected it. However, the location is instantly distorted on both the phone screen and the car's Carplay screen.  I tried it with different cable, it is the same again.
The cable connection is interestingly disrupting the phone's GPS signal.

No problem when I try it with an Android phone.

**Comment by jilleb** [comment]
Note: this is not a bug in the toolbox, so I'll change the topic.

**Comment by olli991** [comment]
Closed to inactivity
