### ISSUE TITLE
Can't access MQBCoding Menu

### ISSUE THREAD

**Issue by twisted-torque** [jilleb/mib2-toolbox#172]
Tried installing the Toolbox as per instructions, everything went fine, units restarted a couple of time and I'm back to the UI, press and hold Menu>Test Mode > Green Engineering Menu > click on MQBCoding, nothing shows..

![IMG_20210630_152443](https://user-images.githubusercontent.com/30951779/124047578-31d6ce80-da1d-11eb-837c-2aac47add249.jpg)
![IMG_20210615_193414](https://user-images.githubusercontent.com/30951779/124047587-34d1bf00-da1d-11eb-8c08-829bb9e2f9dc.jpg)

**Comment by jilleb** [comment]
Is this unit maybe patched by someone, or did it come with your car from factory?

**Comment by twisted-torque** [comment]
> Is this unit maybe patched by someone, or did it come with your car from

Structural unit number been updated or patched.

**Comment by jilleb** [comment]
Strange. I've used this exact firmware version to build the first versions of the toolbox, so it shouldn't be an issue.
Did you copy all the files to the SD-card? 
And also, what happens if you press the update button?

**Comment by twisted-torque** [comment]
I get something along the lines of path not valid or maintained, I will let you know the exact error once I'm back in the car.

As far the files go, here are what is on the SD card
![IMG_20210701_092246__01.jpg](https://user-images.githubusercontent.com/30951779/124076010-58612d80-da4e-11eb-89b9-a1fe37bf07b9.jpg)

**Comment by twisted-torque** [comment]
![IMG_20210702_220248.jpg](https://user-images.githubusercontent.com/30951779/124318411-48963600-db81-11eb-830b-39788dcba897.jpg)

**Comment by Krosta8** [comment]
I had the same issue, for me was working only the version 4.0 and maybe on fifth try. Don't know why

**Comment by jilleb** [comment]
Sometimes it happens. Keep on trying.

**Comment by twisted-torque** [comment]
> Indeed, sometimes it happens. Keep on trying, also with a different SD card. 

Tried a few times, same thing is there anyways to remove this and install again?

**Comment by twisted-torque** [comment]
Any help with this, I can't even Uninstall.

**Comment by andrewleech** [comment]
Try reformatting the SD card as fat32 on computer and download a fresh copy of the toolbox to copy on. Ideally try a different SD card in case that one is damaged.
Also use SD1 slot in car, it shouldn't matter, but most testing would use that one.
Could video the screen in car during the entire install to go back and review to look for any errors reported.

**Comment by twisted-torque** [comment]
> Try reformatting the SD card as fat32 on computer and download a fresh copy of the toolbox to copy on. Ideally try a different SD card in case that one is damaged.
> Also use SD1 slot in car, it shouldn't matter, but most testing would use that one.
> Could video the screen in car during the entire install to go back and review to look for any errors reported.

It won't allow me to update, video link 

https://streamable.com/ujmn51

**Comment by olli991** [comment]
Just check that check box for application or wait for 4.2 release. 
You need to perform custom swdl because current version is already present. Therefor you see the N. If you check this box it will overwrite.

**Comment by twisted-torque** [comment]
> Just check that check box for application or wait for 4.2 release. 
> You need to perform custom swdl because current version is already present. Therefor you see the N. If you check this box it will overwrite. 

Tried checking the box, does nothing, I guess Ill have to wait for a new release...

**Comment by olli991** [comment]
Go Testmode and then SWDL and then check the box for custom swdl and try again. 

Von meinem iPhone gesendet

**Comment by twisted-torque** [comment]
> Go Testmode and then SWDL and then check the box for custom swdl and try again. 
> 
> Von meinem iPhone gesendet
> 
> > Am 18.07.2021 um 15:32 schrieb twisted-torque ***@***.***>:
> > 
> > ﻿
> > Just check that check box for application or wait for 4.2 release.
> > You need to perform custom swdl because current version is already present. Therefor you see the N. If you check this box it will overwrite.
> > 
> > Tried checking the box, does nothing, I guess Ill have to wait for a new release...
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Thanks man, it worked after your input. 

![IMG_20210718_174304.jpg](https://user-images.githubusercontent.com/30951779/126071532-e4a7ba33-2a5c-4c4e-b5cc-1280113a6052.jpg)
