### ISSUE TITLE
Tiguan 5N Park Assist Plus, Android Auto, Camera

### ISSUE THREAD

**Issue by tiguan5n** [jilleb/mib2-toolbox#178]
Hi @jilleb, 

I was wondering if it is possible to:

- Enable wireless Android Auto
- Enable or upgrade park assist to park assist plus with the ability to control the vehicle remotely from a smartphone
- Enable activation of the area view camera when the switch is pressed, irrespective of whether the vehicle is stationary or moving

The vehicle is a 2018 VW Tiguan.

Thank you.

**Comment by olli991** [comment]
Wireless AA is not possible to activate because hardware is not present for that in the units. Use https://www.indiegogo.com/projects/aawireless#/

The rest should be coding or SWAP features which aren't activatable by this toolbox or not even managed by the radio it self.
