### ISSUE TITLE
New feature: Remove green menu

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#18]
Not to be rude, but some people really shoudn't have a green menu in their cars... I get many many mails on a daily basis from people who think they don't need to read any manual or warning, and mess up their systems... 🤕 

These people really need a button that removes the entire green menu and all of its features.
I think it's best if this will be a button with the name "FIX ALL YOUR ISSUES" 😜

**Comment by hxigor** [comment]
Agree with that!

**Comment by jilleb** [comment]
It's insane... the response I get is either:
- someone not reading anything and messing up his unit because of it
- someone demanding a toolbox for MIB2STD RIGHT NOW 😨
