### ISSUE TITLE
[REQUEST] When is the DPI Chnage going to be implemented?

### ISSUE THREAD

**Issue by malebuffy** [jilleb/mib2-toolbox#184]
Is the DPI Fix going to be implemented for split screen on unsupported devices?

https://www.drive2.com/l/594812701956415808/

**Comment by malebuffy** [comment]
I managed go do it manually. Howver having a slider to set dpi from 0 to 120 would be nice.

![20211209_220010](https://user-images.githubusercontent.com/23300461/145481012-a95bb30d-32e4-420a-9219-1031edd5ef64.jpg)

**Comment by ener2k** [comment]
> I managed to do it manually. Howver having a slider to set dpi from 0 to 120 would be nice.
> 
> ![20211209_220010](https://user-images.githubusercontent.com/23300461/145481012-a95bb30d-32e4-420a-9219-1031edd5ef64.jpg)

Can you tell me how did you change DPI to change resolution? Some instructions would be nice.

**Comment by ener2k** [comment]
> 

Ok, thank you very much, but what do you mean by built in script? where can I find the script?

**Comment by malebuffy** [comment]
MIB2-Toolbox has a built in script to patch AA. That script.

**Comment by ener2k** [comment]
> MIB2-Toolbox has a built in script to patch AA. That script.

Can I install MIB2 Toolbox on Audi A4 B9 MHI2 unit with SW version 3346?

**Comment by olli991** [comment]
Closed because with the methodmentioned in https://github.com/jilleb/mib2-toolbox/issues/184#issuecomment-1104185308 its already possible to change this
