### ISSUE TITLE
[BUG] MIB STD2 PQ SEAT 254 not save adaptations

### ISSUE THREAD

**Issue by Mirek890** [jilleb/mib2-toolbox#185]
**Describe the bug**
After installation toolbox on MIB STD2 PQ SE 254, is only possible to read adaptations, but not possible to save new values, if i try reboot button. After that I get exeptions on screen in green menu.

**To Reproduce**
1. Go to 'green menu'
2. Do 'adaptations - car_device_nus and change some adaptations'
3. I get error 'after hit Reboot button'

**Expected behavior**
system rebooted and saved adaptations

**Screenshots**
![image](https://user-images.githubusercontent.com/94869395/142930717-08826512-7456-4e35-86b9-7324649c9ae7.png)

**Firmware(please complete the following information):**
 - Brand: SEAT
 - Hardware-type MIB STD2 PQ NAV
 - Version 254

**Additional context**

**Comment by olli991** [comment]
You are in the wrong toolbox repo. This is the mhi repo and you're reporting mst errors.

But your problem is obvious. You have old GEM 3.5 which isn't supported. Please read the readme on mst toolbox repo carefully and upgrade your gem. Then it should work.
