### ISSUE TITLE
[BUG] Problem after installing 4.1 over 2.2B 

### ISSUE THREAD

**Issue by malebuffy** [jilleb/mib2-toolbox#186]
After installing the new MIB2-Toolbox via the Softwareupdate, old version of MIB Toolbox is still there (2.2) and also new version (4.0)
The 2.2 has all the menu selection of scripts, but they look mostly on folders and files that do not exists.
The 4.0 version only has the update script selection, no other script selection.

1. Install according to instruction

Screenshots
One MenuItem for MIB-Toolbox
https://photos.app.goo.gl/PuiSsv42zepT1kmu6

Two mqbconfig
https://photos.app.goo.gl/ptdJ3wANXYHknHxv6

Old version 2.2B with non working scripts
https://photos.app.goo.gl/tv9AYDSJa5evQsaCA
https://photos.app.goo.gl/qnuBp6hYQRWNo4VX8

 - Brand: AUDI
 - Hardware-type MIB2High
 - Version K3663

**Comment by olli991** [comment]
just use the cleanup button in the uninstall-menu. Should be there, even with this mixed up menus.

**Comment by malebuffy** [comment]
> just use the cleanup button in the uninstall-menu. Should be there, even with this mixed up menus.

Unfortunately there is no cleanup menu. On 4.1 there is only.one menu button like in the screenshot above "Update Scripts" and I cannot find such a button on 2.2B.

**Comment by malebuffy** [comment]
Chnaged card to another a smaller 16Gb card and it worked.
