### ISSUE TITLE
Help! MIB2.5High stuck on bootup screen

### ISSUE THREAD

**Issue by leifalbor** [jilleb/mib2-toolbox#188]
I know this software is use at your own risk - but after installing MIB Toolbox, my device (MIB2.5 Discover Pro with 9.2" touchscreen) is now stuck on the VW startup screen.  The device is still fully functional via steering wheel controls and digital cockpit screen - it's almost as if either the start up screen or the skin is corrupt.
Either way. I'm not able to interact with the device via the screen at all, nor am I able to launch the MIB Tool Green Developer menu to restore anything!  Also tried holding power button for 10+ seconds to reboot, which makes no difference.

Is there any way to force access into MIB Toolbox or to restore my devic's firmware back to factory default?

Not sure of manufacturer or model sorry (obviously I can't look it up within the device) - however it's running firmware version MHI2_ER_VWG13_P4521_MU1367

**Comment by chopinwong01** [comment]
I suspect a corrupt skin... and if you can, may be try to flash the firmware again? or you can ssh/telnet to restore backup files?

**Comment by leifalbor** [comment]
I'm not able to access the GUI at all, so can't flash firmware via the normal method.

I am able to connect in via ssh/terminal (I found a guide here -> https://pdfcoffee.com/mib2-high-nvidia-recovery-ifs-rootuifs-via-bench-access-pdf-free.html ) - however don't have backup files.

I do however have the factory firmware files (the one with the metainfo2.txt file and a heap of holders) - the big problem is I don't know how to flash these via terminal commands.  If anyone is able to guide me through the process I would be hugely grateful!

**Comment by jilleb** [comment]
Try putting a file called SWDLautorun.txt on your Sdcard with new firmware and then reboot.

Also, what did you do before this happened? Did you make any changes to coding, skins, or something? There should be a backup of the skin files on the Sdcard.

**Comment by leifalbor** [comment]
> Try putting a file called SWDLautorun.txt on your Sdcard with new firmware and then reboot.

Thanks @jilleb I've just tried this using the same firmware version installed before I installed MIB2 Toolbox.  The unit has booted up to the same stuck startup screen.  Should the unit have boot into a different screen, or does the update run in the background?

> Also, what did you do before this happened? Did you make any changes to coding, skins, or something? 

Logged into the green developer menu, applied the Android Auto custom apps patch, had a look at what other settings were available (I don't think I changed anything at this point), and rebooted.

> There should be a backup of the skin files on the Sdcard.

Unfortunately, if there was - these are gone.  I didn't realise Toolbox creates backups onto Sdcard, and in my haste to try and fix it, I turned to Google and found [this](https://www.youtube.com/watch?v=Pdel-Kb-hZ0) guide - so I wiped my Sdcard and copied original firmware onto it.  Annoyingly that guide was useless anyway because Harman units like mine have different internals to the Technisat units shown in the video

> Otherwise, you could flash app.img by writing the contents of app.img to the volume that holds it.
> 
> With the MIB2.5 firmware disk in the SD, write the new app.img from SD to mnand0t177:
> 
> on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177

I'd happily try this.  Are you able to provide or link to some instructions on how to make the connection and log in so I can enter this terminal code into the unit?

Thanks again for your help!

**Comment by leifalbor** [comment]
So another small update from me.

Putting SWDLautorun.txt on the Sdcard seems to have done nothing.  The virtual cockpit reports 'software update in progress' for a minute or so, but no further joy from there.

I found [this guide](https://pdfcoffee.com/mib2-high-hardware-recovery-pdf-free.html) which provides instructions on how to restore IFS-ROOT.IFS via PuTTY and serial connection using the debug pins on the back of the unit.  Obviously corrupt IFS-ROOT.IFS is not my issue - but I was hoping it might be a way to get the unit to accept the `on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177` command suggested by @jilleb above.

Following the linked guide I am able to at least access the unit's IPL mode.  IPL mode doesn't accept `on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177` - or it's in the wrong syntax for this mode.  Either way, I'm not inclined to go poking around the in the IPL mode menu without receiving some solid instructions first - I think I've broken enough as it is 😂.

The guide seems to suggest that terminal commands are accepted in EmergencyIFS - but when I enter it using the `boot -t emerg` command the unit does not accept any further text input during the shutdown countdown; so I can't enter the `slay -9 MIBEmergency` command as instructed.  Once the countdown ends the unit just reboots into its regular boot mode and stalls on the VW start up screen - so thats as far as I've gotten.  

@jilleb or anyone else out there - I'm really hoping you can provide some guidance to restore my unit, I'm getting very desperate here - and information online is scarce for a n00b like me.

**Comment by andrewleech** [comment]
@leifalbor take a look at https://mibwiki.one/doc/manual-firmware-restore-NglgI1RK9n also the home page on that site has some links to chat groups you can ask for help in

**Comment by leifalbor** [comment]
Thanks @andrewleech .  Tried the link you provided, won't let me view it without logging in - but the site seems to be having authentication issues; sign in fails when I try to log in using Telegram or Discord, and I never receive any email when I click 'Continue with Email'

**Comment by chopinwong01** [comment]
> Following the linked guide I am able to at least access the unit's IPL mode. IPL mode doesn't accept on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177 - or it's in the wrong syntax for this mode. Either way, I'm not inclined to go poking around the in the IPL mode menu without receiving some solid instructions first - I think I've broken enough as it is 😂.

Just wondering, do we remount it as `rw` before `dd` ?

**Comment by chopinwong01** [comment]
> Following the linked guide I am able to at least access the unit's IPL mode. IPL mode doesn't accept on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177 - or it's in the wrong syntax for this mode. Either way, I'm not inclined to go poking around the in the IPL mode menu without receiving some solid instructions first - I think I've broken enough as it is 😂.

Or we can remount app partition as `rw` and copy mounted `app.img` into it?

**Comment by jilleb** [comment]
> > Following the linked guide I am able to at least access the unit's IPL mode. IPL mode doesn't accept on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177 - or it's in the wrong syntax for this mode. Either way, I'm not inclined to go poking around the in the IPL mode menu without receiving some solid instructions first - I think I've broken enough as it is 😂.
> 
> Or we can remount app partition as `rw` and copy mounted `app.img` into it?

That's basically what I suggested by doing the DD action with the app.img

**Comment by chopinwong01** [comment]
> > > Following the linked guide I am able to at least access the unit's IPL mode. IPL mode doesn't accept on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177 - or it's in the wrong syntax for this mode. Either way, I'm not inclined to go poking around the in the IPL mode menu without receiving some solid instructions first - I think I've broken enough as it is 😂.
> > 
> > 
> > Or we can remount app partition as `rw` and copy mounted `app.img` into it?
> 
> That's basically what I suggested by doing the DD action with the app.im But you can mount it to a temp folder. And copy

Yeah it suppose to work... but somehow leifalbor had issue? may be he can post the output of errors which may help.

**Comment by jilleb** [comment]
Yes that would be helpful. I use this command in emergency mode all the time..

**Comment by leifalbor** [comment]
Hey @jilleb  @chopinwong01  

Happy to provide you with whatever you need, just tell me what you want and how to get it and I'll do it.

To provide a little more context; regarding [this process](https://pdfcoffee.com/mib2-high-nvidia-recovery-ifs-rootuifs-via-bench-access-pdf-free.html) (used to access QNX and terminal commands):

- I can get to the screen shown on the left hand side of page 6.  This screen only seems to accept the predefined commands shown in that screenshot.  If I enter `on -f mmx dd if=/net/mmx/fs/sda0/MMX2/app/70/default/app.img of=/net/mmx/dev/mnand0t177` at this point, it returns an error saying it's an unknown command.
- If I enter `boot –t emerg` the unit will boot into the screen shown on page 7.  However, the screen generates new lines every second, and does not allow me to enter the `slay -9 MIBEmergency` command.  If I try typing the command the system overwrites anything I've typed with a new countdown line.  I've also tried pasting the `slay -9 MIBEmergency` command - but PuTTY ignores this and the countdown continues.  Once the countdown reaches zero, the unit reboots into normal mode.


Also - can I get you to confirm which pins you want me using?  I'd been using the J5 RCC pins.  Should I be using the MMX ESO pins instead?
![image](https://user-images.githubusercontent.com/29937194/147796715-9c6f2377-41ba-4cab-97e3-453403862964.png)

Thanks again guys!  I'll have another look at this in the car today, and see if I can get some screenshots of EXACTLY what I'm doing and how the system responds.  I'll update this post with any new information when I have it.

**Comment by DukeFawks** [comment]
Contact me on Telegram @dukefawks, should be easy fix.

**Comment by leifalbor** [comment]
Problem resolved.  Huge thanks to @DukeFawks who was able to re-set the incorrectly applied skin via long coding using serial terminal internal interface in emergency boot mode.
