### ISSUE TITLE
Google maps for mib2 not booting

### ISSUE THREAD

**Issue by larakiabdel** [jilleb/mib2-toolbox#191]
Hello administrator,

I know that you know that google maps doesn't work since dec 2020. There is people immensely profiting from this and billing us 200-300$ for a fix. I know that i am close to an answer. I've digging since 2 weeks now. I just need a clew. Please help. The guy sent me a ZIP containing an info taking files from my googl earth in my MMI. Now there is a file named SD_INFO.dat. But i can't see what's in it i need a special software i think. Personnally i think there is a link to change in the init files google earth in the MMI. i am scared oh install the mib tools because i recall reading in your posts that it doesn't work for Audis. I've been taking lots of infos. I bought the usb to eth cable that i need to change the name to match the dlink cable by ubuntu. So ill be abl to access the mib root files. I just need a little push, if you can push me that will be amazing brotha. Thanks in advance

**Comment by gregb884** [comment]
Hi , i to work with this problem , i think then it's necessary to replace server address it with this one free server https://www.opengee.org/geedocs/5.3.7/index.html , but i don't know where is googleserver info in mib , if you manage to find the file where it is, let me know.

**Comment by larakiabdel** [comment]
I think this link is just an index for google earth docs for the install on mobile or something. I read a little bit but can't find the proper link

**Comment by gregb884** [comment]
Can you send me this ZIP with SD_INFO ? i try open on other linux system

**Comment by olli991** [comment]
If it's just a change of the URL/IP you're requesting then just edit the host file and reroute the adress to the new one

**Comment by larakiabdel** [comment]
Oh wow i never saw this message. I will send it to you as soon as possible.

**Comment by gregb884** [comment]
Ok thx 👍Wysłane z iPhone'aWiadomość napisana przez larakiabdel ***@***.***> w dniu 11.10.2022, o godz. 09:34:﻿
Oh wow i never saw this message. I will send it to you as soon as possible.
