### ISSUE TITLE
wrong path for update images.mcf

### ISSUE THREAD

**Issue by alm-123** [jilleb/mib2-toolbox#193]
**Describe the bug**
I try to update images.mcf in my skin1 (vw tiguan),
when I add my file to Custom\Skinfiles\Skin1\images.mcf the error appear Can't open source file
If copy this to root folder Skinfiles\Skin1\images.mcf - everything is ok
Tollbox 4.1

**To Reproduce**
1. copy images.mcf to Custom\Skinfiles\Skin1\
2. try to update images.mcf
3. I get error 'Can't open source file'

**Expected behavior**

**Screenshots**
![grFaVgYlsXCvUeXapREm_-Nou70-1920](https://user-images.githubusercontent.com/98448071/151115972-e321b165-7ab2-456f-9772-e3f0743e6fb8.jpg)

**Firmware(please complete the following information):**
 - VW
 - MIB2High
 - Version 1367

**Comment by olli991** [comment]
Thats rly odd because skin folder is defined as following:
`for skin_folder in $VOLUME/Custom/Skinfiles/skin*; do`

and afterwards we are coping the files from that path:
`cp -f $skin_folder/images.mcf $MIBPATH`

Are you acutally using latest realese?

**Comment by alm-123** [comment]
yes, old version 2.7, sorry, my mistake
