### ISSUE TITLE
Issue with Active Navigation Ignore

### ISSUE THREAD

**Issue by NPinUK** [jilleb/mib2-toolbox#195]
**Describe the bug**
When trying to patch Active Navigation Ignore now no longer green menu works

I updated my toolbox from 4.1 to 4.2A but 1st added added the files from NavActiveIgnore.jar into the LSD folder.

However like butOkt after import GEM.jar from Custom/GEM/ I can no longer go into the Green menu.
When I click on test mode it goes onto the next screen showing title of Green Menu but then clicking on this just takes you to a black screen

Can no longer reinstall toolbox from backup as can not get onto the green menu.... Or reinstall tool box again as the start button is not highlited because its recognising same version number. 

Any ideas?
Version MHI2_ER_VWG13_P4521_MU1367

Maybe next update can have different version number to allow update.

**Comment by andrewleech** [comment]
> However like butOkt after import GEM.jar from Custom/GEM/ I can no longer go into the Green menu.

What do you mean here, did you run an import gem menu item in toolbox?

**Comment by NPinUK** [comment]
Ok I will close this now as I manage to redo a full recovery by re applying my original firmware. This has got the green menu working again. Re did tool box and applied the patch and all working. Nav on AID works whilst google maps running. Thanks for all efforts and help.
