### ISSUE TITLE
Patch swdownload to accept any metainfo2.txt

### ISSUE THREAD

**Issue by ifirsov** [jilleb/mib2-toolbox#196]
Hi!

Is it possible to add script for patching swdownload to accept any metainfo2.txt like in https://github.com/olli991/mib-std2-pq-zr-toolbox ?

**Comment by andrewleech** [comment]
On Harman / high units you can simply patch the metainfo to make it accepted by any system after modification with https://gitlab.com/alelec/mib2-update-hashes/-/releases

Copy the exe onto the SD card with your modified metainfo / contents and run it, it'll patch / update hashes as needed.

This works the same way as the metainfo for toolbox itself.

**Comment by olli991** [comment]
Metainfo behind signature backdoor can do everything. No need to patch swdownload. Toolbox runs the same way.
