### ISSUE TITLE
Apple CarPlay has broken

### ISSUE THREAD

**Issue by igorer123** [jilleb/mib2-toolbox#197]
I have a MIB2 HIGH unit, after installing the MIB2 High toolbox and applying the Ignore navigation-active status from smartphone patch, Apple Carplay stopped working, the iPhone sees it, but does not start. Moreover, Android Auto works properly. iOS is the latest up-to-date, the cable is native, working and tested on another car.
Can I somehow fix it or roll it back to working condition?

![Без названия 2](https://user-images.githubusercontent.com/93133205/153550775-ad5b2b8a-fe46-4cbb-8482-73dea790548c.jpg)
>

**Comment by andrewleech** [comment]
Can you share the brand / version (train) of firmware running on your unit?

The carplay Java code in particular seems to differ more than most between versions of mib firmware. 

Currently the only way to disable the patch is via console, eg. SSH / Telnet 

https://github.com/jilleb/mib2-toolbox/pull/189#issuecomment-1004448576

https://github.com/jilleb/mib2-toolbox/wiki/SSH-Login

I really should add another menu item to disable it from gem...

**Comment by igorer123** [comment]
As long as I remember version  MHI2_ER_VWG11_K3332_MU1187

**Comment by andrewleech** [comment]
Ah, that means your unit would be compatible with MHI2_ER_VWG11_K3342_MU1427 which is the version i developed with, upgrading to that would be a great way forward. You could get more assistance with that if needed on the telegram channel https://t.me/joinchat/T_pADdwJyUXq0VoH

**Comment by fateman99** [comment]
I had the same issue but on an older FW version. MHI2_ER_VWG11_S2125. 
Installing the ignore active smartphone navi patch broke the carplay alltogether. 

I've since upgraded to a MU0814 and then to MU1427 FW where on both versions the carplay is working just as it's supposed to. But I have been hasitant to apply the patch on the latest FW even though it is a version you developed it for in a fear it might break the carplay once again. 

I do not have a dlink adapter so I guess I would have to find someone who would be able to fix it for me. 

If there was a "undo" patch as you have mentioned that would be great and I would feel much more comfortable applying the patch. 


![23DAEBAC-724F-4409-94EE-074D7C443759](https://user-images.githubusercontent.com/98986714/152431093-26b166f6-ef11-4bf8-8a4b-edc30348557a.jpeg)

**Comment by cptapple** [comment]
Went from MHI2_ER_VWG11_S2125 to K3342 then patched.
This patch works for AA but not for Carplay, same issue as with original poster

**Comment by cptapple** [comment]
> 

The uninstall script works and fixes Carplay.

**Comment by adrianmihalko** [comment]
Is there any way to make this work on MHI2_ER_VWG11_S2125 for both AA & Carplay? This patch is the main reason why I want to install this mod.

**Comment by andrewleech** [comment]
@adrianmihalko I don't think it will be possible to support such an old firmware, much better if you can update the firmware on your unit first.

**Comment by adrianmihalko** [comment]
> @adrianmihalko I don't think it will be possible to support such an old firmware, much better if you can update the firmware on your unit first.

Thank you. Somehow I need to find a way how to upgrade my SW. Unfortunately I have have no one around me who would be help me with that.

**Comment by dandamc** [comment]
Hello, is there any changes or way how to make it work…? Same problem here…
![60E327EA-6DD4-40A9-B92D-FA6A931BC088](https://user-images.githubusercontent.com/79792897/185393793-d9c21be1-4159-42fc-8342-c161e12a82f8.jpeg)

**Comment by dandamc** [comment]
Before we have this fw and it does same problem, that carplay wont work anymore (tried different phones). So decided to update to k3342 without any change…
![D2E79D87-A8B7-442E-9B4F-0CDE59635179](https://user-images.githubusercontent.com/79792897/185394253-cadccd97-5261-400f-add6-d48f68fa7816.jpeg)

**Comment by andrewleech** [comment]
@dandamc you've got MHI2_ER_VWG11_K3342_MU1427 which is the same MU version as my unit I developed on, so it should work there. What exact problem are you seeing, can carplay not connect at all? Or does maps start but the navigation stuff not work?

The older 0814 definitely will not have worked, but the upgrade the 1427 should have fixed it. Perhaps try uninstall of the patch in the toolbox menus, then install it again.

**Comment by dandamc** [comment]
@andrewleech the problem is that after ignore navigation status patch carplay doesnt start anymore. It shows you that you connected phone but it comes with info that connection cant be eastablished… when i go to gem and uninstall patch of ignore navigation data then it comes back to work after mu restart…

**Comment by andrewleech** [comment]
@dandamc that's strange and unfortunate, perhaps there's some other setting/adaptation enabled on your unit that breaks the patch. 

The only way to diagnose issues like this is via Java Logging which is a bit harder to get to. The best method I've come up with so far is quite manual, documented here: https://gitlab.com/alelec/mib2-lsd-patching/-/wikis/home

I'm hoping to add a function on toolbox to do this automatically, hasn't happened yet though.

**Comment by igorer123** [comment]
I also reflashed MIB2 with the firmware you suggested MHI2_ER_VWG11_K3342_MU1427. The situation has not changed CarPlay also does not start. I applied and removed the patch several times and nothing changes. Moreover, Android Auto with the patch works properly.

**Comment by dandamc** [comment]
@andrewleech i think that on this unit is no other patch, it is stock unit with services unlocked directly in vw service centre… so there shouldnt be any other setting/adaptation i hope…

I am intrested and I will try java loging to get to know where problems comes from. Does it means connection through dlink for example?

**Comment by andrewleech** [comment]
> @andrewleech i think that on this unit is no other patch, it is stock unit with services unlocked directly in vw service centre… so there shouldnt be any other setting/adaptation i hope…

Every unit has a multitude of different settings / adaptations / long-coding - these are all the official settings that are different for each brand of car / country / installed features in car. 

For example I have heard of someone who's car natually allowed built-in nav on VC while AA is on mib without this patch, it just wouldn't allow navigation on both at once. Having map visible on both seemed to be from one of the adaptation / long-coding settings but we haven't figured out which one yet.

> I am intrested and I will try java loging to get to know where problems comes from. Does it means connection through dlink for example?

I've figured out a simpler method of enableing Java Logging and turned it into a toolbox script to enable/disable in this PR: https://github.com/jilleb/mib2-toolbox/pull/216
