### ISSUE TITLE
Issue patching CID OFF SD CARD 

### ISSUE THREAD

**Issue by georgekeemo** [jilleb/mib2-toolbox#198]
Hello ,i am trying to patch a sd card for CD OFF but at the end i get “Backup failed. Patching is aborted” message.
The unit i am using is MST2 5Q0035874C ,0478 fw. 
Till now the toolbox  worked fine and i had the toolbox sd inserted in the unit. Any ides ? I attached a couple of screenshots. 
cheers
![B4034ED2-734F-4F9D-B785-71AED7473ED0](https://user-images.githubusercontent.com/98947697/152318204-92d5991b-d5e9-4aec-8c75-af298078d082.jpeg)
![Uploading 2C44F2D6-9797-4B93-849A-3FCB52A61BE8.jpeg…]()

**Comment by olli991** [comment]
Wrong GitHub Repo. You use MST and you're here on the MHI Toolbox. Please open up Issue there!

https://github.com/olli991/mib-std2-pq-zr-toolbox
