### ISSUE TITLE
New screen/script: Privacy

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#2]
Currently, the MIB2 saves a lot of privacy-sensitive data.
Add a new screen/script that can:

- remove phonebook/pictures of contacts/etc.
- remove history of GPS trips
- remove other sensitive data
- [DONE] change default console password
- [DONE] remove all logs
- [DONE] remove SWDL logs

**Comment by kentherzz** [comment]
Thank you very much for working with this, privacy is as important as anything else!

**Comment by jilleb** [comment]
It's done, Find it in the latest commit:
5d36c6a8bf348ce3b5371e29e1492f558c8dac38

**Comment by jilleb** [comment]
Added shadow file replacement in commit fe5922b834bdf115d6db7cb17dfdc0648cd4a43c
