### ISSUE TITLE
[BUG] Unable to restore Android Auto from backup after patch

### ISSUE THREAD

**Issue by fbuser1** [jilleb/mib2-toolbox#200]
**Describe the bug**
Unable to restore Android Auto from backup after patch

**To Reproduce**
1. Go to AndroidAuto -> make backup
2. Restart MIB
3. Checked that nothing happened, decided to restore
4. Go to AndroidAuto -> restore from backup

**Expected behavior**
No errors

**Error log**

```
...
This script will recover patched AA config files.
-------------------------------
FAZIT of this unit: JTH-07607.09
Firmware version: MH12_ER_VWG13_K4525
-------------------------------
Toolbox on SDA0 found
Mounting SD card writeable

Mounting system writeable

Source: Backup/MHI2_ER_VWG13_K4525/JTH-07607.09.1634010689/
/eso/hmi/engdefs/scripts/mqb/recovery_aapatch.sh: /eso/hmi/engdefs/scripts/mqb/util_recovery.sh[28]: syntax error: "else' unexpected
         AndroidAuto/gal.json
Destination: /net/mmx/etc/eso/production/gal.json
```

**Firmware(please complete the following information):**
 - Brand: VW
 - Hardware-type: MIB2High Harmann
 - Version: MHI2_ER_VWG13_K4525

**Additional context**
Even didn't touched SD card from slot. No backup file manipulated

**Comment by olli991** [comment]
I forgot an `fi` in that argument.. fuck

I just pushed a hotfix for it https://github.com/jilleb/mib2-toolbox/commit/f46df195b05ba8abc518610828b45819b5c940be

Please replace `util_recovery.sh` with newest one and update Toolbox

**Comment by fbuser1** [comment]
Thank you a lot! will try
