### ISSUE TITLE
[BUG] Unable to restore Android Auto from backup after patch (new)

### ISSUE THREAD

**Issue by fbuser1** [jilleb/mib2-toolbox#201]
**Describe the bug**
Unable to restore Android Auto from backup after patch (I'm using latest master)

**To Reproduce**
1. Go to AndroidAuto -> make backup
2. Restart MIB
3. Checked that nothing happened, decided to restore
4. Go to AndroidAuto -> restore from backup

**Expected behavior**
No errors

**Error log**
cp error
![image](https://user-images.githubusercontent.com/36403476/152583581-b98a9c26-cd79-4c81-ab44-ddbd41b75010.png)

**Firmware(please complete the following information):**
 - Brand: VW
 - Hardware-type: MIB2High Harmann
 - Version: MHI2_ER_VWG13_K4525

**Comment by fbuser1** [comment]
path from patch script: /et/mmx/mnt/system/etc/eso/production/gal.json

Recovery script tried to use that file path: /net/mmx/etc/eso/production/gal.json

**Comment by olli991** [comment]
Thanks for clearing this up and sorry for the late fix. Adjusted the paths in https://github.com/jilleb/mib2-toolbox/commit/80f9f4febcfdf3e915bcbd84c6af4ea465f9281c
