### ISSUE TITLE
[REQUEST] Traffic info without online services

### ISSUE THREAD

**Issue by camarao69** [jilleb/mib2-toolbox#203]
Hello, sorry if this has been asked , is it possible to make the traffic info come from google instead of vw.
In my country there is no tmc and i can´t enable online servicies because my mib is retrofitted , this is the only feature that really is important for every they use and i can´t enable it

https://developers.google.com/maps/documentation/javascript/examples/layer-traffic

Thank you

**Comment by MaTyyyJ** [comment]
its not possible without own audi connect server.

**Comment by olli991** [comment]
You could change TMC channels to maybe fit your country, look if there's something fitting in the wiki: https://github.com/jilleb/mib2-toolbox/wiki/TMC-channels-research

You will not get full online services obviously but maybe at least some traffic info.

**Comment by camarao69** [comment]
Hello , sorry for the late response, i had already tryed all tmc codes but none of them worked.

Thank you
________________________________
De: olli991 ***@***.***>
Enviado: 6 de agosto de 2022 19:16
Para: jilleb/mib2-toolbox ***@***.***>
Cc: camarao69 ***@***.***>; Author ***@***.***>
Assunto: Re: [jilleb/mib2-toolbox] [REQUEST] Traffic info without online services (Issue #203)


You could change TMC channels to maybe fit your country, look if there's something fitting in the wiki: https://github.com/jilleb/mib2-toolbox/wiki/TMC-channels-research

You will not get full online services obviously but maybe at least some traffic info.
