### ISSUE TITLE
[REQUEST] Firmware 1427 to 0343 back ?

### ISSUE THREAD

**Issue by NeNicYs7** [jilleb/mib2-toolbox#206]
Hi guys, I have the car B8 MIB2 was 0343 Firmware and I updated until 1427 but I don't like the same blue color, how do I do it and I want to return firmware 0343 if you can help me? do you have skin Multicolor RGB files please ...

**Comment by olli991** [comment]
I am not sure if its the some on MHI but on MST units you could do emergency and go back to stock firmware in that process because its only accepting that anyways.

On the other hand you could possible build yourself a fitting skin tho.

Otherwise porting back is not recommended
