### ISSUE TITLE
[BUG] Skin Fail

### ISSUE THREAD

**Issue by NeNicYs7** [jilleb/mib2-toolbox#207]
made the skin not correct image and how back that same image please
![SCREENSHOT_(Sdl_7DD2(Cmf))_TIME_2022_04_15_16_01_05_GEOCOORD_LAT_44 417_LONG_26 118_186367_Nr_39](https://user-images.githubusercontent.com/93197177/166503028-b3e50085-87b1-4dae-b178-d72df5176011.png)

**Comment by olli991** [comment]
If you used the toolbox correctly you could just use the restore script within the toolbox to go back to you old skin.

Without backup, only via custom SWDL and installing your firmware again

**Comment by NeNicYs7** [comment]
Hello, I will tell you how to change the skin MIB2
![SCREENSHOT_(Sdl_7DD2(Fd))_TIME_2022_03_31_17_29_37_GEOCOORD_LAT_44 417_LONG_26 118_622355_Nr_17](https://user-images.githubusercontent.com/93197177/217943410-5560f22c-46c6-4830-acc2-3dfa74d945c9.png)
![SCREENSHOT_(Sdl_7DD2(Fd))_TIME_2022_05_06_17_55_52_GEOCOORD_LAT_44 417_LONG_26 118_142677_Nr_78](https://user-images.githubusercontent.com/93197177/217943411-18f4e5be-5922-498a-aa5a-5713a1cd2ec9.png)
![SCREENSHOT_(Sdl_7DD2(Fd))_TIME_2022_05_06_18_51_55_GEOCOORD_LAT_44 417_LONG_26 118_118928_Nr_97](https://user-images.githubusercontent.com/93197177/217943413-b4db5b1b-c75e-4f4a-92c4-28c53855651d.png)
