### ISSUE TITLE
[BUG] Splashscreen dump doesn't work

### ISSUE THREAD

**Issue by SavouryMonkey** [jilleb/mib2-toolbox#210]
Hey! At first I'd like to thank you for all the hard work and effort! I appreciate you doing all that, and even for free! 

I wanted to change the Splashscreen on my car, but sadly it doesn't work. I can't dump it, and I can't apply one from the Wiki screens. I've attached a screenshot from my 5F and the error the toolbox gives me. I hope it helps a little. 

If I'm simply to dumb to use it, and this isn't a bug, then I'd love to get thrown into the right direction. 

Map dumping and Skins worked fine. 
![E37ACD3C-C842-4237-9AD8-205E4AAE9613](https://user-images.githubusercontent.com/41338731/174898021-a8ed4b5b-2cb8-4db4-9ab8-9a3110a68b94.jpeg)
![F0C854A1-06FE-4F83-9F3E-4CBEDB195EF2](https://user-images.githubusercontent.com/41338731/174898071-4cb85d2a-7c20-4046-b26c-78db112c5fff.png)

**Comment by olli991** [comment]
I made some changes in https://github.com/jilleb/mib2-toolbox/commit/ae1cd546156310d31e9b731daa2fb79937e75d20 which hopefully fix that behaviour

**Comment by SavouryMonkey** [comment]
> I made some changes in [ae1cd54](https://github.com/jilleb/mib2-toolbox/commit/ae1cd546156310d31e9b731daa2fb79937e75d20) which hopefully fix that behaviour

Awesome, fixed!
