### ISSUE TITLE
[BUG] Unable to apply AndroidAuto patch

### ISSUE THREAD

**Issue by therubiksman** [jilleb/mib2-toolbox#213]
**Describe the bug**
From the latest master, i can't patch android auto, each 'sed' command failed.

**Screenshots**
![20220719_201946](https://user-images.githubusercontent.com/109626024/179836360-3e5417d0-dbbd-408f-bae5-1b3f8feaaa58.jpg)

**Firmware(please complete the following information):**
 - Brand: VW
 - Hardware-type: MIB2High Harmann
 - Version: MHI2_ER_VWG13_P4521

**Comment by olli991** [comment]
Looks like the partition is not mounted read write whats aood because we haven't changed anything in that script for a long time

**Comment by Maras2003** [comment]
Same issue here, newest toolbox, but also newest firmware MHI2_ER_SEG11_P4709. Do You have any ideas why its stopped working?
![IMG_20230223_161924_3](https://user-images.githubusercontent.com/25158946/221582125-5caff05c-b2c5-404a-b2ca-1d468a50cfa9.jpg)

**Comment by therubiksman** [comment]
It seems to be an issue due to mount utility refactoring.
I fixed the bug in my own fork with this patch :
[fix_android_auto.patch](https://github.com/jilleb/mib2-toolbox/files/10840505/fix_android_auto.patch)

**Comment by Maras2003** [comment]
Unfortunatelly i cant apply patch, got some issues in GitKraken, but i assume its only changing lines 3-9 to this:
` export TOPIC=AndroidAuto
 export MIBPATH=/net/mmx/mnt/system/etc/eso/production/gal.json
 export MIBPATH2=/net/mmx/mnt/app/etc/eso/production/gal.json
 export ORIGINAL=/etc/eso/production/
 export FILENAME=gal.json
 export SDPATH=$TOPIC/$FILENAME
 export TYPE="file"`
 
 And similar thing to recovery_aapatch.sh ?
 The only change in fact is 
 Add line: export MIBPATH2=/net/mmx/mnt/app/etc/eso/production/gal.json
 Change patch in: ORIGINAL=/etc/eso/production/

**Comment by therubiksman** [comment]
Yes in file "patch_gal.sh" :
> add line "export MIBPATH2=/net/mmx/mnt/app/etc/eso/production/gal.json" just after "export MIBPATH=..."

And in file "recovery_aapatch.sh" :
> replace line "export MIBPATH=/net/mmx/etc/eso/production/gal.json" by the two lines :
export MIBPATH=/net/mmx/mnt/system/etc/eso/production/gal.json
export MIBPATH2=/net/mmx/mnt/app/etc/eso/production/gal.json

**Comment by Maras2003** [comment]
Finally works, thanks for help!
