### ISSUE TITLE
Missing testmode/green menu

### ISSUE THREAD

**Issue by adrianmihalko** [jilleb/mib2-toolbox#215]
Hi,

I carefully followed the installation guide and installation seem to be successful to me:

- Let the unit run the entire software update. It will reboot several times before showing a screen listing a lot of modules as N/A. The Toolbox line should be Y. You can then hit the back button in the top right corner.
- When it's done, it will ask you to connect a computer and clear the error codes. This is not needed, you can hit the "Cancel" button..
- The unit will restart one final time and you're back at the main car menu. Installation is now done.
- Hold the MENU button, and go to TESTMODE. On older versions you can go to the developer menu by holding the MENU button for about 10 seconds.

Everything was the same, except the last step. After holding the MENU button there is no TESTMODE:

![IMG_3010](https://user-images.githubusercontent.com/733361/183726268-9751a694-57ae-4fb6-933f-ec0c268fb098.jpg)
![IMG_3011](https://user-images.githubusercontent.com/733361/183726279-8cc43766-5736-4366-b51c-4ba54a1a9fe6.jpg)

**Comment by olli991** [comment]
Did you get OK at the end of the installation? If yes then maybe something on your unit is too old. You need to enable devmode via diagnostics then to see if it all worked.

**Comment by adrianmihalko** [comment]
> Did you get OK at the end of the installation? If yes then maybe something on your unit is too old.

Yes, I double checked after it was done.

I have access only to a cl. VCDS, it is possible to enable devmode with this? If so, can you point me how to do it?

**Comment by olli991** [comment]
yes, this could help: https://www.remkoweijnen.nl/blog/2016/05/17/enable-developer-mode-on-vw-discover-pro-with-vcds/
