### ISSUE TITLE
Unable to dump eeprom

### ISSUE THREAD

**Issue by vwjap** [jilleb/mib2-toolbox#217]
So dumped eprom and got a sed error, and at the end said unable to write 48 lines, broken pipe
When I open up the .bin on a hex editor all I get is a “.” In the file 
The txt file opens but either I’m reading it wrong or I really don’t understand what’s going on, as I look at address 0x000240 in Obdeleven eeprom reader (Vim as I have it set on C7 which is 199) but in the eeprom dump 0x240 it has 38 and doesn’t look like the speed settups 🤷‍♂️

im on toolbox 4.2a 
2017 golf 
Mhi2_er_vwg13_p4521 1367

**Comment by olli991** [comment]
maybe fixed with latest commit?

**Comment by olli991** [comment]
Dublicate to https://github.com/jilleb/mib2-toolbox/issues/212
