### ISSUE TITLE
[BUG] ? FAZIT is unknown

### ISSUE THREAD

**Issue by Calimerorulez** [jilleb/mib2-toolbox#218]
Hi,

I'm trying to dump the contents of my MIBH2 in my Seat Leon 5F. I'm getting the message that FAZIT is unknown. Can that be a problem?

Hardware H50
Partnimer 5F0035020D
Software 0897
SW Train MHI2_ER_SEG11_P3315

**Comment by olli991** [comment]
No not really... is it aftermarket or on the bench?

**Comment by Calimerorulez** [comment]
In the car built in from factory.

**Comment by olli991** [comment]
Thats an odd behaviour but it should not prevent you from using the toolbox and stuff.
