### ISSUE TITLE
Wireless CarPlay/Android Auto possible?

### ISSUE THREAD

**Issue by kentherzz** [jilleb/mib2-toolbox#22]
Hi Jille. As Discover Pro headunits (at least in Europe) has WiFi module it seems very much that it is only the software that is the limitation. Can you dig into if this could be activated? I know you do stuff for free and we appreciate it but I would really like to donate a good amount if you found a way... And I dont think Im the only one 👍

**Comment by kentherzz** [comment]
Do you by the way know if Android Auto/CarPlay is using the onboard GPS in the car or the phone GPS?

**Comment by peterbensch** [comment]
> Do you by the way know if Android Auto/CarPlay is using the onboard GPS in the car or the phone GPS?

Depends on the app you're using

**Comment by kentherzz** [comment]
Do you have details about Google Maps on iOS and Android? Both use GPS, no?

**Comment by peterbensch** [comment]
Google Maps use the car GPS yes

**Comment by andy0172** [comment]
In MHI2_US_AU57x_K3324_1 or MHI2_ER_AU57x_K3324_1 wireless Carplay and AA is implemented. i have this firmware available if needed.

**Comment by kentherzz** [comment]
@andy0172 So it is usable? have you tried it?

**Comment by andy0172** [comment]
Yes in a Audi its working, but the question is, how to get this functionallity into our VW software

**Comment by nicof38** [comment]
> In MHI2_US_AU57x_K3324_1 wireless Carplay and AA is implemented. I have this firmware available if needed.

Do you have access to ER variant of any 3xxx MHI2 firmware ?

**Comment by salihkurucan** [comment]
> In MHI2_US_AU57x_K3324_1 wireless Carplay and AA is implemented. I have this firmware available if needed.

is it possible for you to provide the firmware with aa wireless on audi a3 mib2?

**Comment by fsonmez** [comment]
> In MHI2_US_AU57x_K3324_1 wireless Carplay and AA is implemented. I have this firmware available if needed.

is it possible for you to provide the firmware with aa wireless on audi a3 mib2?

**Comment by AndrexOfficial** [comment]
> Yes, this topic has been on my mind for a loooooooong time. I've even used some binaries from Audi to try to enable it, but the problem is: missing user interface. There's no front-end for the wireless connection (yet), so I'm completely in the dark how to activate such a thing. But......... I have good hopes there's a way.
> 
> If anyone knows which firmware versions support wireless AA, I will investigate those for inspiration.

VW MIB3 SW 1560 EU has Wireless CarPlay and Android Auto with even the user-interface, this should work also on very latest MIB 2.5 units with SW 1367 or 1427.
Tell me if you need MIB3 firmware ;)

**Comment by csae6754** [comment]
Hi, 

do you have by any chance info how to activate Audi smartphone interface / Android Auto/ Car Play ?

**Comment by vwjap** [comment]
If you have a Audi with MH2p_ER_AUG35_P2470 or higher. then you can activate it with obdeleven/vcds

**Comment by veso266** [comment]
@AndrexOfficial I would love to get a firmware as well if its possible?
Where did you get it?

**Comment by Hamburgpriat** [comment]
> Hi,
> 
> do you have by any chance info how to activate Audi smartphone interface / Android Auto/ Car Play ?

No...
https://github.com/jilleb/mib2-toolbox/blob/master/FAQ.md#can-this-enable-android-auto--carplay

**Comment by arcangel321** [comment]
Any progress about this? It would be so perfect!!

**Comment by Hamburgpriat** [comment]
i think there need an Firmware of MIB3... to check the Code and  have to implemented in MIB2 Firmware...
Maybe in the future it is possible to upgrade MIB 2 to MIB 3... (i read there is an GPS Problem after update. But Hackers work on it...)

**Comment by AndrexOfficial** [comment]
> @AndrexOfficial I would love to get a firmware as well if its possible?
> Where did you get it?

Got it from original VW server for updates

**Comment by AndrexOfficial** [comment]
> i think there need an Firmware of MIB3... to check the Code and have to implemented in MIB2 Firmware...
> Maybe in the future it is possible to upgrade MIB 2 to MIB 3... (i read there is an GPS Problem after update. But Hackers work on it...)

Where did you read it?

**Comment by Hamburgpriat** [comment]
> > i think there need an Firmware of MIB3... to check the Code and have to implemented in MIB2 Firmware...
> > Maybe in the future it is possible to upgrade MIB 2 to MIB 3... (i read there is an GPS Problem after update. But Hackers work on it...)
> 
> Where did you read it?

Oh sorry. He change the hole Columbus... But have problem with the GPS after replace...

in german:
https://www.jestex.de/tag/mib-3/

**Comment by jilleb** [comment]
Please stay on topic or else I will have to clean this topic and remove most replies...

**Comment by Aintejo** [comment]
Hi, 

Some light, hope this may help : 

**Discover Pro 2017** ==> Supports App-Connect (No wireless)
https://webspecial.volkswagen.de/vwinfotainment/ch/fr/index/infotainment-systeme#/?detail=a7208a1f-88e4-4be9-b8c4-5cb805deaa59
Available on this cars : 
- Golf/Variant/Sportsvan/GTI/GTD/R/GTE/e-Golf from MY2017
- Passat from MY2017
- Tiguan from MY2017
- Tiguan Allspace up to MY2019
- Arteon up to MY2019

**Discover Pro 2019** ==> Supports App-Connect (No wireless)
https://webspecial.volkswagen.de/vwinfotainment/ch/fr/index/infotainment-systeme#/?detail=3583374f-d3ca-4260-a078-3a363d11b06a
Available on this cars : 
- Tiguan from MY2019
- T-ROC from MY2019
- T-Cross
- Touran and Golf Sportsvan from 2019

**Discover Pro 2019** ==> Supports appConnectWireless
https://webspecial.volkswagen.de/vwinfotainment/ch/fr/index/infotainment-systeme#/?detail=a7208a1f-88e4-4be9-b8c4-5cb805deaa59
Available on this cars : 
- Passat from MY2019
- Arteon from MY2019

The screen is the same in the 3 cases, and the skin of menu as well. If VW information is not wrong and Passat/Arteon from 2019 really support App-Connect Wireless, do you think it would be the "easiest" way to do it ?

**Comment by jilleb** [comment]
The 2019 Passat/Arteon Discover Pro's are identical to the ones in Tiguan and Golf... Wireless App-connect is not supported. Audi is currently the only one that has an MIB2 firmware that supports wireless app-connect, but I haven't been able to get it working on other units.

**Comment by BobHackett2** [comment]
Is this something that can be activated in my 2018 S4?

**Comment by mathieuedet** [comment]
I think it's not possible on these vehicules. Android auto requires wifi 5ghz and it's only 2.4ghz on these cars.

**Comment by brianyou0524** [comment]
As I know , there's 3rd party device to implement wireless Apple Carplay.
However, Andorid Auto doesn't have this device. and after studying Wireless AA.
It's using WIFI Direct to implement what we need.  WIFI Direct is one of the WIFI function . 
MIB2 discovery pro2 doesn't  WIFI Direct . It should be upgraded by WIFI module firmware

**Comment by mathieuedet** [comment]
@brianyou0524 Honestly, I have some doubts about an update from VW for this module but it could be really nice ;)

**Comment by spikked27** [comment]
This would be killer to get, so frustrating having a wireless charging pad but still have to plug the phone in to use Android auto 😠

**Comment by OneB1t** [comment]
Hello any progress about this? 

> > Yes, this topic has been on my mind for a loooooooong time. I've even used some binaries from Audi to try to enable it, but the problem is: missing user interface. There's no front-end for the wireless connection (yet), so I'm completely in the dark how to activate such a thing. But......... I have good hopes there's a way.
> > If anyone knows which firmware versions support wireless AA, I will investigate those for inspiration.
> 
> VW MIB3 SW 1560 EU has Wireless CarPlay and Android Auto with even the user-interface, this should work also on very latest MIB 2.5 units with SW 1367 or 1427.
> Tell me if you need MIB3 firmware ;)

Is it possible to obtain that MIB3 firmwar? i have MIB.2.5 unit SW1367 (unit is actually AUDI unit flashed with VW firmware)

**Comment by AndrexOfficial** [comment]
@OneB1t  Yes I have MIB3 firmware but I think it is not compatible with MIB 2.5

**Comment by veso266** [comment]
Well, even if its not compatible, if you could share it anyway, that would be great

**Comment by veso266** [comment]
> @OneB1t Yes I have MIB3 firmware but I think it is not compatible with MIB 2.5

Well, even if its not compatible, if you could share it anyway, that would be great

**Comment by Omario79** [comment]
If you have wifi in your System you can activate it with obdeleven 
I did it

**Comment by andrewleech** [comment]
> If you have wifi in your System you can activate it with obdeleven I did it

Was this on an Audi / mmi system? Certain Audi models support it this way but there's no publicly known way to do this via coding on other brand mib2 / mib2.5 systems.

**Comment by ferpraes** [comment]
Any new about this topic?

**Comment by qba667** [comment]
@andrewleech  
I just looked over script and assemblies of mentioned by @andy0172  MHI2_US_AU57x_K3324_1, can not find any socket related operations beside Exlap in GAL assembly. Maybe it is not part of the GAL.
The WiFi link over 2.4 GHz seems to be sufficient to handle h264 media streaming.

**Comment by LuboszLB** [comment]
> I have Touran 2019 with Discover Pro - HW H55/SW 1367 and look for last update. THX

**Comment by jfalmeida** [comment]
> > Yes, this topic has been on my mind for a loooooooong time. I've even used some binaries from Audi to try to enable it, but the problem is: missing user interface. There's no front-end for the wireless connection (yet), so I'm completely in the dark how to activate such a thing. But......... I have good hopes there's a way.
> > If anyone knows which firmware versions support wireless AA, I will investigate those for inspiration.
> 
> VW MIB3 SW 1560 EU has Wireless CarPlay and Android Auto with even the user-interface, this should work also on very latest MIB 2.5 units with SW 1367 or 1427. Tell me if you need MIB3 firmware ;)

Hey @AndrexOfficial , I've got 1560 on a MIB3, Carplay wifi works but android auto doesn't. Do you have any firmware update for MOI3? like 2700, 2760 or even earlier version?

**Comment by qba667** [comment]
Comparing libs of GAL between my Skoda and Audi:
Audi:
 0x00000001 (NEEDED)                     Shared library: [libirc_mmx_adapter.so]
 0x00000001 (NEEDED)                     Shared library: [libpps.so.1]
 0x00000001 (NEEDED)                     Shared library: [libaoa-lite.so.1]
 0x00000001 (NEEDED)                     Shared library: [libautoreceiver_qnx.so.1]
 0x00000001 (NEEDED)                     Shared library: [libprotobuf-lite.so.1]
 Skoda:

 0x00000001 (NEEDED)                     Shared library: [libservmngt.so]
 0x00000001 (NEEDED)                     Shared library: [libusbdi.so.2]
 0x00000001 (NEEDED)                     Shared library: [libautoreceiver.so]
 0x00000001 (NEEDED)                     Shared library: [libprotobuf-lite.so]

**Comment by isopix** [comment]
I've got Arteon 1.5 TSI 2018 with MST2 (MIB2 Standard: Composition Media, Discover Media)

```
Device part number:
3Q0035846B

Hardware:
851

Navigation Database:
3G0919866BJ
0915
ECE1 2018
2300

App-Connect:
755

Radio database version:
Version 1.9.4

USB surfstick version:
1.0.0

Installed SW Train Version:
MST2_EU_VW_P0883D

Installed SW MU Version:
0883
# was 0867

Part number:
3Q0035846B

Software Version:
H29.319.120_STD2Nav_EU
# was H29.319.28.3_STD2Nav_EU


HMI Software:
H29.319.120_STD2Nav_EU

Model:
GuideModel_29.319.32

Software Base:
H29.319.120-202003251528

CGRun Number:
H29.319.120-202003251531_STD2Nav_EU_202003...

```


All is upgraded to latest version(will paste results later), but it's probably 879.

Android Auto works over USB cable. (I've unlocked everything in car, so there's AppleCar, Android Auto and Mirror Link)

I'm able to connect both car to phone's WiFi(it tries to get to internet that way) and phone to car's hotspot.
So connecting works both ways. If I remember good, the same goes for bluetooth(but less sure about that).

Anyway I don't know how to connect Android Auto wireless. From previous replies it sounds it impossible.
Option to add cars and wireless in disappearing randomly in Android auto settings (Xiaomi 14 Ultra, Global version)





Should I buy adapter (like Motorola MA1/AA Wireless, it will take USB ports and space in cockpit) or is there any hope I can enable it by replacing files from Audi?

(I'm pretty technical person, advanced CLI linux user, and I've unlocked everything by OBD2/Car Scanner , file patching and certificate generation)

**Comment by Korni22** [comment]
If you look at one of the earlier comments, Jille states that this may or may not be possible, but even if you swap the necessary files, you're still lacking the user interface to set things up:
https://github.com/jilleb/mib2-toolbox/issues/22#issuecomment-549902197

While I'm not entirely sure, I think this is pretty much a dead end, the MIB3 retrofits are getting easier by the minute, especially if you don't have Dynaudio (or the version for your specific model)

**Comment by OneB1t** [comment]
replace gal binary from audi and maybe it will be possible to have working wireless android auto
that is where it makes sense to start experimenting

**Comment by veso266** [comment]
I dont think retrofitting MIB3 is souch a good idea at this time

GEM is FEC protected there and there is no toolbox for it yet

**Comment by andrewleech** [comment]
Well in quite happy with my AAWireless dongle on mib2, apparently they're also adding carplay support to the same dongle too so the one unit should work with both.

**Comment by twistedpixel** [comment]
> Well I'm quite happy with my AAWireless dongle on mib2, apparently they're also adding carplay support to the same dongle too so the one unit should work with both.

Which dongle do you use? I have considered CarLinkit 5 but the reviews are either “it’s great” or “it’s great but disconnects all the time.” My Lightning port is dodgy enough so if I want something that disconnects all the time I’ll just keep using the cable!

**Comment by andrewleech** [comment]
It's called [AAWireless](https://www.aawireless.io/).

Yeah sometimes it disconnects, but usually that means the cable it's connected with isn't quite good enough. I've never found a lightning cable for my partner's phone that lasts longer than a few months in the car really.

**Comment by twistedpixel** [comment]
> It's called [AAWireless](https://www.aawireless.io/).
> 
> Yeah sometimes it disconnects, but usually that means the cable it's connected with isn't quite good enough. I've never found a lightning cable for my partner's phone that lasts longer than a few months in the car really.
> 
> Also, from a quick Google search built-in wireless Android Auto / carplay disconnects pretty often for some people too...

The product you have seems way better than the CarLinkit thing. Reviews are unanimously positive and they have a blog post outlining that version 2 is due to be released soon. There is currently a CarPlay beta and apparently it’s very good. I think I’ll wait for version 2 but it looks very promising - thanks for mentioning it.

**Comment by pepsonEL** [comment]
Hi. I have Skoda Kodiaq 2019 with MIB 2,5 9,2" and also Android Auto Wireless no working. I have FW 1440.

**Comment by candasm** [comment]
> Hi. I have Skoda Kodiaq 2019 with MIB 2,5 9,2" and also Android Auto Wireless no working. I have FW 1440.

As I understand after a long time car play requires 5G connection. But our cars has only 2.5G thats why there is no wireless connection.

**Comment by pepsonEL** [comment]
But MIB 2,5 has only 2,4 GHz ? Dont have 5GHz ?
