### ISSUE TITLE
أريدو أن أستخدم App connte في سيارت كولف كادي

### ISSUE THREAD

**Issue by Farihsmail** [jilleb/mib2-toolbox#223]
**Describe the bug**

**To Reproduce**
2. Do '....'
3. I get error '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or pictures to help explain your problem.

**Firmware(please complete the following information):**
 - Brand: [e.g. VW]
 - Hardware-type [e.g. MIB2High]
 - Version [e.g. 1367]

**App Additional context**

**Comment by nirvananils** [comment]
Then you have to activate. But without Information nobody can help
