### ISSUE TITLE
Does MIB2 work on MH2p_ER_POG35_P2550?

### ISSUE THREAD

**Issue by mtrencseni** [jilleb/mib2-toolbox#228]
Hi, I have a 2019 Porsche Cayenne, this is the one with the wide "modern" Porsche touchscreen. When I go into the engineering menu with the magic key combo and check the PCM firmware version, it's MH2p_ER_POG35_P2550? Can I use MIB2 on this type of PCM? Thank you.

**Comment by jilleb** [comment]
Unfortunately not.
