### ISSUE TITLE
Add manual install option to readme and green menu

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#23]
Hi guys! I'm another one who got metainfo read error on VW MIB2.5 v1367 (bootloader 210, application 8863)
@jilleb is it possible to add script files manually?
Mount sdcard and cp all of it to mib filesystem?

Thank you!

_Originally posted by @darkmag666 in https://github.com/jilleb/mib2-toolbox/issues/1#issuecomment-552220581_

**Comment by jilleb** [comment]
Yes it's possible. Just copy payload.sh to mqbcoding.esd in the eso/hmi/engdefs folder. I'll add it to the readme.


> @jilleb Maybe it would be a good idea to add also "Toolbox update" as another option - for units which the payload trick doesn't work it's necessary to install the toolbox using console. Each time there's a new toolbox, the unit has to be updated by computer. If there would be an "update_toolbox.sh" script, it could copy the new mqbcoding.esd file from sd card to the correspoding location :-)

**Comment by darkmag666** [comment]
@jilleb I have copied payload.sh manually today and everything works good.
Scripts also works perfectly.

**Comment by hxigor** [comment]
@jilleb I know it's possible to do that manually. But what I wanted to suggest for improvement is a kind of "update" also for the esd file, like this:

script
   value    sys 1 0x0100 "/scripts/copy_phone_customer_plus_mbqencoding.esd.sh"
   label    "Get new scripts and files from SD-card (slot1) & update MQBCoding.esd file"

When the Toolbox gets a new version, it would be nice if we could update it without connecting the unit to the computer. This would be very handy for all of us whose units give metainfo error.

**Comment by jilleb** [comment]
yes :-) working on that.

But...It's already possible to install new green menu screens from the mqbcoding.esd and it can also replace mqbcoding.esd.

**Comment by Romijn** [comment]
So can any of you share how to manually copy it? I have the same issue with a 2.5.

**Comment by jilleb** [comment]
Copy payload.sh to eso/hmi/engdefs/mqbcoding.esd

That should be enough.
After copying there will be a new green menu screen. That's all


I'll update the readme in the upcoming days.

**Comment by Romijn** [comment]
Is there a way we can have a short chat? I'm Dutch as well so we can be done quick :)

**Comment by jilleb** [comment]
Haha ok, Facebook me op Jille Berends

**Comment by andy0172** [comment]
When I try to copy it from shell I got this error, that the file system is read only:
cp /net/mmx/fs/sda0/PersonalPOI/PayLoad/0/default/payload.sh /net/mmx/mnt/app/eso/hmi/engdefs/mqbcoding.esd
cp: Can't open destination file.  (/net/mmx/mnt/app/eso/hmi/engdefs/mqbcoding.esd): Read-only file system

**Comment by jilleb** [comment]
You need to mount the volume as writeable. Not to be disrespectful, but maybe you should not mess around with the console if you don't know how to mount the volume as writeable.

**Comment by andy0172** [comment]
Strange I did this before, but always brought an error. I will let you know when it works. Thanks

**Comment by ymphua** [comment]
@jilleb managed to install this using the manual method. Great work! Just some info to add to your stats - my car is the Audi A4 B9 firmware 1329

**Comment by turboblade** [comment]
> @jilleb managed to install this using the manual method. Great work! Just some info to add to your stats - my car is the Audi A4 B9 firmware 1329

ymphua, did you connect to the car via telnet? If so, what interface did you use? Thanks

**Comment by ymphua** [comment]
> > @jilleb managed to install this using the manual method. Great work! Just some info to add to your stats - my car is the Audi A4 B9 firmware 1329
> 
> ymphua, did you connect to the car via telnet? If so, what interface did you use? Thanks

Yea I managed to telnet to the car, using the dlink USB Ethernet adapter dub-e100

**Comment by rob2e** [comment]
hello ymphua
you attached a dlink USB dub-e100 to your MIB
Is a special HW Rev. of this USB Ethernet Adapter needed ??? The newest Rev. I see on net is Rev. D ...
Does it work?
The readme of the project states, that the whole SW only works with MIB2 High or MIB2.5 High.
What does High mean?
I have a Media Composition MIB2.5 device (Golf 7  2017). 
device: 3Q0035842C
hardware 722
SW: 0876
Is it covered by this project?
Does anybody know?

**Comment by hxigor** [comment]
@rob2e Nope, Media Composition is MIB Standard and therefore this Toolbox won't work there. MIB 2 High is for example Discover Pro at VW, or Columbus at Skoda.
