### ISSUE TITLE
[REQUEST] enable dual navigation function in MHI2 Harman

### ISSUE THREAD

**Issue by Leor2208** [jilleb/mib2-toolbox#231]
Hi!
Thanks for your work, the system is awesome!
I was testing -enable dual navigation - option into my mhi2-harman from my audi a4 b9 and with this version MHI2Q_ER_AUG22_P5092_MU1329 and with the lastest M.I.B. Version and green menu sais that i cannot activate enable dual navigation into my system. It could be possible?
Best regards
Leo

**Comment by Sergiotero10** [comment]
Yo estoy en la misma situación, habría alguna manera de habilitarlo?

**Comment by Draekhar** [comment]
Same for me, im searching the way to enable it if its possible :)

**Comment by cimbru1** [comment]
Also interested. Let's get @Errivincenz an iPhone. He might be our best bet :) #189 

https://github.com/jilleb/mib2-toolbox/pull/189#issuecomment-1376487793
