### ISSUE TITLE
[ HELP ] - VW Golf 7

### ISSUE THREAD

**Issue by socialvodsud** [jilleb/mib2-toolbox#236]
Hello,
Yesterday my Golf 7 (late 2015) popped up saying that car play, bluetooth etc was not working and that I needed to enter an activation code.

Current software version MHI2_ER_VWG11_S2103

Will this project work for me to achieve unlocking of all services?

Alternatively, what tool should I use?

Thank you all very much. I will then support the project financially if necessary.

Thank you
Robert

**Comment by Cuzoe** [comment]
What you are asking for is not part of this project...
https://github.com/jilleb/mib2-toolbox/blob/master/FAQ.md
