### ISSUE TITLE
discover pro

### ISSUE THREAD

**Issue by skamyra** [jilleb/mib2-toolbox#237]
foto-      
https://user-images.githubusercontent.com/127048515/222980694-048c657a-18c6-4fb6-a777-17ac1c630b13.jpg
https://user-images.githubusercontent.com/127048515/222980755-906419f5-136e-4b44-a626-80c3d3f44e56.jpg
https://user-images.githubusercontent.com/127048515/222980562-0130dc1a-c1d7-48cc-9d77-bf57612f40bb.jpg
HiI should eliminate firmware conflict, could you help me.
Thank you

**Comment by jilleb** [comment]
Can you clarify the question?

**Comment by skamyra** [comment]
I would like to delete the firmware installed as can be seen from photo because it gives me error updates every start of the radio.

**Comment by skamyra** [comment]
sorry if I'm unclear

**Comment by lito69** [comment]
I don't know if you should do swdownload cleaning or you still need to flash emergency, the error is that the integrity of the files is not correct, files are missing within that mib
