### ISSUE TITLE
Convert python tools to Python 3

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#24]
See topic

**Comment by jilleb** [comment]
Extracting tools are working on Py3 now,

**Comment by ShifengHuGit** [comment]
but Compress not working yet， and seems there is a dead loop if you are using 64-bit OS，Compress tool wants to use PIL module which only being supported at 32Bit 。。。 How can I solve this on Python2.7 for a 64Bit OS

**Comment by jilleb** [comment]
No problems with python 2.7 on my win10 64...

**Comment by Wetgod** [comment]
Registered here after messing 1 hour with the .py files.
Compress-mcf is not working with python 3 and python 2.7 generates a lot of "missing PIL modul" errors..

Can you check the .py files for newest python version under Windows 10 ?

**Comment by jilleb** [comment]
If you get missing module errors, you need to install the missing modules... 
On the latest windows 10, with the latest python 2.7, it's working. I'm currently too busy to port all the scripts to python 3.

**Comment by jilleb** [comment]
I'm currently porting the scripts to Python 3. But please read the error messages when it says there;s a module missing. These tools use external packages/modules, that you can install by using pip. It's even in the error message. 😉 
I removed some module dependencies, which will also help.

**Comment by olli991** [comment]
If you rewirte the scripts @jilleb can you also look into https://github.com/jilleb/mib2-toolbox/issues/60 ? we could maybe clean this two issues in one :-)

**Comment by jilleb** [comment]
Yes, i will make sure it has the correct png mode handling in the canim tools as well. And no more seperate vw and seat script.
