### ISSUE TITLE
Got a screenrenderer error.

### ISSUE THREAD

**Issue by NZSloanie** [jilleb/mib2-toolbox#248]
Went to do a dump and got this
![356189784_6439144136147376_394875805122705335_n](https://github.com/jilleb/mib2-toolbox/assets/57697707/bf63f5fb-3592-49d2-b76b-eb493899521a)
Initially the screen was blank so I rebooted the Media device then got the above

**Comment by jilleb** [comment]
You probably had an other script still running.

**Comment by Micun99** [comment]
![IMG_6285](https://github.com/user-attachments/assets/7e768e00-9c29-4d4f-b236-e8a7b2781808)
Hi, i have the same error.
How can I fix it?
Thanks!

**Comment by TomasTomko** [comment]
I have same issue and this is only script im running

**Comment by tapibolla** [comment]
i have also the same problem how to fix it?

**Comment by TomasTomko** [comment]
U need to do this step:


IMPORTANT! If your firmware is version 01xx or 02xx having GEM (Green Engineering Menu) version 3.x, you must use special edition of Toolbox to update it. To do this, replace cpu folder in the root of the SD card with cpu folder from \toolbox\gem folder. If GEM is version 4.x+, skip this step.

Check top left corner for your version in GEM X.X... as soon as I replaced this file it was working
