### ISSUE TITLE
Signature of metainfo2 is not correct

### ISSUE THREAD

**Issue by tt8824** [jilleb/mib2-toolbox#25]
Hi, I tried the toolbox with my audi harman MIB2 High Firmware 0875, and when i choose the SD-Card at the update menu, i get the error: "the signature of metainfo2.txt is not correct"
Is there something i can do? Thank you!

**Comment by jilleb** [comment]
That's interesting, because the metainfo has no sigmature :-) I'll look into this, but it seems this specific firmware is not accepting any metainfo without signature.

**Comment by jingod** [comment]
tt8824a I think you have the same problem here is the picture I have MIB1 VW I install firmware 0388 it give me this problem neither SD card nor Map nothing that works

**Comment by tt8824** [comment]
Hello again, do you have an idea, if there is a way for me to solve the problem? 
Thank you very much!

**Comment by jilleb** [comment]
Currently, not yet. It's probable the you have a firmware version that fixed this issue.

**Comment by MacNee** [comment]
i've hacked Audi MMI2 high running version 1168 and i dont even get
metainfo2 error, just No valid update data found on this medium so im
guessing this approach is totally shut.

**Comment by matix131991** [comment]
MHI2 ER AUG22 S2116 MU333 unit display metainfo2 is not correct. Someone have some idea ?

**Comment by andrei-cimpan** [comment]
@jilleb hi! any updates on this? I also got the error on an Audi TT. I had to update the firmware to MHI2_ER_AU43x_P5098, MU software 1339 to have the CarPlay compatibility

**Comment by jilleb** [comment]
No updates. It's nearly impossible for me to troubleshoot this when I cannot reproduce the error on my own devices.

**Comment by andrei-cimpan** [comment]
OK. Thanks

**Comment by umiterkol** [comment]
hello. I try it that code, but not read metainfo.txt. Maybe my FW very old.  
My Mib2 FW 0814. How can update newer version? Thanks

**Comment by jilleb** [comment]
I cannot reproduce the issue and therefore cannot fix it.

About updating:
Get new firmware
Install it by holding Menu button and go to update.

**Comment by Over690** [comment]
Hello, I have problem with instalation new version and when I want to update i get the error: "the signature of metainfo2.txt is not correct". Anyone can help?
