### ISSUE TITLE
My GEM seems to be an older version

### ISSUE THREAD

**Issue by NZSloanie** [jilleb/mib2-toolbox#251]
I installed the tool box just recently in late June but just noticed that I seem to be running an old version
![364539589_243766331887698_5642764855272134287_n](https://github.com/jilleb/mib2-toolbox/assets/57697707/e632cf63-1472-4c75-81ce-d650597cf70d)

How do I update it?

**Comment by jilleb** [comment]
You mean the version 3.6 in the upper left corner?
That's your green menu version, not the toolbox itself ;-)
