### ISSUE TITLE
Metainfo error 1433 skoda

### ISSUE THREAD

**Issue by Fallen230** [jilleb/mib2-toolbox#26]
Hello,

Thank you for your awesome job with the toolkit!

Unfortunately it dosnet work for my skoda. My firmware is 1433 and no matter what I do, if I use USB stick or a SD card (16 and 32 GB) in slot 1 or 2, if the  master the or toolbox v2 it will show me constantly metafile2.txt error :/ hope I will be able to flash soon too :)

**Comment by jingod** [comment]
I try several times its not running with the map sd neither firmware nor update Map the problem I think it is missing (metainfo2.txt) in the MIB
![IMG-20191124-WA0003](https://user-images.githubusercontent.com/42876315/69883850-48afbf00-12d6-11ea-9465-46f0cfd46b3b.jpeg)

**Comment by jilleb** [comment]
Yes, this issue is known, see #1
