### ISSUE TITLE
[SOLICITUD] it doesn't allow me to install

### ISSUE THREAD

**Issue by Quiquedx** [jilleb/mib2-toolbox#261]
Hello, it won't let me install, when I enter update it opens the MSTD2 ONLINE APPROVAL folder and I can see all the files but the start button remains gray and does not allow me to update.

My stereo data is:

MST2_EU_VW_PQ_P0351T

0351

5K7035200F

SOFTWARE VERSION:
H28.28.76_STD2PLUSPQ_EU

**Comment by jilleb** [comment]
This is an MIB2 STD, which kant supported by this toolbox.

**Comment by Quiquedx** [comment]
Don't they have the option to remove component protection?

**Comment by jilleb** [comment]
Maybe, but it's not supported by this toolbox.
