### ISSUE TITLE
MIB2 toolbox - not starting, can't update

### ISSUE THREAD

**Issue by Oren0007** [jilleb/mib2-toolbox#262]
After download the toolbox 1.3.3v it can't be started.
see in the pic: 

![WhatsApp Image 2024-02-14 at 19 01 24_9d250f2a](https://github.com/jilleb/mib2-toolbox/assets/160055325/451a2986-4185-4d24-a313-46e34fae3692)

![WhatsApp Image 2024-02-14 at 19 57 20_2554c659](https://github.com/jilleb/mib2-toolbox/assets/160055325/ea431425-7964-42a3-a5cb-d5a15b5841e7)

 - Brand: VW
 - Hardware-type MIB STD
 - Version 0475 
 -

**Comment by jilleb** [comment]
This repository is not meant for MIB Standard.
