### ISSUE TITLE
How I activate the toolbox?

### ISSUE THREAD

**Issue by Oren0007** [jilleb/mib2-toolbox#263]
I can’t find the link to activate toolbox for my car 
VW caddy 2019 
![4CC5EFB0-36A7-4F0C-82E9-1359B36B5420](https://github.com/jilleb/mib2-toolbox/assets/160055325/55e7db50-b61b-42fc-ad45-33d1be12c0d2)
![IMG_2393](https://github.com/jilleb/mib2-toolbox/assets/160055325/74a1451e-622c-40c7-b0ba-f0ad7d286659)
![IMG_2394](https://github.com/jilleb/mib2-toolbox/assets/160055325/cdd52272-1681-427a-b495-38d1713e6e17)

Thank you! :)

**Comment by jilleb** [comment]
MIB2 Standard is not supported by this toolbox. Please read the readme ;-)
