### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kalzter** [jilleb/mib2-toolbox#264]
**Describe the bug**
When running Patch script from Tools menu - Unknown Source Error

**To Reproduce**
1. Go to mibstd2_toobox/tools
2. Do (run) Patch tsd.mibstd2.system.swap and generate EL
3. I get Thread has started then at java.lang.Thread.start(Unknown Source)

**Expected behavior**
Patch should run and confirm success

**Screenshots**

![image](https://github.com/jilleb/mib2-toolbox/assets/24211193/cb2e0142-698f-4164-997a-9125556a4583)
![image](https://github.com/jilleb/mib2-toolbox/assets/24211193/eaff660c-c0b8-4efd-9d7c-2c8f86104390)
![image](https://github.com/jilleb/mib2-toolbox/assets/24211193/15dd3603-5e1e-4230-b8e3-4aafe8c61373)
![image](https://github.com/jilleb/mib2-toolbox/assets/24211193/1407b58c-db58-4211-8f4b-3a817cfe4f26)

**Firmware(please complete the following information):**
 - Brand: [e.g. VW]
 - Hardware-type [e.g. MIB2High]
 - Version [e.g. 1367]

**Additional context**

**Comment by olli991** [comment]
You're in the wrong repo. This is for MHI... you have an MST... and to speed things up... you have Gem3.5. need update. Read the Readme

**Comment by kalzter** [comment]
Please could you send me the link to the correct repo
