### ISSUE TITLE
[REQUEST] Is there a way to update the virtual cockpit car skins

### ISSUE THREAD

**Issue by wookie666** [jilleb/mib2-toolbox#266]
I have updated the vehicles in my skins on the MIB2 unit fine. However, the virtual cockpit still uses the old skins. Is there a way to update the look of those skins too?

For instance. I have modified one of the images for the MIB2 skins to this, id like the same on the virtual cockpit if possible.
![image](https://github.com/jilleb/mib2-toolbox/assets/17226236/bd159944-e486-4dd5-b12b-4b17f69851fd)

**Comment by jilleb** [comment]
Not yet!
