### ISSUE TITLE
MIB 1 VW problème pible a script to put on SD card to activate the green menu of MIB1 VW because my MIB1 and block on Metainfo2.txt

### ISSUE THREAD

**Issue by jingod** [jilleb/mib2-toolbox#27]
pible a script to put on SD card to activate the green menu of MIB1 VW because my MIB1 and block on Metainfo2.txt
![IMG-20191124-WA0003](https://user-images.githubusercontent.com/42876315/69885758-fc1cb180-12de-11ea-9d69-aa5fc214617d.jpeg)
![IMG-20191123-WA0060](https://user-images.githubusercontent.com/42876315/69885759-fcb54800-12de-11ea-946f-07cb3cb1ca3e.jpeg)
![IMG-20191123-WA0065](https://user-images.githubusercontent.com/42876315/69885760-fcb54800-12de-11ea-898d-8a5faa94037b.jpeg)
![IMG_20191123_232753](https://user-images.githubusercontent.com/42876315/69885761-fd4dde80-12de-11ea-9f12-deb2af96ad25.jpg)
![IMG_20191123_232836](https://user-images.githubusercontent.com/42876315/69885762-fd4dde80-12de-11ea-918a-11e1dac8e0d8.jpg)

**Comment by jilleb** [comment]
Can you please speak in English and describe the message on screen in English? Thanks!
