### ISSUE TITLE
[BUG]  unable to read SD 

### ISSUE THREAD

**Issue by Eltoddy03** [jilleb/mib2-toolbox#277]
Downloaded the newest software of MIB2 but enable to read SD card when updating, not sure if I’ve done something completely wrong 

installed SW train version 
MST2_EU_VW_PQ_PO245T

SW MU Version
0245

part number 
5C0035680C

SW version
H25.14.78_STD2NAVPQ_EU

**Comment by olli991** [comment]
Wrong toolbox. this is for MHI, you have MST ;-) 
go here: https://github.com/olli991/mib-std2-pq-zr-toolbox

**Comment by mkami77** [comment]
Downloaded the newest software of MIB2 but enable to read SD card when updating, not sure if I’ve done something completely wrong

installed SW train version
MST2_EU_VW_PQ_PO245T

SW MU Version
0245

part number
5K70_EU_VW_PQ_P2045T

SW version
H25.14.78_STD2plusPQPQ_EU

**Comment by olli991** [comment]
Did you even read the messegaes in this thread?

**Comment by Eltoddy03** [comment]
Hello hello Yes I managed to sort it all out had to swap the cpu file from the toolbox 👍👍On 11 Aug 2024, at 00:36, Olli ***@***.***> wrote:﻿
Did you even read the messegaes in this thread?

**Comment by mkami77** [comment]
Hi,  Thanks for your reply. 
My car is VW sharan. Mib not have navi button and only one sd slot.
