### ISSUE TITLE
Android Auto 

### ISSUE THREAD

**Issue by Fallen230** [jilleb/mib2-toolbox#28]
Is there an chance you could explain how the third party apps on Android auto works? I did run the patch neither can I add custom apps nor do I find anything in the gal.json to activate anything. Maybe add something to the Readme?

Thank you in advance

**Comment by jilleb** [comment]
The latest version I released has an updated description in the menu. You only need to run the script and it will patch gal.json automatically, but only if you have an SD in the slot. This is needed for creating a backup.

Can you try with the latest version?

**Comment by Fallen230** [comment]
I am running the new 1.6b.
I installed the aa patch. 
If I connect my phone aa looks like usual.
No extra menu 
In the green menu there is only patch or recovery after patch it tells me did the backup etc 

What menu do you mean?

Maybe I am just overseeing something

**Comment by jilleb** [comment]
there's an Android Auto screen and it allows you to patch gal.json. After it's done you need to reset the Android Auto connection (unplug replug phone) and it works.
