### ISSUE TITLE
Does MIB2 work on Mh2p_us_pog35_p2834?

### ISSUE THREAD

**Issue by bits-orio** [jilleb/mib2-toolbox#280]
I have a 2021 Porsche Panamera and the version on it is `Mh2p_us_pog35_p2834`. Will this tool work with my car's unit?

**Comment by ANMOSIN** [comment]
What do you want?

**Comment by bits-orio** [comment]
My objective is to enable support for Android Auto (wired).

**Comment by jilleb** [comment]
No, this is just for MIB2High
