### ISSUE TITLE
Metainfo Error on "Hacked" VW 1161

### ISSUE THREAD

**Issue by tehfalcon-vw** [jilleb/mib2-toolbox#29]
Is there anyway to flash this on a "hacked" (component protection removed, etc) MIB2 Discover Pro unit with 1161 software?

**Comment by hxigor** [comment]
Yes, look here https://github.com/jilleb/mib2-toolbox/issues/23#issuecomment-552420612

**Comment by tehfalcon-vw** [comment]
> Yes, look here [#23 (comment)](https://github.com/jilleb/mib2-toolbox/issues/23#issuecomment-552420612)

Kind of vague as far as instructions go. Is there a step by step to this method like in the Readme? I'm capable of ssh/telnet and what not, I'd just like instructions to do it correctly.

**Comment by tehfalcon-vw** [comment]
I don’t have the root password for as 1161 to do this.

**Comment by jilleb** [comment]
I will not supply any passwords here. Please stay on topic.
