### ISSUE TITLE
carplay on Delphi mib2 unit 

### ISSUE THREAD

**Issue by Alex2020-dotcom** [jilleb/mib2-toolbox#30]
Hi Jille,

hope all is good , i would like to know if possible to activate carplay with performance monitor . 
ive tried to update my unit and use dlink100 to add the patch but no success 

with all my research i find out that your the only honest person that can help and assist 

i am in canada , so my version will be NAR 

any idea ?

thank you so much for your help and support

**Comment by jilleb** [comment]
haha thanks !!
can I email you?

**Comment by Alex2020-dotcom** [comment]
Yes sure plz help
alex.fermtl2020@gmail.com

**Comment by kamilt86** [comment]
hi Jillie.
I am very fresh here.
I found this place because i am looking for person who can help me with mib2 delphi and CarPlay activation, like alex2020 i am at the same place :) have dlink, patch , software, patch , but don't know how to do this.
I know how to make it on harman :)
Please for any help.

**Comment by vag-d-oran** [comment]
Whatsapp 00213540240173

**Comment by Alex2020-dotcom** [comment]
Hey Kamil 
Did you find out how ?

**Comment by jilleb** [comment]
Currently, the toolbox doesn't support Delphi mib2 units.

**Comment by kamilt86** [comment]
Hi , thx for info , sorry i am quiet fresh 😊
Pleas tell me You know how to do Delphi mib2??
I bought solution but with no info how to do it :/


Wysłane z aplikacji Poczta dla Windows 10

Od: Chillout
Wysłano: wtorek, 25 lutego 2020 08:17
Do: jilleb/mib2-toolbox
DW: kamilt86; Comment
Temat: Re: [jilleb/mib2-toolbox] carplay on Delphi mib2 unit (#30)

Currently, the toolbox doesn't support Delphi mib2 units.

**Comment by kamilt86** [comment]
Hi, i don’t know but i am trying to find a way.

Pleas tell me are You doing something with Delphi mib2??

I bought a solution for delphi, but with no comment how to do it:/ 

I am doing with harman, but Delphi don’t know nothing :/

THX

Wysłane z aplikacji Poczta dla Windows 10

Od: Alex2020-dotcom
Wysłano: wtorek, 25 lutego 2020 05:23
Do: jilleb/mib2-toolbox
DW: kamilt86; Comment
Temat: Re: [jilleb/mib2-toolbox] carplay on Delphi mib2 unit (#30)

Hey Kamil
Did you find out how ?

**Comment by ovi1337** [comment]
i would like to join into this topic, i'm currently also trying to enable android auto and apple carplay on my MIB2 and need the dlink LAN workaround. Let's try to share our experience and let it flow into this awesome project :)
My D-Link adaptor is currently on the way to me and i'll have it this week to try the first steps with it.

**Comment by Red-1000** [comment]
hello Jilleb,
Nice work mate keep on going on .....

**Comment by milenmit** [comment]
Hey @jilleb  any news regarding MIB2 Delphi units :( i've researched a lot of over the internet but still the only solution that i have not checked yet is patch the unit - with d-link usb-ethernet some bash scripts and so on :(?

**Comment by andrewleech** [comment]
> Hey @jilleb any news regarding MIB2 Delphi units :( i've researched a lot of over the internet but still the only solution that i have not checked yet is patch the unit - with d-link usb-ethernet some bash scripts and so on :(? Or is there any tutorial/video with all steps for patching, i'm afraid that i can *****up the multimedia :)

This toolbox still does not support Delphi (neither does https://github.com/olli991/mib-std2-pq-zr-toolbox) but even if it did - the toolbox does not have ability to enable paid for / SWaP protected features like carplay for AA. The only way to enable features like this other than paying VW for them is hacking/patching the unit - this is always a somewhat risky procedure and instructions are hard to find.
