### ISSUE TITLE
Fix sed-issue with google earth patch

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#31]
![image](https://user-images.githubusercontent.com/8352494/72984439-0097af00-3de4-11ea-915e-097fa0c79383.png)

The code is currently :
```     sed -i 's/drawRockTree = false/drawRockTree = true/g' /gemib/drivers.ini```

And it should be modifying this entry in drivers.ini, but I currently don't understand why it's causing an error:
![image](https://user-images.githubusercontent.com/8352494/72984485-13aa7f00-3de4-11ea-99b1-4c838a1dd98a.png)

**Comment by Hamburgpriat** [comment]
How can you use Google Eath. It is disabled since 2017....

**Comment by jilleb** [comment]
No it's not 😁

**Comment by ots0ni** [comment]
> 
> 
> No it's not 😁

Any chance you could point us to what to do/search for to get the Google Earth functionality back? I'm suspecting that first I need to at least remove my car from the car-net subscription as I don't get a licence for GE from the VW servers and functionality is disabled. There must be some way to bypass this licence check completely so GE will work? With Audi MMI system I've seen some coding to get GE working without MyAudi, is it similar to this?

Anyway, thanks for the great work you've done! I'm really loving getting into and modding my MIB2 with your tools 👍

**Comment by gpg18p8** [comment]
> ![image](https://user-images.githubusercontent.com/8352494/72984439-0097af00-3de4-11ea-915e-097fa0c79383.png)
> 
> The code is currently :
> ` sed -i 's/drawRockTree = false/drawRockTree = true/g' /gemib/drivers.ini`
> 
> And it should be modifying this entry in drivers.ini, but I currently don't understand why it's causing an error:
> ![image](https://user-images.githubusercontent.com/8352494/72984485-13aa7f00-3de4-11ea-99b1-4c838a1dd98a.png)

Hi, if I add this manually is google earth then working?
Thx

**Comment by gpg18p8** [comment]
Hi, I have modified manually

/gemib/gemib.cfg 
and
/gemib/drivers.ini

But I cannot regonize any changes in my navi. Google earth view is still not here.
Am I missing something?

Thx

**Comment by jilleb** [comment]
This feature will only enable the 3d view for Google Earth. It will not enable Google Earth itself. You need the licenses for that, which you can get through carnet. 

Also see the following from the readme :-) 

![image](https://user-images.githubusercontent.com/8352494/100261066-81ff2700-2f4a-11eb-9ed9-f063d5a6cacb.png)

**Comment by gpg18p8** [comment]
Hi, is it possible to puchase such a licence?
Is it possible to get Google Earth on Mib2.5 on a 2019 car?
I can't find something... :/
Thank you!
BR

Chillout <notifications@github.com> schrieb am Mi., 25. Nov. 2020, 18:18:

**Comment by jilleb** [comment]
Not through the officials ways, but if you decide to create your own back-end, it should be possible.

**Comment by djskual** [comment]
Hello.
How to create your own back-end? need a server to answer to mib? what need to modify in mib? what kind of parameters do you need in your own server?

Very interested into this!!!

**Comment by Amskms** [comment]
> Bonjour.Comment créer votre propre back-end ? Besoin d'un serveur pour répondre à mib ? Qu'est-ce qui doit être modifié dans mib ? De quel type de paramètres avez-vous besoin sur votre propre serveur ?
> 
> Très intéressé par cela !!!
Did you succeed in creating your server or something else to find Google Earth? I'm interested my Google is charging indefinitely
