### ISSUE TITLE
user-switchable menumode

### ISSUE THREAD

**Issue by aigortt** [jilleb/mib2-toolbox#34]
Hi, I have not seen information about a toolbox option and I would like to ask before touching anything. within customization / various

there is an option that will be called user-switchable menumode

I don't know exactly what you mean could you help me?

Thank you very much and congratulations on your good work.

**Comment by jilleb** [comment]
Go to the following screen: 
- Customization
- Various

You will see a button:
Activate User-switchable MenuMode

This will set the "UserSwitchableMenuMode" config entry in info.txt for each skin to "true".
If you have this set, you will have an additional config in your main setup screens, that will allow you to switch between grid menu and flow menu:
![image](https://user-images.githubusercontent.com/8352494/73139844-93e61400-4072-11ea-919b-ee4321864d80.png)

**Comment by aigortt** [comment]
Thank you very much now if I have it clear 😄 another question I wanted to ask you.  You could make a menu / option that lets you change the driving modes from the screen without having to use any buttons.  I have also seen that in seat the customization option is not well built and comes out this way, could it be solved with any of your tricks?
![58C2E980-1E35-4D5D-BC35-B2666D32F190](https://user-images.githubusercontent.com/55894259/73139955-d2c89980-4073-11ea-975f-d3717549ff98.jpeg)

**Comment by jilleb** [comment]
I think this is caused by faulty design of the screens, and bad testing at Seat.


Driving modes without the button is currently not yet possible. Maybe I'll find a way.

**Comment by jingod** [comment]
Hello I activate green menu but where I find the telent on MIB 2.5 to access with dlink 100

**Comment by jilleb** [comment]
> Hello I activate green menu but where I find the telent on MIB 2.5 to access with dlink 100

I don't really understand the question, especially not if I try to relate it to this topic.

**Comment by jingod** [comment]
I look for the item on the green menu to access dlink dub100 not internet (telent)

**Comment by jingod** [comment]
![15811623352311724613211475043707](https://user-images.githubusercontent.com/42876315/74084607-fa0a6800-4a70-11ea-9f5d-8aca8a84817c.jpg)

I look for the item on the green menu to access dlink dub100 not internet (telent)

**Comment by jilleb** [comment]
This is never in the menu on MIB2
