### ISSUE TITLE
Cannot activate Developer Menu of Audi A6 facelift (MIB2 Harman) firmware P0034

### ISSUE THREAD

**Issue by giginson** [jilleb/mib2-toolbox#38]
Hello

Cannot activate Dev menu of Audi A6 facelift firmware P0034, with VCDS clone 19.
After 5F - Security tried S12345 and 20103 security codes and both let me enter in adaptation menu. After that when try to change Developer mode in active I receive an error: “Request out of range:” and Green Menu remain unactivated.
Do you know other way to activate ?

I have VCP clone 5.5.1 and OBDEleven prof. I tried with ODIS too. Error and not activated ... 

Is there a way to activate it with MIB2 toolbox ?

I need to activate Dev menu because I need green menu activation in order to acitvate user define mode for firmware update of my MIb2 units. If there onother way for firmware update ... let me know. If I don't activate user define mode mode before begining firmware update, MIB2 units restart to the main menu after couple fo seconds of Update firmware begins.

**Comment by olli991** [comment]
You need to change your session to Engeneering Mode. After that you can change the coding and activate the green menu.

**Comment by giginson** [comment]
Yes,   i know. But every tool i used it gives me error when i want to activate Developer Mode.

**Comment by jilleb** [comment]
I don't know any other way. It helps if you share the error.

**Comment by nicof38** [comment]
Have you checked script available at : http://idevx.net/menu-cache/
especially there : http://idevx.net/Fichiers/Logiciels/MMI_3G_3GP_Activation_Hidden-Menu.zip ?

**Comment by giginson** [comment]
I didnt check it because Mib2 its not the same with MMI 3G Plus. Script is for 3GPlus. Using it may brick unit because it’s not designed for Mib2. 
Thx anyway.

**Comment by jilleb** [comment]
Maybe it's not an MIB2 High but Standard?

**Comment by giginson** [comment]
No sir. Its MHI2. So it’s MIB2 Harman. Or High how you named it.

**Comment by nicof38** [comment]
Hi there,

I had tried on mine, and same as yours with VCDS, until today. I did run VCDS 20.4 (latest release), and with S12345 it has worked perfectly.
I now have green menu access (GEM4.0)

**Comment by Pixitrabi** [comment]
> 
> 
> Hi there,
> 
> I had tried on mine, and same as yours with VCDS, until today. I did run VCDS 20.4 (latest release), and with S12345 it has worked perfectly.
> I now have green menu access (GEM4.0)

Hi,

Where can I enter S12345 in VCDS? I can't enable developer mode in 5F module! Thus, after entering the security code, a "Request out of range" message appears. It's not an audi, it's a skoda swing + radio!

**Comment by Sparta18** [comment]
Hello,

A3 8V 2017 VCDS clone 20.4, MIB2 High => Developer menu can't be enabled.
Have tried security access 20103 (accepted but coding out of range), "S12345" gives me an invalid key.
I think I will get a VCP to be sure I won't have any trouble enabling it.

**Comment by Pixitrabi** [comment]
Hello!

 

Thank You for your help! 

I found the video below so the problem was solved and I was able to activate the Developer menu with OBDeleven.

https://youtu.be/R9WlrkBioi8?t=34 <https://l.facebook.com/l.php?u=https%3A%2F%2Fyoutu.be%2FR9WlrkBioi8%3Ft%3D34%26fbclid%3DIwAR33WmdT1C9N4KB89t-4EuUqtpmEEmeDt1JrKnkPLWr_A4vLRnO_QRU7QaM&h=AT32Zjno_Pq7bc0dfo00CGNgFbBdYVY0wkDLxLsuPPRepvNzhpnptESbq-EyMttvFNWaiIfetpNbWSfyaLbjrnqeBZgIBDhAx5n_z91WJPOmPdOtV4U6VG_2QdTUSiFaQdqE> 

 

By,

Pixi

**Comment by Sparta18** [comment]
Thank you,

Finally I didn’t get a VCP and instead I bought an OBDeleven pro. Adaptation for developer mode finally accepted :-)

**Comment by giginson** [comment]
What version did you activate ? P0034 from Audi A6 2015 facelift ? I tried with OBDPro too and only errors.

Thx

**Comment by Sparta18** [comment]
> What version did you activate ? P0034 from Audi A6 2015 facelift ? I tried with OBDPro too and only errors.
> 
> Thx

Have you changed Service Mode in obdeleven ?

**Comment by giginson** [comment]
Yes, I tried with Service Mode change and without ...going directly to the adaptation ...always error..

**Comment by Sparta18** [comment]
Apparently guys with your firmware has done it sucessfully.
https://www.audizine.com/forum/showthread.php/852780-2016-A6-RS6-S6-A7-S7-RS7-Apple-CarPlay-actived-and-Android-Auto/page3

I think they update firmware first, but be careful from what I remember a firmware update erase all FEC codes.

You should contact a "pro" of this kind of things to help you apparently they manage to do it.

**Comment by giginson** [comment]
Guys from that forum never show how they can update to any version from P0034. Update process cannot even begin only if you choose from Green Menu User Define Mode and check some stuff from firmware. But in order to activate Green Menu  you have to activate developer Mode. Dev Mode cannot be activated at this car, with this software version with all tools I tried. I dont have VCP original but I cannot buy this only to try activating Dev Mode. There is another way, by telenet and modifying some file and give some linux comands after login with Putty ... but nobody give instructions. Putty acces is permited by 123 and 23 ports.

**Comment by Sparta18** [comment]
Like I said, call a "hacking pro" ... you've spent 7 months on it.
ip is 172.16.250.248 port 123 password is firmware specific

They don't enable dev mode with files modifications.
http://wiki.mr-fix.info/index.php?title=MIB2

Instructions are everywhere you just need to search well
https://rennlist.com/forums/991/1049794-porsche-pcm-upgrade-hack-for-android-auto-is-this-real-7.html

**Comment by goses** [comment]
giginson, did you solved the problem? It seems that i have similiar.. but i have MIB2 Technisat/preh on my Golf6, 0478 soft, and I cant activate dev mode either.. tried VCDS 21.3 - "out of range" and ODIS 5.1.6 - some error... in both I entered security code 20103.. any ideas? thanks in advice

**Comment by giginson** [comment]
Try with Carly or OBDeleven. Always working with Technisat/preh . Your VCDS is OLD for MIB2 .

**Comment by goses** [comment]
Ok thanks, but unfortunately I dont have Carly and OBDeleven.. only vcds or odis

**Comment by Deezell** [comment]
I've activated Developer mode using OBDeleven on a 2015  A6  with MHI2_ER_AUG11_S0034  software. I still haven't been able to access the green menu. Like the OP, my attempts to upgrade the firmware  to K3663 Android auto /Carplay fail, with a read error.
![Not read error](https://user-images.githubusercontent.com/78157740/177348557-6046b1a8-a9c3-4ca3-bfe1-5aca259af0ba.jpg)
I only have the choice of STANDARD update, user defined is grey, but this can be enabled in the green menu, if I could open it from the mmi.

**Comment by Deezell** [comment]
Final steps to enable user defined.
![20220706_154538](https://user-images.githubusercontent.com/78157740/177578326-24aa33af-2aab-48e8-a0e7-d2bf28b55e6c.jpg)

![20220706_154331](https://user-images.githubusercontent.com/78157740/177578433-f6a7233e-1548-4a11-9104-2b88df5df898.jpg)

**Comment by Deezell** [comment]
And finally, user defined is still greyed out on the firmware update, BUT, all the modules in the standard list can be edited. They're all labelled Y, N, or N/A, so if you want to run update for just some, select the modules current status, and deselect Application, which will be ticked on modules with Y. Don't tick Bootloader, unless you know what its for. I don't but I could guess the brick like consequences.  Fwiw, I think this editing was available on MIB without the need for any green menu enabling, I'm sure I've seen those sub menus before.

**Comment by Deezell** [comment]
Final comment, my stalled update was due to using oldish SD card. Bought new fast MSD with adapter, worked perfectly, smartphone access, AA with maps, Spotify etc now working. This is a Jan 2015 A6 Quattro earliest version with MIB2 afaik.

**Comment by johunb** [comment]
@Deezell
Thank you very much for your instruction. 

I have the same problem. I have installed the same firmware version on my MIH2: MHI2_ER_AUG11_S0034_MU0073 and I also want to have the Green Menu activated on this version for upgrading firmware and selecting the components that have to be upgraded. 

I also tried VCDS, but also got the error "Request out of range". I think here could be the solution: https://forums.ross-tech.com/index.php?threads/29853/
I didn't try it yet.

Which firmeware upgrade steps did you choose? 0034 --> 2589 --> 3634 --> 3663 or 0034 --> 3634 --> 3663
I think your attempts to upgrade the firmware directly from 0034 to K3663 fails because of unsupported trains.

Which components did you label Y, N, or N/A when upgrading?

Thank you!

**Comment by Deezell** [comment]
I used the k3663 AIO (all in one) update on the MIBsolutions.one site, link here https://mibsolution.one/au_3663_aio
This comes with all the modules ready configured,  when you load it will display all the modules with Y, N and N/A already ticked. There is the option to add Bose but it comes with a health warning in the readme. This does it all, there are no further changes required when the script runs its course. You may at most get a few software version errors on a scan of module 5f, these can be eliminated using a short bit of coding with obd11 or VCDS. I did not need to enable SWDL in the GEM for this, just some relatively simple steps to add an XOR of a setting code
The aio brought me from S0034 to K3663 in one go, no major issues. This is quite an achievement on such an early version of my mib2, as the car was built end of 2014,  and Audi would not provide their upgrade on any A6 C7 earlier than mid 2016. Mr-fix on YouTube provides the best tutorial, plus links to the resource and the subsequent maps updates.

**Comment by johunb** [comment]
How long does the AIO-upgrade require (minutes)?

For AOI-upgrade, did you only turn on the MIH2 or did you also turn on ignition and additional external power supply?

**Comment by Deezell** [comment]
It takes about 20 minutes, I done with engine running as ignition goes into standby, and I didn't want to try disabling standby timer. Heres the tutorial.  https://youtu.be/VS21Lyess7o
If a module fails to load  or seems to halt at 99% you can press continue, not exit. I had one which did the latter. It didn't seem to matter and when I ran the setup a second time all modules reported as N/A so it got them all. If you have obdeleven or other, clear any faults. I had a few 'incorrectly coded ones from previous tinkering trying to wifi client working to supply Google maps overlay, as my car has no sim slot, (didn't work), so I worked back through the history and reversed anything I'd changed (except ripping CD to Hard Disk). Also, I didn't tick Hard disk for factory reset as advised on the tutorial as I had a lot of music on it and didn't have the source mp3 files saved, and you can't backup the hard disk juke box. It's a bit scary tbh, but it seems to be bulletproof. Note my comments on the YT tutorial with the minor issues I encountered with touchpad hardware. Doesn't prevent it working.

**Comment by johunb** [comment]
Some users in DEB-Forum report from sometimes failure of KI ("Kombiinstrument") after upgrading to K3663, depending of HW- and Software-Version of KI. 
My KI is: HW: 4G8 920 933 Q, H08, 0043

What KI do you have? Do you have any error/failure since upgrade to K3663_1?

P.S.: You can enter KI by pressing the daily km-Button and then the ignition button.
![KI](https://user-images.githubusercontent.com/34592963/209089319-2dde5462-152c-420f-8a57-0796da088dd1.JPG)

**Comment by Deezell** [comment]
That's whats in mine. I'd no trouble there. Just the scroll pad when using Google maps on AA doesn't interface. Also my rear climate control module when selected on 'Car/Car.Systems/AC/Settings for rear cabin', it no longer displays the setting on the rotary graphic in the mmi, but it is displayed on the front climate control, so I can check and set rear.

![Screenshot_20221222-092836_OBDeleven](https://user-images.githubusercontent.com/78157740/209111698-1c8ed9ae-907a-4542-87be-404b9530d6da.jpg)

**Comment by Deezell** [comment]
Nice tip for the dashboard config btw, didn't know that one. All other data identical to yours, so nothing seems to have changed after K3663 update

**Comment by johunb** [comment]
You wrote: "_And finally, user defined is still greyed out on the firmware update, BUT, all the modules in the standard list can be edited. They're all labelled Y, N, or N/A, so if you want to run update for just some, select the modules current status, and deselect Application, which will be ticked on modules with Y._ "

I want to upgrade to K2598 first (not using AIO to K3663), have no Green Menu and user defined is greyed out on the firmware update to
![IMG_2429](https://user-images.githubusercontent.com/34592963/209232126-24296918-67f9-4213-b9a8-621021b0f499.JPG)
![IMG_2431](https://user-images.githubusercontent.com/34592963/209232153-0b932ae6-00c3-4309-b877-d70adf0f33ab.JPG)
o. How did you enable/disable modules? It does not work for me...

**Comment by johunb** [comment]
Do you miss this  rotary graphic since you have updated to K3636?

![IMG_2434](https://user-images.githubusercontent.com/34592963/209232782-1df6e5a0-b4ce-4562-b380-b3cabf3c6d52.JPG)

**Comment by Deezell** [comment]
When you scroll  the cursor up and down the list of modules presented when you load the update SD file, you should be able to press the rotary knob to change from Y to N for a module to deselect it before you start the update, although my memory is vague on this, but I recall seeing this option at some stage when I was trying it first. I didn't change anything, all Y modules updated.
My mmi display for the rear Climate AC settings shows the control knobs but shows temperature at Min with no numerical display and doesn't change. The temperature for the rear does show correctly the front AC panel leds, and can be adjusted. It times out back to the front settings in about 6-10 seconds. I must mention that there were some occasional recurring OBD scan errors on my rear climate controller, one for a faulty read on the left airflow adjuster, another intermittent  one for the flap motor position sensor, open circuit or short circuit. Perhaps these errors affected the update of the module and caused the frozen display. I have not found any other mention of them in searches. The scroll problem is an Android Auto issue, I've found two other cases, but no solution.

If you're updating to K2698, why would you need to define which modules, it will only select them for update, Y, if there is new software for them. It will not update if your car doesn't have the module, and will display N/A. If you run the same update SD again after updating, they will all display N or N/A

**Comment by johunb** [comment]
_If you're updating to K2698, why would you need to define which modules, it will only select them for update, Y, if there is new software for them. It will not update if your car doesn't have the module, and will display N/A. If you run the same update SD again after updating, they will all display N or N/A_

Yes, I thougt the same when digging into the modules ... 

I'll do the upgrade to K3663 manually, not using the AIO-Package. 0034 --> 2589 --> 3634 --> 3663
My first step is to go to 2589 and checking if all works error free. Then 3684, then 3663.
Also some other users in DEB-Forum report some issues, when using the AIO-Package.
It seems, that in the AIO-Package there is a Downgrade-Option: [https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/discussions/79](url) but I don't know yet how to use.

I also wanted to enable GEM in MHI2_ER_AUG11_S0034_MU0073 manually but failed: [https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/issues/75
](url)

Thank you very much for your input to this topic!!

**Comment by Deezell** [comment]
For MHI2 softwares, you can enable GEM by turning on 'Developer Mode' in Adaptations of Control Unit 5F using OBD11. Im not sure how this translates to VCDS. I done this long before I upgraded to K3663 from MHI2_ER_AUG11_S0034, same as yours.  Once activated, you reboot mmi, then open GEM using Back and bottom left Soft button together.  

![Screenshot_20221223-172700_OBDeleven](https://user-images.githubusercontent.com/78157740/209384122-378000b5-d794-4edc-aaee-c4c57a81bf65.jpg)

This tutorial has an extra step than my OBD11, changing sessions from diagnostic to development. https://youtu.be/hpn1Uah6qBg

**Comment by AdamVadum** [comment]
доброго дня я новенький в цьому ділі! підкажіть як оновити GEM 3.0 до новішого GEM 4.12

**Comment by Deezell** [comment]
> доброго дня я новенький в цьому ділі ! підкажіть як оновити GEM 3.0 до GEM 4.12

Everything you need is here. 
https://mib-helper.com/index.php?train=MHI2_ER_AUG11_P0040#details 
You can search for your own current software train.
I think adding MIB2-Toolbox will upgrade GEM to 4.1. Read the Github details below.
https://github.com/jilleb/mib2-toolbox
