### ISSUE TITLE
Where to find language data on Audi firmware?

### ISSUE THREAD

**Issue by dewonsky** [jilleb/mib2-toolbox#39]
Hello, I took some time to analyze the firmware for audi. I would like to ask if you know which files are responsible for the language. I would like to change a few words.

**Comment by jilleb** [comment]
Check out the data inside:

\net\mmx\eso\hmi\lsd\jars\lang_data.zip
It contains .data files for the HMI.

Note: on VW/Skoda/Seat it's in
\net\mmx\eso\hmi\lsd\Resources\skin1\i18n

**Comment by dewonsky** [comment]
[Imgur](https://i.imgur.com/5S5nAPv.jpg)

This is my firmware. I don't have it there. Maybe i'm looking wrong?

**Comment by jilleb** [comment]
I'm talking about the folder on the machine itself.
If you're looking for this in the firmware distribution itself, look for app.img. It should be there.

**Comment by dewonsky** [comment]
I do not know if I understand correctly, but you will need to create a script for the SSD card that will replace the words to the current firmware? I don't know if this is exactly the case, but I found something like this: [Imgur] (https://i.imgur.com/jBQqcDU.jpg)

**Comment by dewonsky** [comment]
However, I found, but it looks like this. Can anything be done about it ? Will you need an SDK to translate this code? [Imgur](https://i.imgur.com/XsG4XEC.jpg)

**Comment by jilleb** [comment]
tts is text to speech. That's not what you're looking for. Look inside the app volumes, to find anything like language or i18n

**Comment by jilleb** [comment]
Closing this issue because it's not really related to issues with the toolbox.
