### ISSUE TITLE
Using WiFi DLNA as an entrypoint

### ISSUE THREAD

**Issue by zeppardev** [jilleb/mib2-toolbox#40]
Hey, I realized that all MIB2High units have a DLNA service working on port 49152 which is based on https://github.com/plutinosoft/Platinum and I was thinking of fuzzing the binary to find a vuln.

I know that this isn't an issue, just didn't know how else to contact you. 
Please hit me up on yal (at) tuta.io

**Comment by jilleb** [comment]
Thanks. Good idea. This was actually my first attempt at getting a point of entry, a few years ago. I didn't find any vulnerabilities within the DLNA service. It's easier to just update the PF configuration by POI update, to open up telnet on the internal wireless network.

**Comment by aes31** [comment]
WiFi connection didn’t worked on Skoda mib 2,5 1440, only dlink has connected by telnet.

**Comment by zeppardev** [comment]
Did you try fuzzing it with ufuzz in a virtual machine?

Feb 8, 2020, 13:55 by notifications@github.com:

**Comment by zeppardev** [comment]
@aes31
You need to connect your PC to the WiFi hotspot to be able to access the DLNA service on port 49152
Feb 9, 2020, 00:44 by notifications@github.com:

**Comment by jilleb** [comment]
> Did you try fuzzing it with ufuzz in a virtual machine? 

That sounds like a great idea. No I didn't do that yet. Really curious about your results! Would be quite scary if it's vulnerable, because there are a lot of MIB2s connected to the web with DLNA port open on the external interface 😨

**Comment by zeppardev** [comment]
@jilleb Most ISPs are filtering port 49152 so it wouldn't really have that large of an impact.

Can you by any chance contact me using Telegram or a similar messenger?
