### ISSUE TITLE
MIB2 Password Change

### ISSUE THREAD

**Issue by moe2501** [jilleb/mib2-toolbox#41]
The password has been changed for me. How can I view the new one?

**Comment by jilleb** [comment]
Dump the shadow file to SD-card. This will hold the password hash.

**Comment by moe2501** [comment]
Thanks in advance,
How can I best do that?

**Comment by nicof38** [comment]
Can be done with the provided script: https://github.com/jilleb/mib2-toolbox/blob/master/Phone/Apps/0/default/dump_shadow.sh

**Comment by moe2501** [comment]
Thank you nicof38, I'm sorry for my question. But I'm something new in this area.

How do I use that now?

I can't change with my MIB2.

Since the password is no longer known to me.

I wanted to contact you but no messages are possible here.

**Comment by moe2501** [comment]
Create a Sh file an then copy on SD?

**Comment by jilleb** [comment]
No. The script is in the toolbox already, and can be run through the green menu.

**Comment by moe2501** [comment]
Toolbox works with A6 MIB2?

**Comment by jilleb** [comment]
There's only 1 way to find out.
