### ISSUE TITLE
VW MIB2 firmware update error: Train is Blocked

### ISSUE THREAD

**Issue by giginson** [jilleb/mib2-toolbox#42]
Hello

For a Passat B8 2016 with MIB2 there is always an error when trying to update firmware to 3G0919360BK MHI2_ER_VWG11_K3332 MU1187.
I activated from Green Menu user define mode in order to update but I can't find how to make update using user define mode menu..

Thx

![Error_train_is_blocked](https://user-images.githubusercontent.com/60604897/74348419-56e08800-4dbb-11ea-8dc6-f80c0934bb51.jpg)

**Comment by capula** [comment]
Hi ,and i have the same problem on passat b8, i have firmware on sd card i can not install ,same train problem, unlocked green menu, i have VCP and vas5054a can give them something to fix

**Comment by giginson** [comment]
So. The problem can be fixed ? But, if you know, who generates that problem ? I have vcds latest version (18 or 19 ) Obdeleven profesional and VCP clone with cable( no vas interface ). I wait for instructions please.

**Comment by jilleb** [comment]
This does not look like it's an issue with this firmware. I'll close it, because it's off-topic.

If you have any issues installing firmware because of a blocked train, you might want to consider doing an EEPROM change to update your train info. This is not something you can change with VCDS.

**Comment by Navivag** [comment]
Hello everyone, how to modify eeprom please
