### ISSUE TITLE
Activated app connect for High MIB2 with only mirrorlink

### ISSUE THREAD

**Issue by pollopopo** [jilleb/mib2-toolbox#43]
is it possible to activate app connect on devices that only have mirrorlinks (MIB2 high before 10/2015) ??

on the version of the sign 0199 is certainly not present, is it possible to install it? I add that to date for the same units there is the 1100 version of the firmware which however does not seem to enable it automatically, in this case it would be possible ??

**Comment by jilleb** [comment]
Only if you have the FEC to support this

**Comment by pollopopo** [comment]
this "fec" if not present is not possible to install it?

what code should I read to understand if it is possible?

if present instead it would be possible to enable app connet instead of only mirrolink? I instead of the connect app I only see mirrorlink unfortunately, almost useless function if you don't have a sony cell phone

online there is a company that unlocks this function on the MIB2 that do not have it but the fact of having to send the unit 1000km away and the price make me desist from the aforementioned experiment (it costs less to take a unit used with all enabled .....).

if there was something cheaper and more practical ... I would also be happy to pay for this feature, fair figures as a € 200 license to unlock app connect must be added

sorry for bad English

**Comment by jilleb** [comment]
> this "fec" if not present is not possible to install it?

This is like a certificate, signed by VW that declares you can use a certain function. It can be enabled by paying VW or if you find a way to sign it. Or find a way to ignore the signature.


 
> what code should I read to understand if it is possible?

Hold MENU, and check the installed FECs



> online there is a company that unlocks this function on the MIB2 that do not have it but the fact of having to send the unit 1000km away and the price make me desist from the aforementioned experiment (it costs less to take a unit used with all enabled .....).

Yeah.. don't do that ;-) 

> if there was something cheaper and more practical ... I would also be happy to pay for this feature, fair figures as a € 200 license to unlock app connect must be added
> 
> sorry for bad English

No worries. it was perfectly clear to understand :-)
I cannot support any illegal activations here, but 200 is NOT a fair figure. You could pay less to VW to get it officially activated!!

**Comment by pollopopo** [comment]
No illegal activation. I'm only interested unlocking app connect and then paying the license in VW (in the end I would do a pleasure in VW since the license costs € 200) ... unfortunately the MIB2 prior to 10/2015 only have the mirrorlink and not the full app connect , I changed the USB port and soon I should update to version 1100 in the hope that this can unlock something, but I doubt it .....those who did (without changing the USB port though) did not find any particular changes...... I will cross my fingers 

I only asked if with this toolbox it was possible to inject the file or the sources to enable app connect ....

**Comment by jilleb** [comment]
:-) ok ok ok 
Try the update, updating is always a good idea. Let me know if there are any struggles with updating. It could be that your train isn't supported, but I can help you with that 😄 . It takes a simple EEPROM modification to get it to install.

**Comment by pollopopo** [comment]
it is very likely that I need your help, the mod I have in mind requires to be able to install the 3G0035043A unit update on the 3G0035043A unit, specifically the number 0343 which would be the software train MHI2_ER_VWG11_P2125 ....

**Comment by jilleb** [comment]
> the modification of the unit code appears on the mib in the settings or simply the verification of the files is eliminated allowing you to install whatever you like???

If you install the toolbox, and in the pro menu look for dumping eeprom, put the dumped eeprom data in a hex editor. you will see MHI2_ER_VWG11 somewhere down the line. Once you've done that, I'll assist you in modifying it!


> still a few days (I have the unit to repair for a desoldering that interpolates the rear channel) and I start with everything .... if I have the procedure to change the settings in eproom I would be very grateful and I gladly offer you a giant pizza : P

**Comment by pollopopo** [comment]
thank you very much, as soon as my unit returns from repairs I will soon make this change ..... thank you very much again, you have developed a great tool, you no longer need to go crazy with "VCP" for the eproom (which I just can't use : P)

**Comment by martinmikula** [comment]
Hello,

@pollopopo did you make it to work? I have the same problem. :( Can you please help me how to proceed? Or at least is it even working with new FW?

Thanks for any help...

**Comment by Alexnaum2009** [comment]
Hello ,work with last update software
