### ISSUE TITLE
Flash IFS root not possible

### ISSUE THREAD

**Issue by andy0172** [jilleb/mib2-toolbox#44]
It wont find the command out of the script!

Cannot execute - no such file or directory

Btw. flash unlock needs to be written together "flashunlock". Can this be fixed? Thanks

**Comment by jilleb** [comment]
Fixed it.

**Comment by andy0172** [comment]
When will the new version be available?

**Comment by jilleb** [comment]
It's already committed

**Comment by andy0172** [comment]
Script is still the same in latest release!

**Comment by jilleb** [comment]
Hmm, changes must have not been committed then. I'll fix it. But.....if you need to use the function, in the mean time it's easy to update this script by yourself 😉

**Comment by andy0172** [comment]
I've done this already before, the problem is, that these command are not working in the user context that the toolbox is working on! I thought you have found a problem for this as well.

Its still saying "file not found"

**Comment by jilleb** [comment]
With the "on -f" command, it doesn't care about the context. I use modifye2p in the same way.., works here. I can see if I can make it better.

**Comment by andy0172** [comment]
I tried this now:
    on -f rcc /net/mmx/fs/sda0/Advanced/IFS/flashunlock
    on -f rcc /net/mmx/fs/sda0/Advanced/IFS/flashmib -a 0x00BA0000 -d -f /net/mmx/fs/sda0/Advanced/IFS/ifs-root.ifs
    on -f rcc /net/mmx/fs/sda0/Advanced/IFS/flashlock

Get the error:
ldd:FATAL: Could not preload library /lib/libeccp-ne.so.4
