### ISSUE TITLE
Yes in a Audi its working, but the question is, how to get this functionallity into our VW software, because in the audi its a MIB2 high system like ours.

### ISSUE THREAD

**Issue by kamilt86** [jilleb/mib2-toolbox#45]
hi , Andy.

Please tell me how it's possible to make CarPlay work wireless ??
i am doing activation of harman mib2. 

Yes in a Audi its working, but the question is, how to get this functionallity into our VW software, because in the audi its a MIB2 high system like ours.

_Originally posted by @andy0172 in https://github.com/jilleb/mib2-toolbox/issues/22#issuecomment-555442944_

**Comment by vag-d-oran** [comment]
Auto-vag@hotmail.com

**Comment by jilleb** [comment]
Please don't post issues that are already posted.

**Comment by hondaa** [comment]
kamilt86 please write to me klaudia512@wp.pl (Carplay)

**Comment by andy0172** [comment]
Kamilt86 I use an extra adapter like carplay2air
