### ISSUE TITLE
How to go to the Green Developer Menu without menu button on A6/A7/A8/Q8

### ISSUE THREAD

**Issue by wangjunasd** [jilleb/mib2-toolbox#46]
hi, jilleb. On the audi A7 A8 Q8, the screen is full touch, and there is no menu button. Would you like to know how to enter the green screen mode?As far as I know, two fingers in the upper right corner of the screen long press to enter engineering mode.  Thank you so much! The firmware version of my car is MH2p_US_AUG35_P2539.

**Comment by mattcabb** [comment]
I don't know how yet, but I found a pic with one of the hidden menu screens enabled.

https://i.postimg.cc/76K9bsWH/99093105-2770912499901724-6067562644804468736-o.jpg

**Comment by wangjunasd** [comment]
> I don't know how yet, but I found a pic with one of the hidden menu screens enabled.
> 
> https://i.postimg.cc/76K9bsWH/99093105-2770912499901724-6067562644804468736-o.jpg

This is engineering mode,  put two fingers on the upper right corner of the screen for 2-3 seconds to enter.
