### ISSUE TITLE
problem with metainfo (mu 0199) :/

### ISSUE THREAD

**Issue by pollopopo** [jilleb/mib2-toolbox#49]
I have a problem, I'm trying in every way but it doesn't read the metainfo file as it happens to many :/

I have already tried the classic solutions (fat32, unzip directly to SD with 7zip or winrar etc ..)

I tried to modify the metainfo using the metainfo files that I use for the POIs but it doesn't work (obviously without altering the fundamental configurations for the correct indexing)

after the VW recall I have the
hardware revision 3G0035043K
MU 0199
SW train MHI2_ER_VWG11_S0259

before the recall was made
hardware revision 3G0035043A
MU 0199
SW train MHI2_ER_VWG11_K0259

I checked the IOC though and nothing has changed from the old to the "new"

should I try manual installation with the D-Link Dub-E100 ????

if I don't make the modification I can't modify the eeprom to install the revision MU1187 (K3332) because SW train is not compatible (could I try the SWDL in the green menu or not ??) .....

and then there is the modification of the FEC: P ... I would like to avoid using USB / uart

thanks again for the help :)

**Comment by djfanatix** [comment]
To go from 199 to 1187, you have to first install FW 814 and then 1187, then you don’t have the train issue!

**Comment by pollopopo** [comment]
thx for this information :)

**Comment by vwjap** [comment]
Just tried with mine and didn’t work vw golf 2017 original MID 2.5 unit from the factory never installed POI but has had the recall update (hotspot) at the beginning of the year
software version 0913
Hardware number 5NA035020
Hardware version H51
Serial no A845AOHB000****

So I tried it on 2x SD cards, 16g and 32g, plus a USB stick, and get the unable to read metadata2 error,

**Comment by vwjap** [comment]
Just a though on my 2.5 to update the poi you normally do all the updates on nav setting page, couldn’t be to do with that could it?

**Comment by pollopopo** [comment]
> To go from 199 to 1187, you have to first install FW 814 and then 1187, then you don’t have the train issue!

do you know the root password of 1187?

**Comment by matix131991** [comment]
Polloppo Try Uallm8IY or waMC0ISm

**Comment by pollopopo** [comment]
> Polloppo Try Uallm8IY or waMC0ISm

thx

I'm waiting to install it because I don't know the password :P

**Comment by matix131991** [comment]
> > Polloppo Try Uallm8IY or waMC0ISm
> 
> thx
> 
> I'm waiting to install it because I don't know the password :P



> > Polloppo Try Uallm8IY or waMC0ISm
> 
> thx
> 
> I'm waiting to install it because I don't know the password :P

You mean for archive password with firmware?

**Comment by pollopopo** [comment]
> > > Polloppo Try Uallm8IY or waMC0ISm
> > 
> > 
> > thx
> > I'm waiting to install it because I don't know the password :P
> 
> > > Polloppo Try Uallm8IY or waMC0ISm
> > 
> > 
> > thx
> > I'm waiting to install it because I don't know the password :P
> 
> You mean for archive password with firmware?

no, root acces :)

**Comment by turboblade** [comment]
Upgrade your firmware to one which the root password is known and
publicly available

**Comment by matix131991** [comment]
Everything works when i do manual install with e dub d link

**Comment by veso266** [comment]
wait how can I get the firmware?
