### ISSUE TITLE
 Execute failed: java.io.IOException: Unable to start programm

### ISSUE THREAD

**Issue by n3oka** [jilleb/mib2-toolbox#5]
Hi, 

i wrote the error at facebook some days ago.

The installation of this tools works without any problems.

When i want to start any script it will show me this error:  Execute failed: java.io.IOException: Unable to start programm

Tested with version 1.4B and 2.0.

Its not the SD-Card. The SD-Card worked on a other Harman Unit perfect.

My Navi is a crossflashed unit from Skoda (one with dual-antenna for LTE and SIM slot) with Seat Firmware 1409. I Got this unit from MQB-Coding.de (Mike).

Greetings

**Comment by jilleb** [comment]
Interesting. This error occurs when the scripts were not CHMOD'd to be executable.
I suspect something is different on your unit. I'll look at it with Mike

**Comment by n3oka** [comment]
Hi Jill,

okay, if you want, i can send mike the unit again. There he can check the unit.

**Comment by jilleb** [comment]
I believe it's fixed now. Cause was there was a missing mount.
