### ISSUE TITLE
What about uninstall?

### ISSUE THREAD

**Issue by branek** [jilleb/mib2-toolbox#50]
Great work!

I have one question, is it possible to recover to factory state after installation?

**Comment by jilleb** [comment]
Sounds like a good idea to implement.

You can remove all of the changes by doing a firmware reinstall.

**Comment by jilleb** [comment]
I'll implement a feature that removes mqbcoding.esd
That'll be enough.
But the dealer will not know about this menu, and they wouldn't care about it either. (source: I know a lot of them, most don't give anything about stuff like this).

**Comment by olli991** [comment]
This could work as a script ideas:

```
#!/bin/sh
#Cleanup all MQB Toolbox scripts

mount -uw /mnt/app

rm -r /mnt/app/eso/bin/PhoneCustomer/*.sh
rm -r /mnt/app/eso/bin/PhoneCustomer/default/*.sh

mount -ur /mnt/app

exit 0

```

Uninstall everything:
```
#!/bin/sh
#Uninstall MQB Toolbox

mount -uw /mnt/app

rm /mnt/app/eso/hmi/engdefs/mqbcoding.esd
rm -r /mnt/app/eso/bin/PhoneCustomer/*.sh
rm -r /mnt/app/eso/bin/PhoneCustomer/default/*.sh

mount -ur /mnt/app

exit 0

```

**Comment by jilleb** [comment]
Hmm, it could be possible. I'll try 😁

**Comment by olli991** [comment]
Maybe we have to call the script something like `x-uninstall.sh` so it will come last? 🤣

**Comment by olli991** [comment]
If it works here is a userfriedly version 😆 

```
#!/bin/sh

#Info
DESCRIPTION="This script will uninstall MQB Toolbox"

echo $DESCRIPTION


. /eso/bin/PhoneCustomer/default/util_info.sh
mount -uw /mnt/app

echo "Deleting mqbcoding.esd"
rm /mnt/app/eso/hmi/engdefs/mqbcoding.esd

echo "Deleting MQB Toolbox scripts"
rm -r /mnt/app/eso/bin/PhoneCustomer/*.sh
rm -r /mnt/app/eso/bin/PhoneCustomer/default/*.sh

mount -ur /mnt/app

echo "Uninstall complete. Please reboot unit."

exit 0

```

**Comment by jilleb** [comment]
Added in 16baaa5dbe636c8c714c94b182ad27282d1890cb
