### ISSUE TITLE
vw has fixed root access!

### ISSUE THREAD

**Issue by pollopopo** [jilleb/mib2-toolbox#51]
with calls for updates vw has fixed root access.  D-link 100 and uart hack not work!

I don't know if mib 2 toolbox can be installed or used after the update unfortunately.

**Comment by jilleb** [comment]
Can you show any source of this?
They released a security update, but thit is NOT for the DLINK-access, it just fixes the config for the firewall...

**Comment by pollopopo** [comment]
one who changes via dlink i 'fec' .... i have usb uart at home and on Monday the dlink arrives .... if you have to do tests i am available .... i am the one who has problems with metainfo  also in the previous post ....

they have been aware of the flaw for a long time, there are documents from 2018 that speak that I am aware of it and for 6 months there has been a rolout of the fix

sorry for bad english :P

**Comment by pollopopo** [comment]
is it possible to have your contact? I wanted to ask 2 or 3 questions just to get answers without going continuously off topic

I needed to know if through alternative modes (IPL system and zmodem connection) it is possible to flash another firmware to eliminate the problem you have with the "new" firmware :)

I found the K3332 (1187) sign which should also run on hardware h41 (the firmware is for harman) and should not give problems .... obviously the sw train does not allow me to use it in the classic way

**Comment by matix131991** [comment]
How You know wich firmware can works with your unit?

**Comment by pollopopo** [comment]
> How You know wich firmware can works with your unit?

obdeleven tells you which one is the latest for your hardware

**Comment by matix131991** [comment]
So  if obd11 say  that no new firmware is for your that is? I thought that can be upload some similar firmware like on unit.....😬

**Comment by pollopopo** [comment]
obd11 use hardware info (hardware version and hardware number)... 

if it does not report anything there is that no one who has obd11 has higher revisions at that time.

for the gearbox I have a different version (1141-- 1142) ... for the engine no revision for example (1148)

**Comment by matix131991** [comment]
So there is solution to have higher or no? I have '15   production A4 B9 with Harman unit MHI2 ER AUG22 S2116 MU333. I thought that  MHI2_ER_AUG22_K2156 can be upload. If not maybe in eeprom i can change that.

**Comment by pollopopo** [comment]
returning to the discussion,

practically the user told me that the new firmware has no root password and therefore root access is no longer possible ...

**Comment by pollopopo** [comment]
problem solved .... who informed me informed me badly .... I just lost sleep to find the password being a recent firmware.

**Comment by jilleb** [comment]
So to conclude:

D-Link connection is still possible with the latest firmware.

Source: I tested it many times on most recent firmwares, even the ones with the security update. There's a lot of misinformation, especially from people whose main income comes from patching MIBs, who don't want others to do what they do. Let's not spread misinformation.
