### ISSUE TITLE
[Not a bug] - MIB2-STD Support? 

### ISSUE THREAD

**Issue by phoinixgrr** [jilleb/mib2-toolbox#52]
Owner of a Seat Leon 2020 Model, with MIB2 STD entertaiment system:

> SW TRAIN = MST2_EU_SE_ZR_P0514T
> SW MU = 0514 
> HARDWARE = H50 

Photo for illustration: 
![Photo](https://i.ibb.co/Rp8PPMG/IMG-20200322-172538.jpg)

Are there plans to support the STD Version? 

Is it so different in hardware than the High version? 
Could I support the development of the STD Version mib2-toolbox?

**Comment by jilleb** [comment]
The STD hardware is completely different, it's done by a different manufacturer. The HMI is mostly the same, and so is the OS(QNX), but the needed backdoors for getting the MIB2High toolbox working are specifically for MIB2High. I don't have any MIB2STD hardware, so working on this would be like walking in the dark. 

And honestly, I don't want to invest into buying a MIB2STD, nor do I wish to invest much of my time in it.
