### ISSUE TITLE
Green Engineering error Mib1

### ISSUE THREAD

**Issue by mafi31** [jilleb/mib2-toolbox#53]
Hi have Discover Pro Mib1 (5G0035043) and it was cracked one fw 0388, when I updated my unit to fw 0407 component protection enabled on the screen and someone disabled component protection after that Navigation didnt work anymore and when I wanted to go into the green engineering menu it says screen -1 not found. How can I fix it?
![20200115_204412](https://user-images.githubusercontent.com/62706163/77665952-0303ba00-6f89-11ea-975d-495e744810cf.jpg)

**Comment by mafi31** [comment]
Is there no solution to get into the GEM for Discover Pro Mib1?

**Comment by jilleb** [comment]
It looks like the Main esd file is missing... you can try to do a full firmware install, it should recover the Green menu.

**Comment by mafi31** [comment]
thanks for information but when I search for FW200 or FW388 links are not working. But I have a FW407 so if I reinstall it Green Menu might come back?

**Comment by mafi31** [comment]
I found a DisableGEM in the FW407 folder that its already on my head unit. if I delete DisableGEM and setup again then settings can come back again?
![DisableGEM](https://user-images.githubusercontent.com/62706163/78185480-d31a5200-7473-11ea-8413-92f72189b253.jpg)

**Comment by jilleb** [comment]
I honestly have no idea...

**Comment by mafi31** [comment]
I tried it and it worked only navigation doesn't work. My car not came out with navi, first owner retrofitted mib1. So is there any solution to make it work again? Thanks

**Comment by veso266** [comment]
wait, wait where did you get software update for your unit

I have Device Part Number: 3Q0035819A and I am looking to find software update, so I could maybe  install mib2-toolbox with it (if I manage to to modify the update with mqbcoding.esd included)

**Comment by mafi31** [comment]
I found software update on google.
Sure you can find updates for your unit but Mib2 toolbox is not for your unit as they say: An MIB2 HIGH or MIB2.5 HIGH infotainment unit. It will not work on MIB1 or MIB2 Standard units. Discover Media / Compostion Media is not MIB2 HIGH!
 https://github.com/jilleb/mib2-toolbox

**Comment by veso266** [comment]
@mafi31 yea I figured that out already but I want to somehow install this into it, so if I manage to find software update that will install into it, I can probably modify it to include mib2-toolbox

The only thing I found was station database which is not much use as its only pictures that are probably copied to a specific location in the unit

**Comment by veso266** [comment]
hmm according to this: https://www.digital-kaos.co.uk/forums/showthread.php/817970-VW-3Q0035824A-MIB-2-loop-shutdown-after-10-seconds-after-upgrade-FW?s=a9fea15d9b02b642dd98acad4b4e9d9a&p=3840486#post3840486

this sw is not meant to be downloaded

**Comment by mafi31** [comment]
@veso266 Yeah its so complicated to find firmwares for these units. For example my friend has a same unit as yours and his units fw version is 0245. I think its better to buy a Mib2 or higher...

**Comment by veso266** [comment]
maybe some dealer would be so kind and share some updates?

do you know if it is at least possible to update StationLogos?
http://vw-mapscdn.tdd.adacorcdn.com/RSDB_VW_Multi_EU_v1.10.10.7z

because it says on the website 
the database update will refresh the data pool (radio stations, logos of the stations) of “Composition Media”, “Discover Media” and “Discover Pro” 

sitill not sure which unit do I have

**Comment by mafi31** [comment]
@veso266 Im sure dealer will cost money for that.
That Station logo updates for Mib2 units.
Your unit is Composition Media.

**Comment by veso266** [comment]
yey then station update can be used as vector of entrance and we don't need software update
now I just have to figure out how to calculate checksum of metainfo2.txt file as I want to reduce this update to only account for Composition Media units (STD_TS folder + Common (which is just SQLLite database that can be opened with DB Browser for SQLLite and it has tables with station names in it)

**Comment by veso266** [comment]
OK
a bit according to this buletin:  00-19-04 - Set-up SD Creator to Obtain Software Updates
https://static.nhtsa.gov/odi/tsbs/2019/MC-10163538-0001.pdf

you need a special SD Card creator program to download the update
which is uvailable on this server: https://mirrorserver2.vwhub.com/dav/BTAC/TradeRetail/Tools/SD-Creator/

but you need a private Key(SSL Certificate) to connect to the server, there is even a video: https://audi-external.kzoplatform.com/player/medium/1323594103425865057?display=vid

the file we need is: https://mirrorserver2.vwhub.com/dav/BTAC/Trade-Retail/Tools/SD-Creator/setup_V1.0.exe

but the firmware is probably on that server somewhere and without SSL certificate there is now way to download it

**Comment by veso266** [comment]
let's continue here: https://github.com/jilleb/mib2-toolbox/issues/59
so we don't get offtopic
