### ISSUE TITLE
Metadata2 error

### ISSUE THREAD

**Issue by vwjap** [jilleb/mib2-toolbox#54]
Ok I have the metadata2 error but just had a thought, what would happen if I plugged in obdeleven and changed the service to developer mode? It’s probably nothing but earlier I was playing and I needed to change mode to get something working and thought about this problem

**Comment by jilleb** [comment]
Ah cool thinking. And did it work after you changed to dev mode?

**Comment by vwjap** [comment]
No it didn’t work, sorry about the delay, had to find tablet/obdeleven adaptor, charge tablet and sleep, tried it in all 4 modes (even though I know 2 are just obd2 sniffers) 

Need anything else just let me know

**Comment by vwjap** [comment]
So when I used to do work on Vauxhall vectors radios it turned out when I connected to one all was fine, but every now and then you’d get some that wouldn’t work the equipment if it was turned off, someone found out that some radios were made in Portugal and others Eastern Europe, ok there was no real fix, we just let the drivers know to don’t turn the radios off, just mute them, so could this be the case, some are made in one factory and some in another? This being the case could the directory structure be different and that what’s throwing the error? Is there away of getting the directory structure put on a SD and send to you? Or didn’t some SD readers only except upto 2/4Pgb cards? 

Just thinking out loud

**Comment by vwjap** [comment]
Another thought

Could it be that I only have one skin in the engineering menu, and when the metainfo2 is trying to sideload the payload.sh it gets to the line of skin2 and as the directory isn’t there it throws the error halting the installation? In not to sure if your payload.sh creates a new directory/file on the system or just tries to access something that in my case may not be there

**Comment by jilleb** [comment]
No, it only installs 1 file, and it's not installed inside the skin.

**Comment by vwjap** [comment]
Ah ok, is there a way I can find the io-controller version?

**Comment by vwjap** [comment]
IOC 8283
