### ISSUE TITLE
MIB2 High Firmware update/maps

### ISSUE THREAD

**Issue by sdvolks** [jilleb/mib2-toolbox#55]
Hello, I retrofited my 2019 NAR Arteon with a MIB2 High virgin unit and had it activated to the car. The only thing that doest work is nav. I work for a minute at startup and then goes away. Im thinking it needs an update. Thank you for any input or help you may have.
 Device part number: 5NA035026
 Hardware: H51
 Software: 0921
 Navigation database:
V03959803EE0057 NAR 2017
V03959803EE
0057
NAR

**Comment by jilleb** [comment]
I have no NAR firmware, I'm sorry.

**Comment by sdvolks** [comment]
Thanks for getting back to me so quick!
