### ISSUE TITLE
[Enhancement] Add dedicated Longcoding for Splashscreen-Byte-Change

### ISSUE THREAD

**Issue by olli991** [jilleb/mib2-toolbox#57]
Hey jilleb, for Splashscreen-Changes you already writes how it´s done. We can use the force method or we need VCDS/VCP/OBD11... to change the byte 18 forwards and backwards. In the newest version we also can do so in the greenmenu in the longcoding section by scrolling through the whole 5F-STG. 

Why not add one extra screen/entry into coding or splashscreen menu itself and we only have one option in there to change the byte (the slider)? This makes this process faster and more "out of the box".

**Comment by jilleb** [comment]
Yes, I had this, but it didn't work. It only changed the graphic of the car in the status screen, but not the startup graphic. It's like the long coding needs an additional "mode" for some of the settings.

**Comment by olli991** [comment]
I found with VCDS that there are two ways to code Startupscreen and Startup-Sticker-HMI
Maybe we code the wrong one here. One coding is in Byte 18 and one is over Adaptions and is coded with four numbers. i dind´t play around with it, maybe sticker is the behaviour for Beatslogo.

Additional to this: Dump shows me there are 10 screens. But VCDS only lists 9. It seems a bit buggy.

**Comment by jilleb** [comment]
The Startup sticker in Adaptation is indeed for the additional logo's (Beats, Dynaudio, Wifi, etc).
VCDS is a little crappy, they are based upon label files. In reality, byte 18 allows 00 to FF values, so 256 different possibilities. :-) if you check the dump, there's also a textfile with the available ones listed, liked between the number and the graphic file used :-)

**Comment by jilleb** [comment]
I've tested, and currently I cannot get this coding fully working. I'll put it in the fridge for now.
