### ISSUE TITLE
[Skin-Template] Seat FW 1409 - Transparent Radiologos

### ISSUE THREAD

**Issue by olli991** [jilleb/mib2-toolbox#58]
I´ve build a template and want to share it within this project but I don´t know how to place templates for all in this project or github at all... I think it need to go under Wiki like the clocks but I can´t find any option to add something in there... so I opened up this "Issue" knowing it isn´t an issue. Please let me know what is the desired way :-)

So back to my topic here. I started to modify my skin a little bit and startet with one small change which triggered me all the time :D The radiostation logos had a white background even though the logo itself is transparent.

This template is for Seat only and is based on the Firmware 1409. I don´t excactly know it but image-names may vary and so my files may be not working on other firmwares.

Here you see a before (complete stock skin from factory):
![d3dac071-0378-4755-8600-eb211a0df4ec](https://user-images.githubusercontent.com/55631413/79052893-c3e89080-7c39-11ea-8808-ab9dde7cd676.jpg)

And here the after (only changed this specific thing):
![0718c7fe-0e66-4e76-80a2-6c47bfffd4a5](https://user-images.githubusercontent.com/55631413/79052916-ef6b7b00-7c39-11ea-91d1-26c4f3b38649.jpg)

To get this behaviour you only need to edit one file in the skin 1, 4 or 5 (or all if you wish to).
It´s the image `img_1494.png` which you need to replace with a fully transparent one.

Here is the stock one:
![img_1494](https://user-images.githubusercontent.com/55631413/79053038-90f2cc80-7c3a-11ea-928e-91e06f7e3d3e.png)
 
And here the edited (I also deleted the shadow because it looks odd with it):
![img_1494](https://user-images.githubusercontent.com/55631413/79053057-a9fb7d80-7c3a-11ea-8cf5-7ef04796ca8b.png)

Picture of transparent  background with shadow for instance:
![13eba15c-6a25-4dc1-8a5a-a97258d36c1f](https://user-images.githubusercontent.com/55631413/79053072-c39cc500-7c3a-11ea-93ee-b4171140d2bf.jpg)

To get this done I obviously compressed the skinfiles. So if you don´t want to change this by yourself you can use the following .mcf-files. In this files there is nothing changed except this image.
You find 3 files named after the skins 1,4 and 5. Copy those files into the right skinfolder and rename them to `images.mcf`, then copy them to your unit. 
I also included the extracted raw img_1494.png (stock and modified) in the ZIP:
https://drive.google.com/open?id=1NrAtrNcBkNxXlp2XUKK5BC1zLpudyk_d

**Comment by veso266** [comment]
wow if I could get the whole theme and theme my WV Golf radio with it that would be great
That is the most beautifull theme I have ever seen (I know you didn't create it but if it could be copied to other units)

**Comment by olli991** [comment]
It is the standard Seat theme and I don´t think you can simply copy it over yours this easy because you have completly other buttonplacement in the system and so on. Furthermore the compress and extract-scripts are different. Technically in the Zip above you have the whole Skin as mcf. If VW also uses mcf you could theoretically overwrite yours... but I this is completly on your own risk. This is out of my knowledge.

**Comment by jilleb** [comment]
Great work!! :-) 

I've done the same some time ago on MIB2.5:
![image](https://user-images.githubusercontent.com/8352494/79125081-d4b21700-7d9d-11ea-9ddf-bfd419689b1b.png)


I'll have a look if I can grant you rights so you can edit on the wiki @olli991

**Comment by olli991** [comment]
@jilleb thanks for giving me the rights. I added a new page and some files to the repo and give them a bit of a structure... i hope i´ve done everthing the right way without messing up your structure. I also edited the Wikioverview.

You can find the new wiki [here](https://github.com/jilleb/mib2-toolbox/wiki/%5BSeat%5D-Graphics-modification:-Transparent-background-for-radiostation-logos) and the added files [here](https://github.com/jilleb/mib2-toolbox/tree/master/Modifications/Graphics/Seat/Transparent%20Radiostation-Background)

I think we can close this "issue" then :-)

**Comment by andy0172** [comment]
Can someone find the file on MIB2.5 Skoda? I searched already, but couldn't find similar file.

**Comment by olli991** [comment]
> 
> 
> Can someone find the file on MIB2.5 Skoda? I searched already, but couldn't find similar file.

I don´t have access to the firmware so I have no skindump available. If you send me your full skin dumps I can help looking into it. Maybe I find something suitable.

**Comment by andy0172** [comment]
That would  be awesome, you can download it here:
Resources.zip
http://gofile.me/2mZkm/x63wzYn7e

Here is the current version:
https://ibb.co/jvvdYKQ

**Comment by olli991** [comment]
@andy0172 to me it looks like it could be `img_1755.png` in `skin1` or `img_1758.png` in `skin2`. Don´t know which skin you´re running. Did you already testet to replace this file with a transparent one?

The only other option would be `img_1393.png` (skin1), `img_1396.png` (skin2) but I tend more to the first option.

**Comment by jilleb** [comment]
Great work @olli991 !! 👍 👍

**Comment by andy0172** [comment]
Thank you @olli991 img1755 did the job and I didn't tried this before, but its dispalyed differently then yours, the name of the radio station is still in the background! Might be just a coding issue?
![63577065-E1D3-4B12-BF5C-C552D983BAF5](https://user-images.githubusercontent.com/54629567/79864609-fe8cbe80-83d9-11ea-9a39-68ce06e6243e.jpg)

**Comment by olli991** [comment]
@andy0172 did you deleted the image? Then this could happen. You need the replace the white image with a transparent one which have excatly the same dimensions. And somehow your second image now looks different to the first one... like it´s a complete other skin.. it´s even another display :D 

I see you´re running on german language maybe we can clear this the fast way in native language ;-)
You can contact me via Telegram t.me/Olli991 
I will document the conclusion here afterwards for the community.

**Comment by simonz1982** [comment]
I have a problem when I use this command: compress-mcf.py images.mcf images2.mcf .\extracted\ gives me the following error:

original-file incorrect magic!

or this:

File "compress-mcf.py", line 32
print 'original-file incorrect magic!'
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('original-file incorrect magic!')?

what does it mean?

**Comment by olli991** [comment]
You have to reference the phrase of the code to your actual filenames and existing folders. Did you do this or did you just copy this phrase from the instructions?

**Comment by simonz1982** [comment]
C:\Users\Simone\Desktop\splash\imagesmcf>python compress-mcf.py images.mcf images2.mcf C:\Users\Simone\Desktop\splash\imagesmcf\skin0
original-file incorrect magic!


In the folder skin0 there are all png file that i extracted. 
In the folder imagesmcf there is compress-mcf.py and orginal images.mcf file
Whre is the error? 
Thanks

**Comment by olli991** [comment]
Looks right to me ... kind of. Try by just drag and drop every entity into the cmd.. I do it this way so every path is correct and i don´t need to have all the scripts and files in the same directory.

**Comment by simonz1982** [comment]
Thanks for the support, but don't work

The error is: original-file incorrect magic! 

Why? Is orginal file images.mcf.
What is magic!

**Comment by jilleb** [comment]
That's the header of the file. It seems the file you're trying to open is either incorrect or can't be read.
What python version are you using? The compress script isn't yet converted to Python3

**Comment by simonz1982** [comment]
Hi,
the file imags.mcf, it's the same file I used to make the extract-mcf.py and it worked. how come it doesn't work with compresses? it's weird isn't it?
I'm using the latest version of python the 3.8

I can try a lower version.

**Comment by olli991** [comment]
> I'm using the latest version of python the 3.8
That is your problem. Like jille wrote the compression-script isn´t Python 3.8 ready.
Instead use 2.7 then it will work. I´m running everything on 2.7.

**Comment by simonz1982** [comment]
yeeeeees !!! now with 2.7 work ;-) my fist skin upload in my car

**Comment by olli991** [comment]
If you build something cool we can add it to the wiki and make it available to everyone here. Or did you just edited your skin with this info here to transparent backgrounds? :)

**Comment by simonz1982** [comment]
for now I am experimenting, when they are official I can publish them, where can I find yours and see them?

**Comment by olli991** [comment]
> 
> 
> for now I am experimenting, when they are official I can publish them, where can I find yours and see them?

Here in the [Wiki ](https://github.com/jilleb/mib2-toolbox/wiki) of the repo you can find it. Mine are the Seat modifications

**Comment by jilleb** [comment]
Great work! :-)

**Comment by OliverGTI** [comment]
> Great work!! :-)
> 
> I've done the same some time ago on MIB2.5:
> ![image](https://user-images.githubusercontent.com/8352494/79125081-d4b21700-7d9d-11ea-9ddf-bfd419689b1b.png)
> 
> I'll have a look if I can grant you rights so you can edit on the wiki @olli991

Hello how did they do that for the mib2.5. made they may help me thank you
