### ISSUE TITLE
First time user some questions

### ISSUE THREAD

**Issue by veso266** [jilleb/mib2-toolbox#59]
Hi there, I've got my WV Golf car with this kind of radio, as I did a lot of Mazda Infotaiment mods in the past I am familiar with embedded linuxes, so I wanted to start digging in to this

as for Ethernet Dongle I believe as long as your dongle has an ASIX Chipset in it like ASIX AX88772 like TP Link has, it should work fine as it is using ASIX kernel driver which linux kernel has bult in so I have this dongle: https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/global/network_adapters_usb_adapters/eu-4208

and I think it should work fine (didn't try it yet, as funny fact don't have any laptop that has Ethernet port so I have to figure out how will I connect my car to wifi :) eather using my Raspberry Pi with a battery pack as a gateway :smile: )

Now the questions, you didn't mention how to check on which model of a Radio I have, where can I check that, I only know its WV Golf but don't know what radio it has :smile: I already told someone to activate green menu for me so at least I have the menu (I love analogtuner option as it gives me so much control over the radio part)

![Screenshot_20200412-133654_Video Player](https://user-images.githubusercontent.com/6347325/79068274-efb15800-7cc5-11ea-88ab-b66f95455420.jpg)

you think you could send me analogtuner script so I can take a look at it before I start to play with my car?

Thanks

**Comment by olli991** [comment]
If I´m not completly wrong this is a MIB2 STD so this is not a High-Version and so on not supported in this toolbox. It should also be possible to get into it somehow but not with this toolbox, sadly.

**Comment by veso266** [comment]
but why?
are esd files not supported?

**Comment by vwjap** [comment]
Hasn’t got nav

**Comment by veso266** [comment]
OK so why do I need NAV for mib2-toolbox?

**Comment by vwjap** [comment]
Highs hav nav

**Comment by veso266** [comment]
Well I figured it myself (maybe you should update FAQ with this)

Because this Toolbox is using PersonalPOI as a way in: https://github.com/jilleb/mib2-toolbox/tree/master/PersonalPOI/Package/0/default
(still don't know if you could install this without PersonalPOI folder)

and my unit doesn't have navigation so I don't need/cannot have Personal POI (points of Interest) as this is navi thing and I don't have navi

my radio won't accept PersonalPOI package

**Comment by vwjap** [comment]
Also jilleb doesn’t know wether his scrips work on the STD? As I don’t think he has the hardware to test with,

**Comment by veso266** [comment]
now how would I calculate the checksum for metainfo2.txt file?
I read here: https://turbo-quattro.com/archive/index.php/t-19874.html
and here: https://turbo-quattro.com/archive/index.php/t-26835.html
and here:  https://forums.seatcupra.net/index.php?threads/uploading-speed-camera-pois-tail-of-woe-vw-pulled-the-update-site-again.444799/page-8#post-4911244

that checksum is sha1 so using openssl it should be easy: openssl dgst -sha1 metainfo2.txt

but you didn't calculate checksum when you edited your metainfo2.txt, you just skipped it
skipCheckSignatureAndVariant = "true"
skipMetaCRC = "true"
skipFileCopyCrc = "true"

let's try that and see what happens

**Comment by veso266** [comment]
damm it won't install, how can I sign metainfo2.txt file?
![20200412_214811](https://user-images.githubusercontent.com/6347325/79078373-3a53c400-7d08-11ea-92ae-6b92029ab3d7.jpg)

I tried to install this
https://transfer.sh/HoInz/staion_update.zip

I just reduces the default station_database file a bit and change a line in metainfo.txt
to: Source = "./Common/stl.1vw"

and now I need to resign metainfo.txt but don't know how?
How do you do that? (I think you just skip that somehow)

**Comment by jilleb** [comment]
This is indeed an MIB2 Standard. (see the STD in the menu? That's one of the ways you can tell ;-) )
I won't be supporting MIB2 STD.


Metainfo.txt is not something you can sign yourself, currently.

Closing this issue, because it's not my ambition to support MIB2STD.
