### ISSUE TITLE
[Question] Is there more information?

### ISSUE THREAD

**Issue by JanLoebel** [jilleb/mib2-toolbox#6]
Hi there,

first of all, thank you very much for your hard work :) 

I would like to get more into everything but couldn't find any good source. For example what does "String per 30 1966083" mean? In the end I think it's reading a string from a memory address but where can you find the information that the MU Version is at "1966083".
```
keyValue
    value   String per 30 1966083
    label   "MU Version"
```

And what about:

```
BIOSCtrl
       	value           int per 0 0x501848ff
       	label           "Byte 18 - startup screen"
       	entry		"not set" 0
        entry		"Family" 0c
        poll            1000
```

`value` is clear, but what does `poll` mean for example, is it a refresh of the value each 1000ms?

Is there any information source?

Thanks again,
Cheers

**Comment by jilleb** [comment]
See the example.esd in the GreenMenu folder. It has a lot of info.
