### ISSUE TITLE
Please read me...

### ISSUE THREAD

**Issue by Alejo2345i** [jilleb/mib2-toolbox#61]
Hi! Jilleb greetings from Ecuador. Firstly i wanted to say sorry to contact you by this way, but i didnt have any idea about how to do it. 
So i was looking around and i found your project (mib2-toolbox). I tought that this was a solution to my problem but i noticed that isnt. Let me tell you about my problem. 
I bought a VW jetta 2017 with a MIB2 radio part number 5K7 035 200D. That doesnt includes app connect. I have already contacted my car dealer agency to unlock it but here in Ecuador they dont have any idea about what is app connect... I searched for about 3 years for a solution on internet but there isnt as far as i know. So today i found your project and if there is a solution I will be glad to PAY you the amount that you want for unlocking app connect on my radio... Thanks, i will be waiting for your reply
![WhatsApp Image 2020-04-15 at 19 10 54 (1)](https://user-images.githubusercontent.com/63758098/79401106-c99de900-7f4d-11ea-9fa2-a1240a9d0f2d.jpeg)
![WhatsApp Image 2020-04-15 at 19 10 54 (2)](https://user-images.githubusercontent.com/63758098/79401108-ca367f80-7f4d-11ea-81eb-f997b44a4944.jpeg)
![WhatsApp Image 2020-04-15 at 19 10 54](https://user-images.githubusercontent.com/63758098/79401109-ca367f80-7f4d-11ea-83ae-d350ef64e2fe.jpeg)
![WhatsApp Image 2020-04-15 at 19 12 27](https://user-images.githubusercontent.com/63758098/79401110-cacf1600-7f4d-11ea-848c-502e6c96c3f7.jpeg)
![WhatsApp Image 2020-04-15 at 19 14 49](https://user-images.githubusercontent.com/63758098/79401112-cacf1600-7f4d-11ea-819d-2cc29b9a6127.jpeg)

**Comment by vwjap** [comment]
You need the part number to go to vw, they also need to fit a data USB port in, as its only got a power usb,

**Comment by vwjap** [comment]
5g0054830a is the part number

**Comment by Hamburgpriat** [comment]
I think you have to buy the Key. Aks VW eqcador https://www.volkswagen.com.ec/es.html

Acrivate Appconnect by ODB or Development is not possible.

**Comment by jilleb** [comment]
I cannot support unlocking of units on this board, I'm sorry.

**Comment by Alejo2345i** [comment]
Thanks Jilleb. But as i said here in Ecuador they dont have any idea about app connect or that kind of stuff. The only way to get it is buying a new car...  Have a nice day!
