### ISSUE TITLE
Add VIM Mode

### ISSUE THREAD

**Issue by OnSerious** [jilleb/mib2-toolbox#62]
Hi,

is it possible to add VIM Mode? 
I've seen a "developer" Menu from someone where you can pick the VIM Speed for yourself.

There is a slider which can go from 0 to 255 and when applying for example 180 and you go over it, you get the "no video while driving" message

this will be a cool feature

**Comment by andy0172** [comment]
For now you can only copy a patched Storage1.raw file to the unit. The slide within MIB2 Toolbox will be a very cool feature!

**Comment by jilleb** [comment]
I can look into this.

**Comment by CaneTLOTW** [comment]
> 
> 
> For now you can only copy a patched Storage1.raw file to the unit. The slide within MIB2 Toolbox will be a very cool feature!

I tried that, but the changes are not applied back to the adaption channels.

**Comment by huddx01** [comment]
CaneTLOTW, did you try this script from the experimental branch?

https://github.com/jilleb/mib2-toolbox/blob/experimental/Phone/Apps/0/default/set_VIM.sh

**Comment by jilleb** [comment]
VIM is in there, in a rudimentary way. Will possibly improve it sooner or later.
