### ISSUE TITLE
Android Auto Music in "Home" and "AID"

### ISSUE THREAD

**Issue by Hamburgpriat** [jilleb/mib2-toolbox#63]
Hi,

is it possible to view Android Auto music Infos in "Home"and "AID" ?
You can Code that?

Best regards,

![2020-04-20 16_41_57-Window](https://user-images.githubusercontent.com/63672262/79764915-44884a80-8326-11ea-90cb-4aebbc4f8b88.png)
![2020-04-20 16_42_23-Window](https://user-images.githubusercontent.com/63672262/79764918-4520e100-8326-11ea-8acc-803eb9b040d6.png)

**Comment by olli991** [comment]
It´s also not possible for iOS. It isn`t even implemented in the car so you can´t just activate it somewhere. The possibility to show this informations (for iOS CarPlay) came with iOS 13 which itself came out in september 2019. I don´t know about AA but the function, most likely, wasn´t available when the MIB2 was developed. The carmanufacteur have to implement code in the AA or CarPlay software on the units etc. to make this work. Theoretically they can bring this as a Update but I don´t think so for the MIB2. Maybe the MIB3 can do it and we can bring it down somehow...

**Comment by Hamburgpriat** [comment]
Yep. Possible on Mib3. Also possible in Audi Mib2...

**Comment by jilleb** [comment]
Audi AID is much different than the VW/Seat. I've spent a lot of time looking into displaying track info here, but currently it's not possible.
