### ISSUE TITLE
Climate Info overlay on mib 

### ISSUE THREAD

**Issue by Hamburgpriat** [jilleb/mib2-toolbox#64]
Hi,
At the superb mib 2.5 you get an Information overlay if you change temp, heated seats and alls other climate infos if you set a new temp... On the Navigation.
It is possible to activate, or is it a newer Firmware? I get no overlay about change climate settings on my karoq mib...

**Comment by vwjap** [comment]
How would you activate it without the menu button on the air control unit?

**Comment by andy0172** [comment]
Its also in octavia and realted to the software of the air condition control unit. I thin you need at least 2xxx version on it.

**Comment by Hamburgpriat** [comment]
Ok little correction..
I can see the temp. But no seat heat info.. But not so importent.. Luxus problem

**Comment by andy0172** [comment]
For seat info you need to code stearing wheel heater even when you dont have it, then seat heating will be displayed as well.

**Comment by simonz1982** [comment]
I have a problem when I use this command: compress-mcf.py images.mcf images2.mcf .\extracted\ gives me the following error:

original-file incorrect magic!

or this:

File "compress-mcf.py", line 32
print 'original-file incorrect magic!'
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('original-file incorrect magic!')?

what does it mean?

**Comment by Hamburgpriat** [comment]
Its working. Thanks.
