### ISSUE TITLE
Start Installation Button Greyed Out

### ISSUE THREAD

**Issue by bencasse** [jilleb/mib2-toolbox#65]
Hi, Amazing work on this.  When I try to install it onto my unit, the update is recognised fine, however the start installation button is greyed out and cannot be pressed.  Please see the image attached.  Is there any way to resolve this?
![IMG_1098](https://user-images.githubusercontent.com/24221395/80454069-8f850c00-897d-11ea-81b1-2906c4975d48.jpg)

**Comment by Hamburgpriat** [comment]
Hi,

i think thats the wrong Menu. Holt Menu for few seconds. And than you have the  Update Button.
Or. Can you select SD Card above? Sorry i dont have an VW.

**Comment by bencasse** [comment]
Hi, its definitely the update menu.  Accessed by holding menu, selecting update, it then asks the source (SD Card) it then reads the card and shows MIB Toolkit 2.5, and on selecting that the screen above is shown with the start button greyed out.

**Comment by Hamburgpriat** [comment]
Ok. Did you Activate the Dev. Menu in 5F ?
*Developer mode enabled on module 5F (you need VCDS/OBD11/VCP for this!)*

**Comment by bencasse** [comment]
Yes, developer mode is active and I can access the green engineering menu.  Just can't start installation of the toolkit

**Comment by matix131991** [comment]
Thats maybe so easy but do you try click something in the right side PersonalPOI button?

**Comment by bencasse** [comment]
Yes I did, here are the screens that show when you click in.  But the start button doesn't seem to be enabled at any level.
![IMG_1099](https://user-images.githubusercontent.com/24221395/80476085-00d4b700-899e-11ea-9129-e646cb43e12a.jpg)
![IMG_1100](https://user-images.githubusercontent.com/24221395/80476088-029e7a80-899e-11ea-8a9d-673ad5a5220d.jpg)
![IMG_1101](https://user-images.githubusercontent.com/24221395/80476094-04683e00-899e-11ea-8faf-89667b2eef88.jpg)
![IMG_1102](https://user-images.githubusercontent.com/24221395/80476097-06320180-899e-11ea-9737-36cc0bbd576d.jpg)

I am wondering what the "I" next to them means

**Comment by Hamburgpriat** [comment]
The toolkit is on sd and only one sd card is inside? (FAt32, All Files direct into the SD) 
...Strange. On Skoda you have only put install, SD Card and Go...

**Comment by jilleb** [comment]
Do you have any error codes, maybe from a previous firmware installation?

Remove them first.

**Comment by bencasse** [comment]
I did have some errors, cleared them and the button came active.  Thanks so much for your help!  The toolbox worked perfectly, I was able to retrieve the password hashes from the unit that I have been trying to get out for ages.  Do you know the hash algorithm that they use?

**Comment by grzesqxx** [comment]
how did you menage that ? I mean clear errors ?
