### ISSUE TITLE
[REQUEST] Unicode Support/Hack

### ISSUE THREAD

**Issue by airsky98** [jilleb/mib2-toolbox#67]
I'm from Asia, currently using mib 2.5 (5NA035045E) , equipped with EU firmware H29.319.75_HIGH2GP_EU
MHI2_ER_VWG13_P4521_1

I discovered that when streaming Chinese songs via Bluetooth. The characters don't show up correctly while the speedometer is able to show it correctly. 

By switching to units from china definitely will fix the problem and I heard that even people from Hong Kong faced the same issue where Chinese characters are not showing up in their MIB 2.5 

Just wondering this issue can be fixed by the toolbox in the future? or it's easier to flash to CN firmware but I would like to keep the original nav maps? 

I did some research, it seems like it involves flashing EEPROM, is it possible via software or requires soldering skills which is too troublesome for sure.  

Note : If it's connected via car play or android auto, Chinese characters show up fine.

**Comment by jilleb** [comment]
Hi! 

Good question. I know there are some specific linguistic things inside the unit. Maybe it's a font thing. If that's the case, fonts are very easy to replace, but then we would need the right one. I know this is the case with Arabic language setting on the unit, not sure about China. Let's try! 


If you have China firmware, you can mount app.img as a qnx6 volume in Debian, and find the fonts inside (somewhere in /net/mmx/mnt/app/eso/hmi/lsd/Resources)

**Comment by airsky98** [comment]
ok, thanks for the tips. let me try to get it later from people in china. 👍

**Comment by airsky98** [comment]
I have gotten the flash version 0841

https://www.dropbox.com/s/wmmwmeocosl5e97/3GD035048_0841%E8%BD%AF%E4%BB%B6.rar?dl=0

here's the link but I'm not familiar with Linux so I have trouble mounting it. I will continue to try. 

Please help me to take a look (if possible, tell me the commands as well so that i can explore other files)

**Comment by chopinwong01** [comment]
> I have gotten the flash version 0841
> 
> https://www.dropbox.com/sh/ca3ctu7qt2b4c7x/AADbFRIw77EOeOQ1UeRaAxX-a?dl=0
> 
> here's the link with a song name in unicode I'm not familiar with Linux so I have trouble mounting it. I will continue to try.
> 
> Please help me to take a look (if possible, tell me the commands as well so that i can explore other files)

Hi,

I had a look into the system on my Australian Golf 7.5 with 'MIB 2.5 High' and can confirm that the fonts contain no Chinese characters. 
I will try to mount app.img while this may need some time as my computer runs Windows and WSL by default doesn't support qnx filesystems.

Will keep you posted.

**Comment by chopinwong01** [comment]
There are more differences than just fonts. I tried to add Chinese font **_ZYHei_GB18030_c.ttf_** and change the _**Font.properties**_ and there is no observable changes. 
I have no plan to touch the binaries but I do want to import the whole skin into my 'MIB2.5High'. The Chinese firmware contains a _**skin3**_  and this is not on my device.

**Comment by chopinwong01** [comment]
> There are more differences than just fonts. I added Chinese font **_ZYHei_GB18030_c.ttf_** and edited the _**Font.properties**_ which results in no observable changes. I have no plan to touch the binaries but I do want to import the whole skin into my 'MIB2.5High'. The Chinese firmware contains a _**skin3**_ and this is not on my device.

okay. not working.

**Comment by olli991** [comment]
Closed for inactivity

**Comment by chopinwong01** [comment]
> > There are more differences than just fonts. I added Chinese font **_ZYHei_GB18030_c.ttf_** and edited the _**Font.properties**_ which results in no observable changes. I have no plan to touch the binaries but I do want to import the whole skin into my 'MIB2.5High'. The Chinese firmware contains a _**skin3**_ and this is not on my device.
> 
> okay. not working.

Finally, I got some time and tried again... while I don't understand how the _**Font.properties**_ works, CJK characters can be displayed by directly replacing the fonts as in the names.
In my unit, replacing the fonts with  **_ZYHei_GB18030_c.ttf_** found in your firmware _only partially worked_ as the plan, non-bold numbers are now squares just like the CJK characters old fonts.

In short, it works, and probably in 2 ways: 

1.  change the _**Font.properties**_
2.  create/find a new font containing all characters...

**Comment by chopinwong01** [comment]
> > > There are more differences than just fonts. I added Chinese font **_ZYHei_GB18030_c.ttf_** and edited the _**Font.properties**_ which results in no observable changes. I have no plan to touch the binaries but I do want to import the whole skin into my 'MIB2.5High'. The Chinese firmware contains a _**skin3**_ and this is not on my device.
> > 
> > 
> > okay. not working.
> 
> Finally, I got some time and tried again... while I don't understand how the _**Font.properties**_ works, CJK characters can be displayed by directly replacing the fonts as in the names. In my unit, replacing the fonts with **_ZYHei_GB18030_c.ttf_** found in your firmware _only partially worked_ as the plan, non-bold numbers are now squares just like the CJK characters old fonts.
> 
> In short, it works, and probably in 2 ways:
> 
> 1. change the _**Font.properties**_
> 2. create/find a new font containing all characters...
> 
> BTW, it is /mnt/app/eso/hmi/lsd/Resources/skin**_[whatever number]_**/Fonts/



> I have gotten the flash version 0841
> 
> https://www.dropbox.com/sh/ca3ctu7qt2b4c7x/AADbFRIw77EOeOQ1UeRaAxX-a?dl=0
> 
> here's the link with a song name in unicode I'm not familiar with Linux so I have trouble mounting it. I will continue to try.
> 
> Please help me to take a look (if possible, tell me the commands as well so that i can explore other files)

I tried merging fonts with fontForge. it works now.

**Comment by happilyxyq** [comment]
> > > > There are more differences than just fonts. I added Chinese font **_ZYHei_GB18030_c.ttf_** and edited the _**Font.properties**_ which results in no observable changes. I have no plan to touch the binaries but I do want to import the whole skin into my 'MIB2.5High'. The Chinese firmware contains a _**skin3**_ and this is not on my device.
> > > 
> > > 
> > > okay. not working.
> > 
> > 
> > Finally, I got some time and tried again... while I don't understand how the _**Font.properties**_ works, CJK characters can be displayed by directly replacing the fonts as in the names. In my unit, replacing the fonts with **_ZYHei_GB18030_c.ttf_** found in your firmware _only partially worked_ as the plan, non-bold numbers are now squares just like the CJK characters old fonts.
> > In short, it works, and probably in 2 ways:
> > 
> > 1. change the _**Font.properties**_
> > 2. create/find a new font containing all characters...
> > 
> > BTW, it is /mnt/app/eso/hmi/lsd/Resources/skin**_[whatever number]_**/Fonts/
> 
> > I have gotten the flash version 0841
> > https://www.dropbox.com/sh/ca3ctu7qt2b4c7x/AADbFRIw77EOeOQ1UeRaAxX-a?dl=0
> > here's the link with a song name in unicode I'm not familiar with Linux so I have trouble mounting it. I will continue to try.
> > Please help me to take a look (if possible, tell me the commands as well so that i can explore other files)
> 
> I tried merging fonts with fontForge. it works now.

Hi, how does it work? I am trying now, but I am worried about damaging the unit system.
