### ISSUE TITLE
Doubt about new features

### ISSUE THREAD

**Issue by aigortt** [jilleb/mib2-toolbox#68]
Good afternoon, I would like to ask you about a function that I have seen in your code. I am not an expert but I would like to know if this could give access to the unit's online services such as google earth.

Greetings

script
   value    sys 1 0x0100 "/eso/bin/PhoneCustomer/default/nosslcheck.sh"
   label    "Disable Online service SSL checks"

script
   value    sys 1 0x0100 "/eso/bin/PhoneCustomer/default/removenosslcheck.sh"
   label    "Re-enable online service SSL checks"

**Comment by jilleb** [comment]
This allows you to host your own online services backend.

You need to build your own webservice, and change the hosts file so the mib will use the right IP, and then these flags allow connections.

**Comment by aigortt** [comment]
okay thank you very much. Do you know if there is a server already created? That subject escapes my knowledge

**Comment by jilleb** [comment]
There are several that I know of, but all of them are private.

**Comment by qba667** [comment]
@jilleb great to know! Is there any API documentation? Maybe we can run opens source and free one?

**Comment by jilleb** [comment]
There is no official documentation...
Several people I know are running a server, based on research of the  OLS Jar files on  the Mib and captures of data during an online session.

I've been in doubt about releasing a public open source server, but I fear one of the following or all will happen:

- people will try to take advantage of it and sell online services for high prices 
- any free/freemium traffic API will be flooded with requests, which will either lead to higher cost or denial of using the services
- VW lawyers come knocking at my door.

**Comment by qba667** [comment]
@jilleb good points, you are fully right. Probably most serious is is the legal aspect. Would you mind if we have conversation about work aredy made in this area? Doing same work twice is a little bit painful. I will send you a email on Gmail (linked to got commits). Thanks a lot!

**Comment by qba667** [comment]
@andrewleech please let me know if you got my email.

**Comment by camarao69** [comment]
> @jilleb good points, you are fully right. Probably most serious is is the legal aspect. Would you mind if we have conversation about work aredy made in this area? Doing same work twice is a little bit painful. I will send you a email on Gmail (linked to got commits). Thanks a lot!

Hello  , are you kind enough to help me with this ? I would really like to enable traffic info and i think this would be the only way do it, but i do not have the knowledge to create a server for this , can somebody share a server that i can use please?

@qba667
@andrewleech

**Comment by ANMOSIN** [comment]
it's a good idea, but the author is right that the server will be overloaded at one time I used online, but it's not worth the money spent when there is a carplay.

**Comment by camarao69** [comment]
> it's a good idea, but the author is right that the server will be overloaded at one time I used online, but it's not worth the money spent when there is a carplay.

I have some cons about that, 
1-sometimes the connection with the phone is lost.
2-you cant see nav in the virtual cockpit .

I don´t mind paying a fee to have it , as i have a retrofitted unit i can´t have online services , ther is no tmc either in my country.
I don't know any owner of a private server that i can contact.

**Comment by jilleb** [comment]
I am skeptical when it comes to "I am willing to pay for that", seeing the amount of donations my projects have received over the years 😂😂

Maybe it would be a good idea to just make an open server platform, so people can rollout their own servers. But honestly, it's not worth the time and effort to develop and maintain such a thing.

**Comment by ANMOSIN** [comment]
It costs 300 euros I can give a person's contact from you a laptop and a d link and diagnostics.

**Comment by camarao69** [comment]
I don't know the kind work it is needed to build the server so i can't comment on that ,
but carnet , Audi connect, Skoda connect i think is 18€ a month or 200€ a year so something in those values would be fair.

**Comment by camarao69** [comment]
> It costs 300 euros I can give a person's contact from you a laptop and a d link and diagnostics.

Do you mean he can enable the official Skoda connect with the retrofitted unit ?

**Comment by ANMOSIN** [comment]
Yes

**Comment by camarao69** [comment]
It would still be a fee next correct ?

**Comment by ANMOSIN** [comment]
it is better to ask the person who does it, but it will not be fully functional

**Comment by olli991** [comment]
There are options for around 150 Euro / year to make carnet available. You could built it yourself but I am also on that pre built service and run it on seat. Where you even couldn't buy carnet at all ;-) so it's possible.

**Comment by ANMOSIN** [comment]
150 is also expensive, I don't need more than 50.

**Comment by camarao69** [comment]
From 300 we are now on 50 lol , how can you pass me those contacts?
i have searched everywhere always finding a dead end.

**Comment by olli991** [comment]
Audi-mib.bg could help you. But only for money

**Comment by ANMOSIN** [comment]
Мне не надо

**Comment by camarao69** [comment]
> Audi-mib.bg could help you. But only for money

i came across that website once but i thought the features wore only for audi , so they can do it for skoda ?
is that the one you talked about , are you using it ?

**Comment by olli991** [comment]
Yes I use that. It's so listed that in can do Skoda and stuff

**Comment by camarao69** [comment]
thank you olli991 do i need to have any special tool ?
I have obdeleven and vas5054

**Comment by olli991** [comment]
An SD card the rest should be possible via toolbox or just via coding injection via sd card. I don't know hoe he does it now. Just ask him
