### ISSUE TITLE
Why can't PQ platforms be used[REQUEST] 

### ISSUE THREAD

**Issue by onemiless** [jilleb/mib2-toolbox#69]

**Comment by mattcabb** [comment]
AFAIK infotainment systems in PQ platform cars are not MIB2High based, but MIB2Std based. User interface looks the same but there are some crucial differences "under the hood".

**Comment by jilleb** [comment]
Indeed. MIB2PQ is a different platform, and since I don't have a suitable test/development environment to investigate it, it's not supported.
