### ISSUE TITLE
[NOT A BUG] Compostion Media

### ISSUE THREAD

**Issue by Leproide** [jilleb/mib2-toolbox#7]
Hi!
in first, thank you for the amazing work 👍 
In future you can add Compostion Media support? Android Auto patch is a very useful feature.

**Comment by jilleb** [comment]
Thanks :-)

I don't have any access to a Composition Media to try and develop/test a solution. The MIB2High toolbox is the result of a lot of research about MIB2H vulnerabilities and possibilities, I am completely in the dark when it comes to Composition Media

**Comment by segadora** [comment]
@jilleb would you work on it if one were sent to you or provided access to?

**Comment by jilleb** [comment]
@segadora, Yes.

**Comment by langers2k** [comment]
@jilleb - I have a Skoda Bolero (Composition Media) that I can probably send you. I tried emailing and got no response, is it something you're interested in?
