### ISSUE TITLE
Merge with MIB1-toolbox

### ISSUE THREAD

**Issue by jilleb** [jilleb/mib2-toolbox#70]
Take the metainfo from Navi updates:

```
[common]
vendor = "ESO"
variant = "FMU-H-*-*-*"
variant2 = "FM2-*-*-*-*"
variant3 = "QC2-*-*-*-*"
variant4 = "FMQ-*-*-*-*"
region = "Europe"
MetafileChecksum = "fcbb47bc9cea64a52c00ac305517f158a65f25bb"

[common_Release_1]
variant = "FMU-H-*-*-*"
region = "Europe"
name = "MIB1 navigation database"
path = "./Mib1"

[common_Release_2]
variant = "FM2-*-*-*-*"
variant2 = "QC2-*-*-*-*"
variant3 = "FMQ-*-*-*-*"
region = "Europe"
name = "MIB2 navigation database"
path = "./Mib2"

[Signature]
signature1 = "321c41897fc2e8605c9ff2736bf510c1"
signature2 = "c916568df82ec4026a4a5ec721384286"
signature3 = "05538004273506a4278a266a8c6827f7"
signature4 = "e90124b0c585b6807f197881c18a229e"
signature5 = "afd011eaae35da39cac02951ab3e68a8"
signature6 = "f5b1ee18fcd9774d9dbab95b3a74c03e"
signature7 = "19c40ecb3010c2e8f98cbb9b8b9ec939"
signature8 = "97b8ce0e139462cdf6b574792b5f0d93"
```

And merge folders, files.
Also needs script updates for both, and a lot of testing to make sure all scripts/installs are still working correctly.

**Comment by jilleb** [comment]
All stuff regarding this merger can be found in the experimental branch.

**Comment by marijngiesen** [comment]
Would be cool to build some kind of test suite for all scripts. When I have more time, I'll try to come up with something.

**Comment by jilleb** [comment]
Sounds like a great idea 😎

**Comment by jilleb** [comment]
Test install on MIB1: OK
Test install on MIB2: NOK. Something is wrong with the paths, error 31 during installation.

**Comment by jilleb** [comment]
Update: let's not do this... Causes too much problems.

**Comment by olli991** [comment]
@jilleb Merge with new install method a thing? We actually already have Mib1 und Mib2 folders and according metafiles in the new method.

**Comment by jilleb** [comment]
I was having a lot of issues with paths, variables and such... And decided not to put my time into fixing those and keeping MIB1 stuff up to date. But it's worth to try with the new method! The MIB1 actually has a very simplified SWDL, which has a metainfo path traversal but that was fixed in Mib2 😁

**Comment by olli991** [comment]
Hmm i have literally nothing to test if it works, was just an idea because nav update is for mib1 and mib2 so one script already prepared.

**Comment by jilleb** [comment]
Indeed. I no longer own a car with MIB1, so testing would be hard 😅

**Comment by andrewleech** [comment]
Also, my in-test script with the name of the installer and default install targets fixed doesn't have separate mib1 & mib2 folders...
