### ISSUE TITLE
[REQUEST] is it possible to create own skoda connect apps?

### ISSUE THREAD

**Issue by Hamburgpriat** [jilleb/mib2-toolbox#71]
It it possible to create own apps nativ on mib2? Skoda connect has news, weather, Traffic... It it possible to create own apps like musik app, spotify api...?

**Comment by jilleb** [comment]
Skoda or VW has not released an SDK. However, it should be possible to be able to make your own webservices that offer data to the unit. This would be something server-side, so no really mib2-toolbox related.
