### ISSUE TITLE
[REQUEST] Enabling Dev Mode from shell

### ISSUE THREAD

**Issue by andy0172** [jilleb/mib2-toolbox#73]
When installing the Toolbox manually from shell, is there a way to enable Dev mode directly with a command? That would be handy. Thanks

**Comment by jilleb** [comment]
yes, there is.
```
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production
/net/mmx/eso/bin/dumb_persistence_writer -P 0 3221356557 01
```

**Comment by andy0172** [comment]
Perfect, thank you!

**Comment by florin1974** [comment]
hello
i try to enable dev mode from console with this script and i have an error:
ksh: export: -P: not identifier

i have the firmware version: MHI2_ER_AU57X_P3634
MU SOFTWARE: 0910
please help me to activare dev menu.
thank you

**Comment by jilleb** [comment]
check if the given paths exists

**Comment by florin1974** [comment]
![Annotation 2020-05-20 172311](https://user-images.githubusercontent.com/64842581/82457923-b6d38280-9abe-11ea-8fa4-2d0c9beda4f2.png)

**Comment by andy0172** [comment]
I have this error:

/ > export IPL_CONFIG_DIR=/etc/eso/production
/ > /net/mmx/eso/bin/dumb_persistence_writer -P 0 3221356557 01
ksh: /net/mmx/eso/bin/dumb_persistence_writer: cannot execute - No such file or directory

**Comment by florin1974** [comment]
hello Jilleb
I am look into etc director and not heave ESO directory.
in this case is possible to activate dev menu?
please help me if you know

thank you

**Comment by hxigor** [comment]
I'm getting this error:
`/net/mmx/mnt/app/eso/bin/dumb_persistence_writer AgentBase: error on config-file. Aborting.: JSONParser: Given file not found: /etc/eso/production/framework.json (in d:\build-rel_mib2_sop1_integration-framework\qnx-arm-qcc-rcc2_high-release_2\src_root\framework\src\comm\AgentBase.cxx:528)
Abort was called in process 593947 / thread 1 !
Thread name: "init/main thread"
Location: src\comm\Error.cxx:94, fatal()
Current error context:
Error (ID 0):
        JSONParser: Given file not found: /etc/eso/production/framework.json
        Location: src\util\config\Provider.cxx:210

Reason: "AgentBase: error on config-file. Aborting. in d:\build-rel_mib2_sop1_integration-framework\qnx-arm-qcc-rcc2_high-release_2\src_root\framework\src\comm\AgentBase.cxx:528"
[mib_dumper] dumping core (pid=593947-dumb_persistence_writer)
dumping to /HBpersistence/core/dumb_persistence_writer.core.gz
thread 1.flags is 0x1
thread 1 is was SIGNALLED
thread 1.why is 0x1
thread 2.flags is 0x1
thread 2.why is 0
ldd mapinfos:
`

**Comment by jilleb** [comment]
find one of these binaries on your unit:

```pc```
or
```dumb_persistence_writer``` 

I don't know the paths for each individual firmware version or brand, so you will have to do some searching yourself to get the right paths.


and it could help to run the command from MMX:
```
on -f mmx  /net/mmx/eso/bin/dumb_persistence_writer -P 0 3221356557 01
```

**Comment by andy0172** [comment]
At least for Skoda I figured it out, the lib directory is different:
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production
on -f mmx  /net/mmx/eso/bin/dumb_persistence_writer -P 0 3221356557 01


will do the job

**Comment by jilleb** [comment]
I'll add this to the readme. Thanks!

**Comment by jilleb** [comment]
Updated in the readme of experimental branch:
bfa4841d68a12f770df51c8d2b81698be95970dd

**Comment by CaneTLOTW** [comment]
Tried the command on my MIB2.5 Skoda Columbus.
It is not working.
