### ISSUE TITLE
[REQUEST] Chinese gold theme and composition media

### ISSUE THREAD

**Issue by Leproide** [jilleb/mib2-toolbox#74]
Hi!
Can you add the Chinese gold skin?
https://youtu.be/y7zt3CrM9_4
This theme exist in the new mib
![nnEZsGC](https://user-images.githubusercontent.com/8448713/82220315-bbf9cb80-991e-11ea-9cac-6f3b6b8351ae.jpg)

You are working for supporting the composition media unit?

Have a nice day :)

**Comment by vwjap** [comment]
If you enable developer mode, then go to skins, it’s sometimes under that (sport skin, or high skin, I can’t remember which one as my car only has one skin)

**Comment by Leproide** [comment]
Unfortunately this skin is only for asian market, in EU market not exist :(

**Comment by jilleb** [comment]
But if someone has the skin files for this on MIB2.5, please please please share it.
If possible, please share the entire Resources folder, which also contains all the viewhandler stuff.

**Comment by airsky98** [comment]
Do you know how to mount the image?

https://www.dropbox.com/s/wmmwmeocosl5e97/3GD035048_0841%E8%BD%AF%E4%BB%B6.rar?dl=0

I have the whole software for MIB2.5 China market. However, it’s too complicated for me to mount the image. ☹
Would like to extract the language fonts as well.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jilleb** [comment]
You can mount app.img by:

```
mount -o loop -t qnx6 app.img /mnt/tmp
```

**Comment by jilleb** [comment]
![DSC_2462-01](https://user-images.githubusercontent.com/8352494/82411771-af868780-9a72-11ea-8fa7-1d2812e91307.jpeg)

So, it's working.
The bad news is... It cannot be retofitted directly into each firmware. 

The good news: it's working, but.you are looking at the Chinese software running on my EU unit. The dots theme is different from the non-dots by having specific graphics and views that aren't there in the EU version. Retofitting would mean we have to edit compiled java files, I don't see that happening any time soon.

**Comment by Leproide** [comment]
The chinese firmware have only chinese language?
This is only for pro or work on the composition media? I think the package is specific and are not a single package with all the firmware for all the version... 
I tried to mount the chinese firmware on windows with wsl running debian on windows but not recognize the fs, i think i need a full vm or a physical machine, the windows subsystem is a s**t

**Comment by jilleb** [comment]
> The chinese firmware have only chinese language?

No, as you can see in the screenshot, there's also english.

> This is only for pro or work on the composition media? I think the package is specific and are not a single package with all the firmware for all the version...

This entire toolbox is about MIB HIGH.

**Comment by Leproide** [comment]
Yes, the toolbox i know are only for the mib high, i talk about the chinese firmware :)

**Comment by airsky98** [comment]
@jilleb How easy is it to flash to chinese firmware? will the map from EU still works? I'm SG based but using EU headunit i guess

**Comment by jilleb** [comment]
> @jilleb How easy is it to flash to chinese firmware? will the map from EU still works? I'm SG based but using EU headunit i guess

Maps are not working on my converted unit. So far I haven't been able to get it working with EU maps either. 

Installation is pretty easy. Make sure the eeprom has the right values for variant and train.

**Comment by jilleb** [comment]
Leaving this for now.

**Comment by AndrexOfficial** [comment]
@jilleb To install this firmware to your EU Discover Pro unit did you write the EEPROM to update the train version or did you changed the supported train versions in metainfo2.txt file?
