### ISSUE TITLE
[REQUEST] Android Auto custom apps patch

### ISSUE THREAD

**Issue by Steppdroid** [jilleb/mib2-toolbox#75]
Hi, Any chance for ONLY Android Auto custom apps patch on MIB2 STD ?
Thank u!

**Comment by jilleb** [comment]
No, I don't have an MIB2Std platform to work on, so it's up to someone who does have it, and has the time to investigate it.

But if anyone knows how to gain access to the filesystem, he should look for the gal.conf.
