### ISSUE TITLE
[REQUEST] MHI2_ER_AUG22_S2148 UPDATE TO P2156 PROBLEM

### ISSUE THREAD

**Issue by kamilt86** [jilleb/mib2-toolbox#77]
HI I AM LOOKING FOR SOLUTION , HOW TO UPDATE FIRMWARE OF AUDI Q7 4M FROM S2148 TO P2156.
I CHANGED IN EEPROM SETTINGS, NOW SYSTEM SEE SOFTWARE LIKE P2148, AND NOW I CAN UPDATE SYSTEM BECAUSE OF SUPPORTED TRAIN LIST P2148 EXISTS. 

BUT UNFORTUNATELLY NOT POSSIBLE TO UPDATE TO P2156.

"PARSING OF RELEASE  INFO FAILED"
FILE:
LINE: 7

PLEASE ANY ADVICE HOW TO UPDATE THIS 4M TO SOMETING NORMAL SOFTWARE :)
THX

**Comment by jilleb** [comment]
No caps-lock needed here 😉 
It is very plausible that the newer release has an updated metainfo key. Not sure about that, I've had no similar issues.

Since this is not a Toolbox issue, I will close it, to prevent this place from becoming a big chaotic forum for everyone with MIB issues.

**Comment by kamilt86** [comment]
thx Jilleb for answer me, at start car had:
s2148 software.
![image](https://user-images.githubusercontent.com/61435872/83075260-d5fc8200-a073-11ea-997f-8dd9b8313beb.png)

after i changed in eeprom to get p2148 :
![image](https://user-images.githubusercontent.com/61435872/83075347-f88e9b00-a073-11ea-9ecb-201eafda853b.png)

and try to update to k2156 because support train: SupportedTrains = "MHI2_ER_AUG22_P1056*,MHI2_ER_AUG22_P1064*,MHI2_ER_AUG22_P2116*,MHI2_ER_AUG22_P2133*,MHI2_ER_AUG22_K2140*,MHI2_ER_AUG22_P2148*,MHI2_ER_AUG22_K2150*,MHI2_ER_AUG22_K2152*,MHI2_ER_AUG22_K2154*,MHI2_ER_AUG22_K2155*,MHI2_ER_AUG22_K2156*

but got error like this 

![image](https://user-images.githubusercontent.com/61435872/83075454-2b389380-a074-11ea-9bdb-dd22476ba2c6.png)

don't know why get this error, if trains now is supported.

thx for help

**Comment by jilleb** [comment]
But the train was no supported for a reason, probably because the metainfo key has changed
