### ISSUE TITLE
[BUG] MIB2 High - Stuck in Seat Logo

### ISSUE THREAD

**Issue by seb375** [jilleb/mib2-toolbox#78]
Hello,
I’m from France and I have a MIB2 HIGH
![8CE229E7-F192-4B94-BDB1-B5DF9BDCC00C](https://user-images.githubusercontent.com/66327023/83576427-12c3ef80-a532-11ea-85ba-6fa072d062eb.jpeg)
(I guess).
It’s on my Seat Cupra 2015 and it has the navigation pro with a hard drive.
I don’t have CarPlay and it has Mirror Link inside.
So I went to see a guy who have a shop in Switzerland, and he cannot update my MIB2.
He tried to upgrade my MIB2 with this MHI2_ER_SEG11_P4708, but after the reboot and after one hour wait, it gets stuck on the Seat Logo and nothing works even if you press the buttons.
So I need some help with this, (If you can guys) because, he’s saying that my MIB2 is almost dead and I’m afraid I have to pay for one new.
Thank you for you help guys !
Greetings from France :)

**Comment by jilleb** [comment]
Hi :-) Thanks for your message, but this github is not meant for MIB troubleshooting... 
I'll close this topic.

One thing you can try, is do a custom SWDL from the developer menu, and select all items to do a full update.
