### ISSUE TITLE
[BUG] Script not found 

### ISSUE THREAD

**Issue by grzesqxx** [jilleb/mib2-toolbox#79]
Hello, 

After installation can not run any script. 
Error looks like: https://ibb.co/4VgYSVv https://ibb.co/3CchdGg

MU version: 0687

Is means that, installation had found error ? The scripts should be loaded to unit ?

Regards

**Comment by olli991** [comment]
Just restart the unit and run the import scripts button again.

**Comment by grzesqxx** [comment]
No changes. 

When yesterday tried to install toolbox, had a error (can not remember part of text, but there had were two buttons - "again" or "cancel" - something like that : https://github.com/jilleb/mib2-toolbox/issues/27 ). And the update MQB Coding Toolbox 2.7 is empty: https://ibb.co/S3v6SWd. Tried to update it with SD card one more time, but unit could not start it (button was unactived). Today entered to SWDL and the option was active. The "second" MQB Coding Toolbox 2.7 is not empty (POI's are visible - https://ibb.co/CvLTqPs)

**Comment by jilleb** [comment]
Keep on trying. After install, Run the script that imports new scripts.

The copy_phone_customer.sh script is already on the unit, so this error should never occur, unless... your unit has been modified by someone. Some companies like APG remove stuff from the green menu.

**Comment by grzesqxx** [comment]
Is any way to put that script into The unit ? My unit is already hacked so i looking for The way without software update. 

Thanks Jilleb

**Comment by jilleb** [comment]
Yes, check the manual install in the readme. On a hacked unit, I cannot guarantee it's working, because sometimes they just mess things up 😅😅
