### ISSUE TITLE
[REQUEST] Support Skoda Kodiaq

### ISSUE THREAD

**Issue by fon1105** [jilleb/mib2-toolbox#81]
Do you have tool(python files) for Skoda?

Can my Skoda Kodiaq support this toolbox?
S/W MU Version: 0468
Part number: 5Q0035840C
S/W Version: H29.319.29.3_STD2Plus_EU

**Comment by jilleb** [comment]
It's supported when it has a MIB2 High.

**Comment by fon1105** [comment]
This is my detailed version: MST2_EU_SK_ZR_P0468T. It looks like a MIB2 Standard version. So it will not be supported by the tool?
