### ISSUE TITLE
Only D-Link DUB-E100 support MIB2/MIB2.5?

### ISSUE THREAD

**Issue by fon1105** [jilleb/mib2-toolbox#82]
My country cannot find the D-Link DUB-E100.

Does anyone try other USB to Ethernet adapter which works with MIB2/MIB2.5?

**Comment by jilleb** [comment]
I'll post a list with supported pid/vids

**Comment by dankec2000** [comment]
I'm also interested in this list, please

**Comment by jilleb** [comment]
Here's a list of pid,vid combinations I've found in the config files that should be working with the MIB2:

D-link Dub-E100:
0x2001, 0x3c05
0x2001, 0x1a02

SMSC9500:
0x0424, 0x9500

Germaneers LAN9514:
0x2721, 0xec00

Cinterion AH6A (3G)
0x1e2d, 0x0055

Cinterion ALS1/ALS6 (4G)
0x1e2d, 0x0060

Delock USB Serialadapter
0x0403, 0x6001

JRC DSRC Device
0x1145, 0x0008


Microchip-USB-Hub:
0x0424, 0x2530

SMSC-USB-Hub
0x0424, 0x4040

**Comment by andrewleech** [comment]
@fon1105 I've found on newer firmware there are a couple of ASIX generic USB3 adapters that can also be used instead: https://github.com/jilleb/mib2-toolbox/issues/119

**Comment by ecarruda** [comment]
> ASIX generic USB3

Do know now the chipset model?

**Comment by khanabid20** [comment]
> Here's a list of pid,vid combinations I've found in the config files that should be working with the MIB2:
> 
> D-link Dub-E100: 0x2001, 0x3c05 0x2001, 0x1a02
> 
> SMSC9500: 0x0424, 0x9500
> 
> Germaneers LAN9514: 0x2721, 0xec00
> 
> Cinterion AH6A (3G) 0x1e2d, 0x0055
> 
> Cinterion ALS1/ALS6 (4G) 0x1e2d, 0x0060
> 
> Delock USB Serialadapter 0x0403, 0x6001
> 
> JRC DSRC Device 0x1145, 0x0008
> 
> Microchip-USB-Hub: 0x0424, 0x2530
> 
> SMSC-USB-Hub 0x0424, 0x4040

You said you find it in some config file, can that file be instead modified ?
Also would you be able to tell me the file name ?
