### ISSUE TITLE
[OFFER] Willing to help with non-Pro device.

### ISSUE THREAD

**Issue by ElProempie** [jilleb/mib2-toolbox#85]
Since we're in the same country, I was thinking of letting you tinker with my Discover Media non-Pro. 
I have a 2016 VW Caddy. Need any info on the unit, let me know.

If you're willing, we could arrange something. I would do anything to help the community! 

If my device bricks, it's easy for me to replace as I'm in the car audio business.

**Comment by jilleb** [comment]
Thanks for the offer! I recently got a Technisat unit to play with. But....lacking the time to work on it. So currently no progress there.
