### ISSUE TITLE
Mib2 technisat

### ISSUE THREAD

**Issue by cdennis12280** [jilleb/mib2-toolbox#86]
Does this work with MIB2 TECHNISAT devices?

**Comment by jilleb** [comment]
No, that's the MIB2 Standard, which is not supported.

https://github.com/jilleb/mib2-toolbox/blob/master/FAQ.md#when-will-you-make-a-toolbox-for-mib2-standard

**Comment by cdennis12280** [comment]
cool thanks for reply, i need access to write files to fs
