### ISSUE TITLE
[REQUEST]  Exception List backup & restore

### ISSUE THREAD

**Issue by mattcabb** [jilleb/mib2-toolbox#89]
Might be useful to backup `/HBpersistence/FEC/Exceptionlist.txt` or `efs-persist/etc/prodEL.txt` as these files are used to activate some SWaP functions and are overwritten at the end of FW update with ones that don't list any FECs.

**Comment by olli991** [comment]
As you'll mpost likely use M.I.B. Toolbox for that matter now I would see this as solved because that toolbox is saving and also setting new lists.
