### ISSUE TITLE
[BUG] Error message on FW update: Medium: Device doesn't support this (MainUnit: variant)

### ISSUE THREAD

**Issue by barbalion** [jilleb/mib2-toolbox#90]
Update from the service menu doesn't start with the error message:
"Error: Variant conflict"
"Medium: Device doesn't support this (MainUnit: variant)"

**To Reproduce**
1. Insert a proper SD card (32GB, FAT)
2. Go to service menu (hold Menu for 5 secs)
3. Go to FW update and pick SD source
4. The error appears on the screen

**Firmware(please complete the following information):**
 - Brand: Skoda Kodiaq
 - Hardware-type: Device number 565035840 (MIB2.5, AFAIU), 
 - Version: MU 0478, FW: H29.319.93_STD2Plus_EU

**Comment by jilleb** [comment]
This is not a bug. You have a MIB standard and this is meant for MIB High

**Comment by barbalion** [comment]
:(
thank you!
