### ISSUE TITLE
manual installation

### ISSUE THREAD

**Issue by goerdi** [jilleb/mib2-toolbox#91]
Hi !

I have a device which complains about metainfo2.txt.
So is manual installation an option ?
If yes i do not understand the following steps

=> Developer mode enabled on module 5F (you need VCDS/OBD11/VCP for this!)
Is this mandantory ?

=>  Log in

Does it need any username / password ?
   
=> copy mqbcoding.esd to /net/mmx/mnt/app/eso/hmi/engdefs/mqbcoding.esd:
=> cp /net/mmx/fs/sda0/PersonalPOI/PayLoad/0/default/payload.sh /net/mmx/mnt/app/eso/hmi/engdefs/mqbcoding.esd

So payload.sh is mbqcoding.esd ? Or not ?
if yes better say copy payload.sh to mbqcoding.esd on device :)

Ciao Gerd

**Comment by vwjap** [comment]
You enable developer mode which adds more to the green screens so the new menu to install it shows up

Yes you need a username and password for the firmware you have, but you have to go searching for it (think I found a wiki that had it)

The cp line is actually the command you have to use in your terminal program to put the menu item onto the mmi for the install

**Comment by vwjap** [comment]
You enable developer mode which adds more to the green screens so the new menu to install it shows up

Yes you need a username and password for the firmware you have, but you have to go searching for it (think I found a wiki that had it)

The cp line is actually the command you have to use in your terminal program to put the menu item onto the mmi for the install

**Comment by vwjap** [comment]
You enable developer mode which adds more to the green screens so the new menu to install it shows up

Yes you need a username and password for the firmware you have, but you have to go searching for it (think I found a wiki that had it)

The cp line is actually the command you have to use in your terminal program to put the menu item onto the mmi for the install

**Comment by vwjap** [comment]
You enable developer mode which adds more to the green screens so the new menu to install it shows up

Yes you need a username and password for the firmware you have, but you have to go searching for it (think I found a wiki that had it)

The cp line is actually the command you have to use in your terminal program to put the menu item onto the mmi for the install

**Comment by vwjap** [comment]
You enable developer mode which adds more to the green screens so the new menu to install it shows up

Yes you need a username and password for the firmware you have, but you have to go searching for it (think I found a wiki that had it)

The cp line is actually the command you have to use in your terminal program to put the menu item onto the mmi for the install

**Comment by goerdi** [comment]
hi ! Thnx but you did not answer the main question..
if auto installation fails, does manual installation always work ? 
in my case auto does not work (mib2 high an fw 1409) so before i spend 35€ for an ethernet adapter..........

**Comment by olli991** [comment]
Manual installation always works if you have the root password!

**Comment by goerdi** [comment]
So you have fw 1409 ? can you read it out ? i googlet the half day yesterday but i came not far....

**Comment by olli991** [comment]
> So you have fw 1409 ? can you read it out ? i googlet the half day yesterday but i came not far....

Contact me via t.me/Olli991

**Comment by goerdi** [comment]
ok i, i installed this stuff, but how can i find out whta an option does ..
e.g. the options beyond navigation....

**Comment by jilleb** [comment]
make sure you read the readme, and when in doubt check the scripts inside the repository to see what they do
