### ISSUE TITLE
[BUG] compress-mcf.py not run Py 3.6

### ISSUE THREAD

**Issue by plasmocz** [jilleb/mib2-toolbox#92]
When i use tool compress-mcf.py in Python 3.6, Windows 7 64bit give **struct.error argument for 's' must be a bytes object** on line 108.

**Comment by shanapu** [comment]
use Python 2.7

**Comment by jilleb** [comment]
Indeed, I currently haven't found the time yet to convert all to Python 3, so you'll have to use 2.7
