### ISSUE TITLE
Root Password für 0687

### ISSUE THREAD

**Issue by Sensei1978** [jilleb/mib2-toolbox#93]
Hello.
I can't automatically install the MIB2Toolbox.
There is an error with Metainfo.
Now i want manually install the MIB2Toolbox.
But i don't know the Root password. I have the Discover Pro MIB2 with FW 0687.
I searched in the internet but i can't anything about the 0687.
Can anyone help me?

**Comment by jilleb** [comment]
I'm sorry, but we're not supplying root passwords here.
