### ISSUE TITLE
What about MIB3?

### ISSUE THREAD

**Issue by pedzacypociag** [jilleb/mib2-toolbox#95]
Hi, what about testing this on MIB3 Infotainment System, was it done or not? 
If not, is there a chance that mib2-toolbox should work? 
Thanks

**Comment by jilleb** [comment]
Never tested it, and I guess the chances are slim it is supported. The backdoor I'm using is very specific to the Harman units, MIB3 SWDL is quite different.


But... if someone supplies me with an MIB3, I'd be willing to look for a solution.

**Comment by pedzacypociag** [comment]
OK, thank you for the comment about this, I'll consider to share my MIB3, but for now the unit and the car is in warranty period (car's manufacture date is september 2019).

**Comment by Omario79** [comment]
I have MIB3 LG w/o navigation 

System description: MU-O-N-R2
Software number: 575035868
Software version: 0804
Hardware number: 575035868
Hardware version: H56

I need to activate th Wifi and don't know if its with SWAP code activation or its not equipped with the feature.

And is this toolbox file work on my infotainment system?

**Comment by jilleb** [comment]
It will not work on MIB3. MIB3 consists of a different hardware platform and software framework.

**Comment by Omario79** [comment]
What will not work the Wifi feature or this toolbox file ?

**Comment by jilleb** [comment]
This toolbox won't work

**Comment by Pro55624** [comment]
wait , then how can we mod the mib 3 , like whats the single way to do it ? i want carplay and wifi on it and ive been looking for some answers for some time . idk if SWaP codes would work since i aways find people using the MIB 2 onto those and idk other ways. 200 bucks just for carplay activation is insane

**Comment by jilleb** [comment]
It's not as simple as you think. It takes a lot of effort to find a way into the system and then find ways to ke useful mods that can be used by everyone. Time needs to be invested, as well as money to buy the hardware.

**Comment by Pro55624** [comment]
yeah, too bad here everyone uses this tool or Swap codes to activate android auto/ carplay for money . I barely got into this stuff and now i see how they do it, thing is instead of actually investing money here this people go as crazy as charging 70-100 bucks just for a single feature activation :(

**Comment by koldico** [comment]
Hello everyone, I would like to be able to activate the sport hmi mode in my mib 3, is there any way to do it, I have my mib 3 without patching, is there a way to patch it, thank you very much, greetings.

**Comment by jilleb** [comment]
Mib3 isn't supported by this toolbox

**Comment by jilleb** [comment]
Mib3 isn't supported by this toolbox

**Comment by koldico** [comment]
It seems that there is some toolbox for the mib3 because things are already being seen, and there are people who are already asking for money for activations, they have asked me €850 for putting the toolbox in my mib3, and 800 € for activating the sport hmi mod.

**Comment by jilleb** [comment]
850 for a toolbox 😂😂😂
Thats about 5 times as much as I got for donations on all my projects combined 😂😂😂
Smells like dirty scammers.
Don't be scammed.

**Comment by koldico** [comment]
It's just that you send the unit plus the money, surely I would be left without money and without a unit.

**Comment by koldico** [comment]
I would also like to be able to put the central vision sport in the virtual copickt, but I don't know if that could be done, as well as the sport hmi mode in the inmfotaiment if it can.

**Comment by koldico** [comment]
Apparently and they are saying through several telegram threads and some forum there is not much left to be able to patch the mib3 so it seems that the expected moment will arrive to be able to do it at once

**Comment by koldico** [comment]
Any chance of activating the exp in the mib3?

**Comment by jilleb** [comment]
This toolbox is not about patching, so the answer would always be 'no'

**Comment by koldico** [comment]
Thank you very much for responding so quickly, the truth is that this mib3 has been left and nothing can be done with it compared to the mib2 and mib2,5 hopefully in the future you will be able to access it and it can be modified like the previous ones, what I said thank you very much for the help provided.

**Comment by jilleb** [comment]
No, Mercedes is not compatible

**Comment by veso266** [comment]
Does mib3 even have Green Engeneering menu?

This mib3 (not sure how its called): https://cdn-fastly.autoguide.com/media/2023/10/18/16241/3-tips-to-make-volkswagens-mib3-touchscreen-system-easier-to-use.jpg?size=720x845&nocrop=1

Because it seams there are different versions of mib3

**Comment by koldico** [comment]
It seems there's already a way to do it; here are two examples: one with OBD and one with VCDS.
https://youtu.be/-L5ySUeKVOw
https://youtu.be/pdS5-qbmaKY

**Comment by ko4ergin** [comment]
There is already a specialist on the Russian forum who can patch MIB 3.
 For my device:
· Device part number: 654035867C
· Software (Firmware version): 1310
· AO (Equipment index): 040
· Bluetooth:
 · Software version: BGv2.11r13590 + MF0821
 · HW version: 1QD
· Android Auto: v3.2.33 + MIB3_v1.1.26
· Apple CarPlay: v3.2.33 + MIB3_v1.1.26
· MirrorLink®: 1.6.4

He requested 650 USD
Article on the Russian forum: 
https://www.drive2.ru/l/705348255164152656/

**Comment by koldico** [comment]
So far, absolutely nothing, total darkness, at least in the case of my LG MIB 3 unit MOI3GP_EU_VW_R5650L.
Software version:
2565

**Comment by ko4ergin** [comment]
I found a YouTube channel of a hacker. 
He doesn't even solder anything. 
You can hear a mouse click in the background. 
I assume that he's patching directly from his computer.
MEN3_EU_SK370_P3355L

https://youtu.be/bhw0E--t2e4?si=19K10E-i65TpTnhc

**Comment by TryPaco** [comment]
i have for you VW Parts for Testing 5G6919606C, 3G5035816P  MIB3

**Comment by koldico** [comment]
I'm not interested in changing my 13" system in my 2025 Octavia RS. I'd like to be able to program it, especially to have the Sport HMI 060400, and I wouldn't mind some other things like SFD2, such as activating developer mode.
