### ISSUE TITLE
Will this work for me?

### ISSUE THREAD

**Issue by joncy92** [jilleb/mib2-toolbox#96]
Hello,

I have a VW Golf R with Discover Pro. The software version shows H2B.28.135_HIGH2_EU

Will this mod work here?

Thanks

**Comment by jilleb** [comment]
Should work! But..... there's only 1 way to find out: try it 😄

**Comment by joncy92** [comment]
You're not wrong lol. For both install methods, the system needs to be in debug which you can only do using VCDS or similar right?

**Comment by joncy92** [comment]
Hey man is it possible to check if developer mode is enabled via the unit itself? I went to change it in VCDS but it Said it's already enabled

**Comment by joncy92** [comment]
I've get this error: unable to read release information file. Error when reading opening the file. Metainfo2.txt
