### ISSUE TITLE
No SD card slot in a car

### ISSUE THREAD

**Issue by kestonikas** [jilleb/mib2-toolbox#97]
Hi, 

I do not have SD card slot, only 2x USB-C. Tried to do with USB, no option. Any suggestions?

P.S. tried to put files to USB but it does not work.

**Comment by jilleb** [comment]
What radio is it? If it's Harmann MIB2 High, it has 2 sd slots.

**Comment by kestonikas** [comment]
I have passat variant Y2020, its discover pro and it does not have sd card slots. I have also passat alltrack Y2017 - it has 2 sd card slots.
