### ISSUE TITLE
POIBased Website imports data  

### ISSUE THREAD

**Issue by ShifengHuGit** [jilleb/mib2-toolbox#99]
Hi， 
First of all ， thnx your great effort for this work， I tried your tool on my MIB2STD， absoultely did not work， But still want to share my thoughts here。

  I merged your metainfo2.txt file with the official Upgrade ， （Just merged the Common part as I am afraid the Variant codes and Region issue， meanwhile， I re-generated the new MetafileChecksum ）。 This failed as expected at the Signature Check Step。

Based on your finding，There is a leak that MIB2HIGH allows POI import without Signature  but not for MIB2STD。

What I am thinking now is how this Website works？
https://web.poibase.com/pb/start/login/?redirect_after_login=%2Fpb%2Fhome%2Fdownload%2FdownloadPois%2F

Not sure you are aware of it ， it allows users to download POI and import the download file to the Unit（I try to import but failed again ，the reason is none of POI area for CN china ， Most of them are for EU，USA， so it failed at the very earlier step  Region Check）， the download content contains MIB2HIGH and MIB2STD， also there are Signature lines in Meta file！。。。（but even you download different POIs， the Website still gives you same Signature info， Hope there are some guys from this Region to test whether it works or not）
 if this download that from POIbase website work  I am wondering How this Website get the VW‘s private Key to sign the checksum。

**Comment by olli991** [comment]
With the background of the new install method it now could become a possibility to build a MST2 toolbox. But dont try this toolboy on mst because paths and everything is different.
